/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 23:59:18 BST 2026
 * 
 */
extern "C" {
  unsigned long long c_get_symbol_val(char *);
  char c_trygetchar(char );
}
