/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkBoot_ROM_h__
#define __mkBoot_ROM_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkBoot_ROM module */
class MOD_mkBoot_ROM : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt64> INST_rg_addr_base;
  MOD_Reg<tUInt64> INST_rg_addr_lim;
  MOD_Reg<tUInt8> INST_rg_module_ready;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_arff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_awff;
  MOD_Fifo<tUInt32> INST_slavePortShim_shim_bff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_rff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_wff;
 
 /* Constructor */
 public:
  MOD_mkBoot_ROM(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_slave_aw_put_val;
  tUWide PORT_slave_w_put_val;
  tUWide PORT_slave_ar_put_val;
  tUWide PORT_slave_r_peek;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_slavePortShim_shim_rff_i_notEmpty____d1298;
  tUInt8 DEF_slavePortShim_shim_bff_i_notEmpty____d1297;
 
 /* Local definitions */
 private:
  tUInt32 DEF_v__h6591;
  tUInt32 DEF_v__h915;
  tUWide DEF_slavePortShim_shim_arff_first____d8;
  tUWide DEF_slavePortShim_shim_awff_first____d1244;
  tUInt64 DEF_lim__h6417;
  tUInt64 DEF_base__h6415;
  tUWide DEF_slavePortShim_shim_arff_first_BITS_100_TO_93_8_ETC___d1233;
 
 /* Rules */
 public:
  void RL_rl_process_rd_req();
  void RL_rl_process_wr_req();
 
 /* Methods */
 public:
  void METH_set_addr_map(tUInt64 ARG_set_addr_map_addr_base, tUInt64 ARG_set_addr_map_addr_lim);
  tUInt8 METH_RDY_set_addr_map();
  tUInt8 METH_slave_aw_canPut();
  tUInt8 METH_RDY_slave_aw_canPut();
  void METH_slave_aw_put(tUWide ARG_slave_aw_put_val);
  tUInt8 METH_RDY_slave_aw_put();
  tUInt8 METH_slave_w_canPut();
  tUInt8 METH_RDY_slave_w_canPut();
  void METH_slave_w_put(tUWide ARG_slave_w_put_val);
  tUInt8 METH_RDY_slave_w_put();
  tUInt8 METH_slave_b_canPeek();
  tUInt8 METH_RDY_slave_b_canPeek();
  tUInt32 METH_slave_b_peek();
  tUInt8 METH_RDY_slave_b_peek();
  void METH_slave_b_drop();
  tUInt8 METH_RDY_slave_b_drop();
  tUInt8 METH_slave_ar_canPut();
  tUInt8 METH_RDY_slave_ar_canPut();
  void METH_slave_ar_put(tUWide ARG_slave_ar_put_val);
  tUInt8 METH_RDY_slave_ar_put();
  tUInt8 METH_slave_r_canPeek();
  tUInt8 METH_RDY_slave_r_canPeek();
  tUWide METH_slave_r_peek();
  tUInt8 METH_RDY_slave_r_peek();
  void METH_slave_r_drop();
  tUInt8 METH_RDY_slave_r_drop();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBoot_ROM &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBoot_ROM &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBoot_ROM &backing);
};

#endif /* ifndef __mkBoot_ROM_h__ */
