/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkBtb_h__
#define __mkBtb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkBtb module */
class MOD_mkBtb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUWide> INST_btb_addr_reg;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_0_clearCount;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_0_clearReg;
  MOD_Reg<tUInt32> INST_btb_compressedRecords_0_lookupReg;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_0_mem_0_bram;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_0_mem_1_bram;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_0_updateFresh;
  MOD_Wire<tUInt8> INST_btb_compressedRecords_0_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_0_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_0_updateKeys_0_bram;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_0_updateKeys_1_bram;
  MOD_Reg<tUInt64> INST_btb_compressedRecords_0_updateReg;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_0_wayNext;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_1_clearCount;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_1_clearReg;
  MOD_Reg<tUInt32> INST_btb_compressedRecords_1_lookupReg;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_1_mem_0_bram;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_1_mem_1_bram;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_1_updateFresh;
  MOD_Wire<tUInt8> INST_btb_compressedRecords_1_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_1_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_1_updateKeys_0_bram;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_1_updateKeys_1_bram;
  MOD_Reg<tUInt64> INST_btb_compressedRecords_1_updateReg;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_1_wayNext;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_2_clearCount;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_2_clearReg;
  MOD_Reg<tUInt32> INST_btb_compressedRecords_2_lookupReg;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_2_mem_0_bram;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_2_mem_1_bram;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_2_updateFresh;
  MOD_Wire<tUInt8> INST_btb_compressedRecords_2_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_2_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_2_updateKeys_0_bram;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_2_updateKeys_1_bram;
  MOD_Reg<tUInt64> INST_btb_compressedRecords_2_updateReg;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_2_wayNext;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_3_clearCount;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_3_clearReg;
  MOD_Reg<tUInt32> INST_btb_compressedRecords_3_lookupReg;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_3_mem_0_bram;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_btb_compressedRecords_3_mem_1_bram;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_3_updateFresh;
  MOD_Wire<tUInt8> INST_btb_compressedRecords_3_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_3_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_3_updateKeys_0_bram;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_compressedRecords_3_updateKeys_1_bram;
  MOD_Reg<tUInt64> INST_btb_compressedRecords_3_updateReg;
  MOD_Reg<tUInt8> INST_btb_compressedRecords_3_wayNext;
  MOD_Reg<tUInt8> INST_btb_fullRecords_0_clearCount;
  MOD_Reg<tUInt8> INST_btb_fullRecords_0_clearReg;
  MOD_Reg<tUInt32> INST_btb_fullRecords_0_lookupReg;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_btb_fullRecords_0_mem_0_bram;
  MOD_Reg<tUInt8> INST_btb_fullRecords_0_updateFresh;
  MOD_Wire<tUInt8> INST_btb_fullRecords_0_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_fullRecords_0_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_fullRecords_0_updateKeys_0_bram;
  MOD_Reg<tUWide> INST_btb_fullRecords_0_updateReg;
  MOD_Reg<tUInt8> INST_btb_fullRecords_1_clearCount;
  MOD_Reg<tUInt8> INST_btb_fullRecords_1_clearReg;
  MOD_Reg<tUInt32> INST_btb_fullRecords_1_lookupReg;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_btb_fullRecords_1_mem_0_bram;
  MOD_Reg<tUInt8> INST_btb_fullRecords_1_updateFresh;
  MOD_Wire<tUInt8> INST_btb_fullRecords_1_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_fullRecords_1_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_fullRecords_1_updateKeys_0_bram;
  MOD_Reg<tUWide> INST_btb_fullRecords_1_updateReg;
  MOD_Reg<tUInt8> INST_btb_fullRecords_2_clearCount;
  MOD_Reg<tUInt8> INST_btb_fullRecords_2_clearReg;
  MOD_Reg<tUInt32> INST_btb_fullRecords_2_lookupReg;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_btb_fullRecords_2_mem_0_bram;
  MOD_Reg<tUInt8> INST_btb_fullRecords_2_updateFresh;
  MOD_Wire<tUInt8> INST_btb_fullRecords_2_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_fullRecords_2_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_fullRecords_2_updateKeys_0_bram;
  MOD_Reg<tUWide> INST_btb_fullRecords_2_updateReg;
  MOD_Reg<tUInt8> INST_btb_fullRecords_3_clearCount;
  MOD_Reg<tUInt8> INST_btb_fullRecords_3_clearReg;
  MOD_Reg<tUInt32> INST_btb_fullRecords_3_lookupReg;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_btb_fullRecords_3_mem_0_bram;
  MOD_Reg<tUInt8> INST_btb_fullRecords_3_updateFresh;
  MOD_Wire<tUInt8> INST_btb_fullRecords_3_updateFresh_1;
  MOD_Reg<tUInt8> INST_btb_fullRecords_3_updateInsert;
  MOD_BRAM<tUInt8,tUInt32,tUInt8> INST_btb_fullRecords_3_updateKeys_0_bram;
  MOD_Reg<tUWide> INST_btb_fullRecords_3_updateReg;
  MOD_Reg<tUWide> INST_btb_updateEn;
  MOD_Wire<tUWide> INST_btb_updateEn_1;
 
 /* Constructor */
 public:
  MOD_mkBtb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_update_pc;
  tUWide PORT_update_brTarget;
  tUWide PORT_put_pc_pc;
  tUWide PORT_pred;
 
 /* Publicly accessible definitions */
 public:
  tUWide DEF_btb_updateEn___d245;
 
 /* Local definitions */
 private:
  tUWide DEF__dfoo94;
  tUWide DEF__dfoo88;
  tUWide DEF__dfoo82;
  tUWide DEF__dfoo76;
  tUWide DEF__dfoo222;
  tUWide DEF__dfoo158;
  tUWide DEF__dfoo216;
  tUWide DEF__dfoo152;
  tUWide DEF__dfoo210;
  tUWide DEF__dfoo146;
  tUWide DEF__dfoo204;
  tUWide DEF__dfoo140;
  tUInt8 DEF_a__h10925;
  tUInt8 DEF_a__h9387;
  tUInt8 DEF_a__h7849;
  tUInt8 DEF_a__h6311;
  tUWide DEF_btb_updateEn_1_wget____d242;
  tUWide DEF_btb_fullRecords_3_updateReg___d80;
  tUWide DEF_btb_fullRecords_2_updateReg___d56;
  tUWide DEF_btb_fullRecords_1_updateReg___d32;
  tUWide DEF_btb_fullRecords_0_updateReg___d8;
  tUWide DEF_btb_fullRecords_3_mem_0_bram_b_read____d403;
  tUWide DEF_btb_fullRecords_2_mem_0_bram_b_read____d448;
  tUWide DEF_btb_fullRecords_1_mem_0_bram_b_read____d492;
  tUWide DEF_btb_fullRecords_0_mem_0_bram_b_read____d359;
  tUWide DEF_x__h38915;
  tUInt64 DEF_btb_compressedRecords_3_updateReg___d214;
  tUInt64 DEF_btb_compressedRecords_2_updateReg___d178;
  tUInt64 DEF_btb_compressedRecords_1_updateReg___d142;
  tUInt64 DEF_btb_compressedRecords_0_updateReg___d106;
  tUWide DEF_btb_fullRecords_3_updateReg_0_BITS_129_TO_0___d89;
  tUWide DEF_btb_fullRecords_2_updateReg_6_BITS_129_TO_0___d65;
  tUWide DEF_btb_fullRecords_1_updateReg_2_BITS_129_TO_0___d41;
  tUWide DEF_btb_fullRecords_0_updateReg_BITS_129_TO_0___d17;
  tUWide DEF_x__h15039;
  tUWide DEF__read_value_d__h4541;
  tUWide DEF__read_value_d__h3468;
  tUWide DEF__read_value_d__h2395;
  tUWide DEF__read_value_d__h1295;
  tUWide DEF_x_b_read_value_d__h38441;
  tUWide DEF_x_b_read_value_d__h38375;
  tUWide DEF_x_b_read_value_d__h38309;
  tUWide DEF_x_b_read_value_d__h38507;
  tUWide DEF_btb_updateEn_45_BITS_258_TO_146___d249;
  tUWide DEF_btb_updateEn_45_BITS_129_TO_17___d250;
  tUWide DEF_x_BITS_128_TO_16___h38917;
  tUInt32 DEF_x__h4534;
  tUInt32 DEF_x__h3461;
  tUInt32 DEF_x__h2388;
  tUInt32 DEF_x__h1288;
  tUInt32 DEF_y__h10651;
  tUInt32 DEF_y__h9113;
  tUInt32 DEF_y__h7575;
  tUInt32 DEF_y__h6023;
  tUInt8 DEF_a__h4523;
  tUInt8 DEF_a__h3450;
  tUInt8 DEF_a__h2377;
  tUInt8 DEF_a__h1277;
  tUWide DEF_IF_NEG_btb_addr_reg_22_BITS_2_TO_1_23_24_BIT_0_ETC___d508;
  tUWide DEF_IF_btb_compressedRecords_0_updateReg_06_BITS_2_ETC___d505;
  tUWide DEF_IF_btb_compressedRecords_1_updateReg_42_BITS_2_ETC___d507;
  tUWide DEF_IF_NEG_btb_addr_reg_22_BITS_2_TO_1_23_24_BIT_0_ETC___d513;
  tUWide DEF_IF_btb_compressedRecords_2_updateReg_78_BITS_2_ETC___d510;
  tUWide DEF_IF_btb_compressedRecords_3_updateReg_14_BITS_2_ETC___d512;
  tUWide DEF_IF_btb_updateEn_1_whas__41_THEN_btb_updateEn_1_ETC___d244;
  tUWide DEF__0_CONCAT_DONTCARE___d243;
  tUWide DEF_IF_btb_fullRecords_3_clearReg_6_THEN_0_ELSE_bt_ETC___d91;
  tUWide DEF_btb_fullRecords_3_updateReg_0_BITS_152_TO_137__ETC___d90;
  tUWide DEF_IF_btb_fullRecords_2_clearReg_2_THEN_0_ELSE_bt_ETC___d67;
  tUWide DEF_btb_fullRecords_2_updateReg_6_BITS_152_TO_137__ETC___d66;
  tUWide DEF_IF_btb_fullRecords_1_clearReg_8_THEN_0_ELSE_bt_ETC___d43;
  tUWide DEF_btb_fullRecords_1_updateReg_2_BITS_152_TO_137__ETC___d42;
  tUWide DEF_IF_btb_fullRecords_0_clearReg_THEN_0_ELSE_btb__ETC___d19;
  tUWide DEF_btb_fullRecords_0_updateReg_BITS_152_TO_137_CO_ETC___d18;
  tUWide DEF_IF_btb_compressedRecords_1_updateReg_42_BITS_2_ETC___d504;
  tUWide DEF_IF_btb_compressedRecords_1_updateReg_42_BITS_2_ETC___d485;
  tUWide DEF_btb_fullRecords_1_updateReg_2_BITS_136_TO_130__ETC___d503;
  tUWide DEF_IF_btb_compressedRecords_2_updateReg_78_BITS_2_ETC___d460;
  tUWide DEF_IF_btb_compressedRecords_2_updateReg_78_BITS_2_ETC___d441;
  tUWide DEF_btb_fullRecords_2_updateReg_6_BITS_136_TO_130__ETC___d459;
  tUWide DEF_IF_btb_compressedRecords_0_updateReg_06_BITS_2_ETC___d371;
  tUWide DEF_IF_btb_compressedRecords_0_updateReg_06_BITS_2_ETC___d352;
  tUWide DEF_btb_fullRecords_0_updateReg_BITS_136_TO_130_5__ETC___d370;
  tUWide DEF_IF_btb_compressedRecords_3_updateReg_14_BITS_2_ETC___d415;
  tUWide DEF_IF_btb_compressedRecords_3_updateReg_14_BITS_2_ETC___d396;
  tUWide DEF_btb_fullRecords_3_updateReg_0_BITS_136_TO_130__ETC___d414;
  tUWide DEF_IF_btb_fullRecords_1_updateReg_2_BITS_136_TO_1_ETC___d502;
  tUWide DEF_IF_btb_fullRecords_2_updateReg_6_BITS_136_TO_1_ETC___d458;
  tUWide DEF_IF_btb_fullRecords_3_updateReg_0_BITS_136_TO_1_ETC___d413;
  tUWide DEF_IF_btb_fullRecords_0_updateReg_BITS_136_TO_130_ETC___d369;
  tUWide DEF_IF_btb_compressedRecords_3_updateReg_14_BITS_2_ETC___d511;
  tUWide DEF_IF_btb_compressedRecords_2_updateReg_78_BITS_2_ETC___d509;
  tUWide DEF_IF_btb_compressedRecords_0_updateReg_06_BITS_2_ETC___d416;
  tUWide DEF_IF_btb_compressedRecords_1_updateReg_42_BITS_2_ETC___d506;
  tUWide DEF__1_CONCAT_update_pc_CONCAT_update_brTarget_CONC_ETC___d515;
  tUWide DEF_update_brTarget_CONCAT_update_taken___d514;
  tUWide DEF_btb_updateEn_45_BITS_155_TO_140_56_XOR_btb_upd_ETC___d278;
 
 /* Rules */
 public:
  void RL_btb_fullRecords_0_updateFresh__dreg_update();
  void RL_btb_fullRecords_0_updateCanon();
  void RL_btb_fullRecords_1_updateFresh__dreg_update();
  void RL_btb_fullRecords_1_updateCanon();
  void RL_btb_fullRecords_2_updateFresh__dreg_update();
  void RL_btb_fullRecords_2_updateCanon();
  void RL_btb_fullRecords_3_updateFresh__dreg_update();
  void RL_btb_fullRecords_3_updateCanon();
  void RL_btb_compressedRecords_0_updateFresh__dreg_update();
  void RL_btb_compressedRecords_0_updateCanon();
  void RL_btb_compressedRecords_1_updateFresh__dreg_update();
  void RL_btb_compressedRecords_1_updateCanon();
  void RL_btb_compressedRecords_2_updateFresh__dreg_update();
  void RL_btb_compressedRecords_2_updateCanon();
  void RL_btb_compressedRecords_3_updateFresh__dreg_update();
  void RL_btb_compressedRecords_3_updateCanon();
  void RL_btb_updateEn__dreg_update();
  void RL_btb_canonUpdate();
 
 /* Methods */
 public:
  tUInt8 METH_flush_done();
  tUInt8 METH_RDY_flush_done();
  void METH_put_pc(tUWide ARG_put_pc_pc);
  tUInt8 METH_RDY_put_pc();
  tUWide METH_pred();
  tUInt8 METH_RDY_pred();
  void METH_update(tUWide ARG_update_pc, tUWide ARG_update_brTarget, tUInt8 ARG_update_taken);
  tUInt8 METH_RDY_update();
  void METH_flush();
  tUInt8 METH_RDY_flush();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkBtb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkBtb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkBtb &backing);
};

#endif /* ifndef __mkBtb_h__ */
