/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkDummyStoreBuffer_h__
#define __mkDummyStoreBuffer_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkDummyStoreBuffer module */
class MOD_mkDummyStoreBuffer : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_mkDummyStoreBuffer(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_data;
  tUWide PORT_deq;
  tUWide PORT_issue;
  tUWide PORT_search;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF__0_CONCAT_DONTCARE___d1;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt8 METH_isEmpty();
  tUInt8 METH_RDY_isEmpty();
  tUInt8 METH_getEnqIndex(tUInt64 ARG_getEnqIndex_paddr);
  tUInt8 METH_RDY_getEnqIndex();
  tUWide METH_search(tUInt64 ARG_search_paddr, tUInt32 ARG_search_be);
  tUInt8 METH_RDY_search();
  tUInt8 METH_noMatchLdQ(tUInt64 ARG_noMatchLdQ_paddr, tUInt32 ARG_noMatchLdQ_be);
  tUInt8 METH_RDY_noMatchLdQ();
  tUInt8 METH_noMatchStQ(tUInt64 ARG_noMatchStQ_paddr, tUInt32 ARG_noMatchStQ_be);
  tUInt8 METH_RDY_noMatchStQ();
  void METH_enq(tUInt8 ARG_enq_idx,
		tUInt64 ARG_enq_paddr,
		tUInt32 ARG_enq_be,
		tUWide ARG_enq_data,
		tUInt32 ARG_enq_pcHash,
		tUInt8 ARG_enq_permitPoison);
  tUInt8 METH_RDY_enq();
  tUWide METH_deq(tUInt8 ARG_deq_idx);
  tUInt8 METH_RDY_deq();
  tUWide METH_issue();
  tUInt8 METH_RDY_issue();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDummyStoreBuffer &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDummyStoreBuffer &backing);
};

#endif /* ifndef __mkDummyStoreBuffer_h__ */
