/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkDummyStoreBuffer.h"


/* Literal declarations */
static unsigned int const UWide_literal_657_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    43690u };
static tUWide const UWide_literal_657_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(657u,
																									    UWide_literal_657_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);
static unsigned int const UWide_literal_655_h2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    2863311530u,
																											    10922u };
static tUWide const UWide_literal_655_h2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(655u,
																									    UWide_literal_655_h2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);
static unsigned int const UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
											2863311530u,
											2863311530u,
											2863311530u,
											0u };
static tUWide const UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(130u,
									UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);


/* String declarations */
static std::string const __str_literal_1("\n%m: ASSERT FAIL!!", 18u);
static std::string const __str_literal_2("Dynamic assertion failed: \"../../src_Core/RISCY_OOO/procs/lib/StoreBuffer.bsv\", line 321, column 25\nenq should never be called)",
					 127u);
static std::string const __str_literal_3("Dynamic assertion failed: \"../../src_Core/RISCY_OOO/procs/lib/StoreBuffer.bsv\", line 324, column 25\ndeq should never be called)",
					 127u);
static std::string const __str_literal_4("Dynamic assertion failed: \"../../src_Core/RISCY_OOO/procs/lib/StoreBuffer.bsv\", line 328, column 25\nissue should never be called)",
					 129u);


/* Constructor */
MOD_mkDummyStoreBuffer::MOD_mkDummyStoreBuffer(tSimStateHdl simHdl,
					       char const *name,
					       Module *parent)
  : Module(simHdl, name, parent), __clk_handle_0(BAD_CLOCK_HANDLE), PORT_RST_N((tUInt8)1u)
{
  PORT_enq_data.setSize(129u);
  PORT_enq_data.clear();
  PORT_deq.setSize(655u);
  PORT_deq.clear();
  PORT_issue.setSize(657u);
  PORT_issue.clear();
  PORT_search.setSize(133u);
  PORT_search.clear();
  symbol_count = 4u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkDummyStoreBuffer::init_symbols_0()
{
  init_symbol(&symbols[0u], "deq", SYM_PORT, &PORT_deq, 655u);
  init_symbol(&symbols[1u], "enq_data", SYM_PORT, &PORT_enq_data, 129u);
  init_symbol(&symbols[2u], "issue", SYM_PORT, &PORT_issue, 657u);
  init_symbol(&symbols[3u], "search", SYM_PORT, &PORT_search, 133u);
}


/* Rule actions */


/* Methods */

tUInt8 MOD_mkDummyStoreBuffer::METH_isEmpty()
{
  tUInt8 PORT_isEmpty;
  PORT_isEmpty = (tUInt8)1u;
  return PORT_isEmpty;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_isEmpty()
{
  tUInt8 DEF_CAN_FIRE_isEmpty;
  tUInt8 PORT_RDY_isEmpty;
  DEF_CAN_FIRE_isEmpty = (tUInt8)1u;
  PORT_RDY_isEmpty = DEF_CAN_FIRE_isEmpty;
  return PORT_RDY_isEmpty;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_getEnqIndex(tUInt64 ARG_getEnqIndex_paddr)
{
  tUInt8 PORT_getEnqIndex;
  DEF__0_CONCAT_DONTCARE___d1 = (tUInt8)2u;
  PORT_getEnqIndex = DEF__0_CONCAT_DONTCARE___d1;
  return PORT_getEnqIndex;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_getEnqIndex()
{
  tUInt8 DEF_CAN_FIRE_getEnqIndex;
  tUInt8 PORT_RDY_getEnqIndex;
  DEF_CAN_FIRE_getEnqIndex = (tUInt8)1u;
  PORT_RDY_getEnqIndex = DEF_CAN_FIRE_getEnqIndex;
  return PORT_RDY_getEnqIndex;
}

tUWide MOD_mkDummyStoreBuffer::METH_search(tUInt64 ARG_search_paddr, tUInt32 ARG_search_be)
{
  DEF__0_CONCAT_DONTCARE___d1 = (tUInt8)2u;
  PORT_search.set_bits_in_word((tUInt8)31u & ((DEF__0_CONCAT_DONTCARE___d1 << 2u) | UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_bits_in_word8(4u,
																			  0u,
																			  2u)),
			       4u,
			       0u,
			       5u).set_whole_word(UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(3u),
						  3u).set_whole_word(UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(2u),
								     2u).set_whole_word(UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(1u),
											1u).set_whole_word(UWide_literal_130_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.get_whole_word(0u),
													   0u);
  return PORT_search;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_search()
{
  tUInt8 DEF_CAN_FIRE_search;
  tUInt8 PORT_RDY_search;
  DEF_CAN_FIRE_search = (tUInt8)1u;
  PORT_RDY_search = DEF_CAN_FIRE_search;
  return PORT_RDY_search;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_noMatchLdQ(tUInt64 ARG_noMatchLdQ_paddr,
					       tUInt32 ARG_noMatchLdQ_be)
{
  tUInt8 PORT_noMatchLdQ;
  PORT_noMatchLdQ = (tUInt8)1u;
  return PORT_noMatchLdQ;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_noMatchLdQ()
{
  tUInt8 DEF_CAN_FIRE_noMatchLdQ;
  tUInt8 PORT_RDY_noMatchLdQ;
  DEF_CAN_FIRE_noMatchLdQ = (tUInt8)1u;
  PORT_RDY_noMatchLdQ = DEF_CAN_FIRE_noMatchLdQ;
  return PORT_RDY_noMatchLdQ;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_noMatchStQ(tUInt64 ARG_noMatchStQ_paddr,
					       tUInt32 ARG_noMatchStQ_be)
{
  tUInt8 PORT_noMatchStQ;
  PORT_noMatchStQ = (tUInt8)1u;
  return PORT_noMatchStQ;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_noMatchStQ()
{
  tUInt8 DEF_CAN_FIRE_noMatchStQ;
  tUInt8 PORT_RDY_noMatchStQ;
  DEF_CAN_FIRE_noMatchStQ = (tUInt8)1u;
  PORT_RDY_noMatchStQ = DEF_CAN_FIRE_noMatchStQ;
  return PORT_RDY_noMatchStQ;
}

void MOD_mkDummyStoreBuffer::METH_enq(tUInt8 ARG_enq_idx,
				      tUInt64 ARG_enq_paddr,
				      tUInt32 ARG_enq_be,
				      tUWide ARG_enq_data,
				      tUInt32 ARG_enq_pcHash,
				      tUInt8 ARG_enq_permitPoison)
{
  PORT_enq_data = ARG_enq_data;
  dollar_fdisplay(sim_hdl, this, "32,s", 2147483650u, &__str_literal_1);
  dollar_display(sim_hdl, this, "s", &__str_literal_2);
  dollar_finish(sim_hdl, "32", 0u);
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_enq()
{
  tUInt8 DEF_CAN_FIRE_enq;
  tUInt8 PORT_RDY_enq;
  DEF_CAN_FIRE_enq = (tUInt8)1u;
  PORT_RDY_enq = DEF_CAN_FIRE_enq;
  return PORT_RDY_enq;
}

tUWide MOD_mkDummyStoreBuffer::METH_deq(tUInt8 ARG_deq_idx)
{
  PORT_deq = UWide_literal_655_h2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;
  dollar_fdisplay(sim_hdl, this, "32,s", 2147483650u, &__str_literal_1);
  dollar_display(sim_hdl, this, "s", &__str_literal_3);
  dollar_finish(sim_hdl, "32", 0u);
  return PORT_deq;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_deq()
{
  tUInt8 DEF_CAN_FIRE_deq;
  tUInt8 PORT_RDY_deq;
  DEF_CAN_FIRE_deq = (tUInt8)1u;
  PORT_RDY_deq = DEF_CAN_FIRE_deq;
  return PORT_RDY_deq;
}

tUWide MOD_mkDummyStoreBuffer::METH_issue()
{
  PORT_issue = UWide_literal_657_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa;
  dollar_fdisplay(sim_hdl, this, "32,s", 2147483650u, &__str_literal_1);
  dollar_display(sim_hdl, this, "s", &__str_literal_4);
  dollar_finish(sim_hdl, "32", 0u);
  return PORT_issue;
}

tUInt8 MOD_mkDummyStoreBuffer::METH_RDY_issue()
{
  tUInt8 DEF_CAN_FIRE_issue;
  tUInt8 PORT_RDY_issue;
  DEF_CAN_FIRE_issue = (tUInt8)1u;
  PORT_RDY_issue = DEF_CAN_FIRE_issue;
  return PORT_RDY_issue;
}


/* Reset routines */

void MOD_mkDummyStoreBuffer::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkDummyStoreBuffer::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkDummyStoreBuffer::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_mkDummyStoreBuffer::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 6u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_DONTCARE___d1", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "deq", 655u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "enq_data", 129u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "issue", 657u);
  vcd_write_def(sim_hdl, num++, "search", 133u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkDummyStoreBuffer::dump_VCD(tVCDDumpType dt,
				      unsigned int levels,
				      MOD_mkDummyStoreBuffer &backing)
{
  vcd_defs(dt, backing);
}

void MOD_mkDummyStoreBuffer::vcd_defs(tVCDDumpType dt, MOD_mkDummyStoreBuffer &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 655u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 657u);
    vcd_write_x(sim_hdl, num++, 133u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_DONTCARE___d1) != DEF__0_CONCAT_DONTCARE___d1)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_DONTCARE___d1, 3u);
	backing.DEF__0_CONCAT_DONTCARE___d1 = DEF__0_CONCAT_DONTCARE___d1;
      }
      ++num;
      if ((backing.PORT_deq) != PORT_deq)
      {
	vcd_write_val(sim_hdl, num, PORT_deq, 655u);
	backing.PORT_deq = PORT_deq;
      }
      ++num;
      if ((backing.PORT_enq_data) != PORT_enq_data)
      {
	vcd_write_val(sim_hdl, num, PORT_enq_data, 129u);
	backing.PORT_enq_data = PORT_enq_data;
      }
      ++num;
      if ((backing.PORT_issue) != PORT_issue)
      {
	vcd_write_val(sim_hdl, num, PORT_issue, 657u);
	backing.PORT_issue = PORT_issue;
      }
      ++num;
      if ((backing.PORT_search) != PORT_search)
      {
	vcd_write_val(sim_hdl, num, PORT_search, 133u);
	backing.PORT_search = PORT_search;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_DONTCARE___d1, 3u);
      backing.DEF__0_CONCAT_DONTCARE___d1 = DEF__0_CONCAT_DONTCARE___d1;
      vcd_write_val(sim_hdl, num++, PORT_deq, 655u);
      backing.PORT_deq = PORT_deq;
      vcd_write_val(sim_hdl, num++, PORT_enq_data, 129u);
      backing.PORT_enq_data = PORT_enq_data;
      vcd_write_val(sim_hdl, num++, PORT_issue, 657u);
      backing.PORT_issue = PORT_issue;
      vcd_write_val(sim_hdl, num++, PORT_search, 133u);
      backing.PORT_search = PORT_search;
    }
}
