/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkEpochManager_h__
#define __mkEpochManager_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkEpochManager module */
class MOD_mkEpochManager : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_curr_epoch;
  MOD_Reg<tUInt8> INST_prev_checked_epoch;
  MOD_Wire<tUInt8> INST_updatePrevEn_0_lat_0;
  MOD_Wire<tUInt8> INST_updatePrevEn_0_lat_1;
  MOD_Reg<tUInt8> INST_updatePrevEn_0_rl;
  MOD_Wire<tUInt8> INST_updatePrevEn_1_lat_0;
  MOD_Wire<tUInt8> INST_updatePrevEn_1_lat_1;
  MOD_Reg<tUInt8> INST_updatePrevEn_1_rl;
 
 /* Constructor */
 public:
  MOD_mkEpochManager(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_x__h3370;
  tUInt8 DEF_x__h3367;
  tUInt8 DEF_next_epoch__h81;
 
 /* Local definitions */
 private:
  tUInt8 DEF_updatePrevEn_1_rl___d12;
  tUInt8 DEF_updatePrevEn_1_lat_0_wget____d11;
  tUInt8 DEF_updatePrevEn_0_rl___d5;
  tUInt8 DEF_updatePrevEn_0_lat_0_wget____d4;
  tUInt8 DEF_updatePrevEn_1_lat_0_whas____d10;
  tUInt8 DEF_updatePrevEn_0_lat_0_whas____d3;
  tUInt8 DEF_x__h730;
  tUInt8 DEF_x__h729;
  tUInt8 DEF_updatePrevEn_0_rl_BIT_4___d21;
  tUInt8 DEF_updatePrevEn_0_lat_0_wget_BIT_4___d20;
  tUInt8 DEF_IF_updatePrevEn_0_lat_0_whas_THEN_updatePrevEn_ETC___d22;
  tUInt8 DEF_checkedEpoch__h3097;
 
 /* Rules */
 public:
  void RL_updatePrevEn_0_canon();
  void RL_updatePrevEn_1_canon();
  void RL_canon_prev_checked_epoch();
 
 /* Methods */
 public:
  tUInt8 METH_checkEpoch_0_check(tUInt8 ARG_checkEpoch_0_check_e);
  tUInt8 METH_RDY_checkEpoch_0_check();
  tUInt8 METH_checkEpoch_1_check(tUInt8 ARG_checkEpoch_1_check_e);
  tUInt8 METH_RDY_checkEpoch_1_check();
  void METH_updatePrevEpoch_0_update(tUInt8 ARG_updatePrevEpoch_0_update_e);
  tUInt8 METH_RDY_updatePrevEpoch_0_update();
  void METH_updatePrevEpoch_1_update(tUInt8 ARG_updatePrevEpoch_1_update_e);
  tUInt8 METH_RDY_updatePrevEpoch_1_update();
  tUInt8 METH_getEpoch();
  tUInt8 METH_RDY_getEpoch();
  void METH_incrementEpoch();
  tUInt8 METH_RDY_incrementEpoch();
  tUInt8 METH_getEpochState();
  tUInt8 METH_RDY_getEpochState();
  tUInt8 METH_isFull_ehrPort0();
  tUInt8 METH_RDY_isFull_ehrPort0();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkEpochManager &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkEpochManager &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkEpochManager &backing);
};

#endif /* ifndef __mkEpochManager_h__ */
