/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkFpuMulDivDispToRegFifo.h"


/* String declarations */
static std::string const __str_literal_1("\n%m: ASSERT FAIL!!", 18u);
static std::string const __str_literal_2("Dynamic assertion failed: \"../../src_Core/RISCY_OOO/procs/lib/SpecFifo.bsv\", line 151, column 34\nenq entry cannot be valid",
					 122u);


/* Constructor */
MOD_mkFpuMulDivDispToRegFifo::MOD_mkFpuMulDivDispToRegFifo(tSimStateHdl simHdl,
							   char const *name,
							   Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_m_m_deqP_ehr_lat_0(simHdl, "m_m_deqP_ehr_lat_0", this, 0u),
    INST_m_m_deqP_ehr_lat_1(simHdl, "m_m_deqP_ehr_lat_1", this, 0u),
    INST_m_m_row_0(simHdl, "m_m_row_0", this, 79u),
    INST_m_m_specBits_0_lat_0(simHdl, "m_m_specBits_0_lat_0", this, 12u, (tUInt8)0u),
    INST_m_m_specBits_0_lat_1(simHdl, "m_m_specBits_0_lat_1", this, 12u, (tUInt8)0u),
    INST_m_m_specBits_0_rl(simHdl, "m_m_specBits_0_rl", this, 12u, 2730u, (tUInt8)0u),
    INST_m_m_valid_0_lat_0(simHdl, "m_m_valid_0_lat_0", this, 1u, (tUInt8)0u),
    INST_m_m_valid_0_lat_1(simHdl, "m_m_valid_0_lat_1", this, 1u, (tUInt8)0u),
    INST_m_m_valid_0_rl(simHdl, "m_m_valid_0_rl", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_m_m_wrongSpec_canon_conflict(simHdl, "m_m_wrongSpec_canon_conflict", this, 0u),
    INST_m_m_wrongSpec_deq_conflict(simHdl, "m_m_wrongSpec_deq_conflict", this, 0u),
    INST_m_m_wrongSpec_enq_conflict(simHdl, "m_m_wrongSpec_enq_conflict", this, 0u),
    PORT_RST_N((tUInt8)1u),
    DEF_m_m_row_0___d27(79u),
    DEF_enq_x_BITS_90_TO_12___d21(79u)
{
  PORT_enq_x.setSize(91u);
  PORT_enq_x.clear();
  PORT_first.setSize(91u);
  PORT_first.clear();
  symbol_count = 17u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkFpuMulDivDispToRegFifo::init_symbols_0()
{
  init_symbol(&symbols[0u], "enq_x", SYM_PORT, &PORT_enq_x, 91u);
  init_symbol(&symbols[1u], "first", SYM_PORT, &PORT_first, 91u);
  init_symbol(&symbols[2u], "m_m_deqP_ehr_lat_0", SYM_MODULE, &INST_m_m_deqP_ehr_lat_0);
  init_symbol(&symbols[3u], "m_m_deqP_ehr_lat_1", SYM_MODULE, &INST_m_m_deqP_ehr_lat_1);
  init_symbol(&symbols[4u], "m_m_row_0", SYM_MODULE, &INST_m_m_row_0);
  init_symbol(&symbols[5u], "m_m_specBits_0_lat_0", SYM_MODULE, &INST_m_m_specBits_0_lat_0);
  init_symbol(&symbols[6u], "m_m_specBits_0_lat_1", SYM_MODULE, &INST_m_m_specBits_0_lat_1);
  init_symbol(&symbols[7u], "m_m_specBits_0_rl", SYM_MODULE, &INST_m_m_specBits_0_rl);
  init_symbol(&symbols[8u], "m_m_valid_0_lat_0", SYM_MODULE, &INST_m_m_valid_0_lat_0);
  init_symbol(&symbols[9u], "m_m_valid_0_lat_1", SYM_MODULE, &INST_m_m_valid_0_lat_1);
  init_symbol(&symbols[10u], "m_m_valid_0_rl", SYM_MODULE, &INST_m_m_valid_0_rl);
  init_symbol(&symbols[11u], "m_m_valid_0_rl__h2361", SYM_DEF, &DEF_m_m_valid_0_rl__h2361, 1u);
  init_symbol(&symbols[12u],
	      "m_m_wrongSpec_canon_conflict",
	      SYM_MODULE,
	      &INST_m_m_wrongSpec_canon_conflict);
  init_symbol(&symbols[13u],
	      "m_m_wrongSpec_deq_conflict",
	      SYM_MODULE,
	      &INST_m_m_wrongSpec_deq_conflict);
  init_symbol(&symbols[14u],
	      "m_m_wrongSpec_enq_conflict",
	      SYM_MODULE,
	      &INST_m_m_wrongSpec_enq_conflict);
  init_symbol(&symbols[15u], "RL_m_m_specBits_0_canon", SYM_RULE);
  init_symbol(&symbols[16u], "RL_m_m_valid_0_canon", SYM_RULE);
}


/* Rule actions */

void MOD_mkFpuMulDivDispToRegFifo::RL_m_m_valid_0_canon()
{
  tUInt8 DEF_IF_m_m_valid_0_lat_1_whas_THEN_m_m_valid_0_lat_ETC___d7;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_m_m_valid_0_lat_0_whas____d3 = INST_m_m_valid_0_lat_0.METH_whas();
  DEF_m_m_valid_0_lat_0_wget____d4 = INST_m_m_valid_0_lat_0.METH_wget();
  DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6 = DEF_m_m_valid_0_lat_0_whas____d3 ? DEF_m_m_valid_0_lat_0_wget____d4 : DEF_m_m_valid_0_rl__h2361;
  DEF_IF_m_m_valid_0_lat_1_whas_THEN_m_m_valid_0_lat_ETC___d7 = INST_m_m_valid_0_lat_1.METH_whas() ? INST_m_m_valid_0_lat_1.METH_wget() : DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6;
  INST_m_m_valid_0_rl.METH_write(DEF_IF_m_m_valid_0_lat_1_whas_THEN_m_m_valid_0_lat_ETC___d7);
}

void MOD_mkFpuMulDivDispToRegFifo::RL_m_m_specBits_0_canon()
{
  tUInt32 DEF_upd__h1138;
  tUInt32 DEF_x__h1024;
  tUInt32 DEF_x_wget__h945;
  DEF_x_wget__h945 = INST_m_m_specBits_0_lat_1.METH_wget();
  DEF_x_wget__h896 = INST_m_m_specBits_0_lat_0.METH_wget();
  DEF_upd__h1138 = DEF_x_wget__h945;
  DEF_upd__h1165 = DEF_x_wget__h896;
  DEF_upd__h9426 = INST_m_m_specBits_0_rl.METH_read();
  DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15 = INST_m_m_specBits_0_lat_0.METH_whas() ? DEF_upd__h1165 : DEF_upd__h9426;
  DEF_x__h1024 = INST_m_m_specBits_0_lat_1.METH_whas() ? DEF_upd__h1138 : DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15;
  INST_m_m_specBits_0_rl.METH_write(DEF_x__h1024);
}


/* Methods */

void MOD_mkFpuMulDivDispToRegFifo::METH_enq(tUWide ARG_enq_x)
{
  tUInt8 DEF_NOT_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_val_ETC___d20;
  tUInt32 DEF_x__h5676;
  PORT_enq_x = ARG_enq_x;
  DEF_x__h5676 = ARG_enq_x.get_bits_in_word32(0u, 0u, 12u);
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_m_m_valid_0_lat_0_whas____d3 = INST_m_m_valid_0_lat_0.METH_whas();
  DEF_m_m_valid_0_lat_0_wget____d4 = INST_m_m_valid_0_lat_0.METH_wget();
  DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 = DEF_m_m_valid_0_lat_0_whas____d3 ? !DEF_m_m_valid_0_lat_0_wget____d4 : !DEF_m_m_valid_0_rl__h2361;
  DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6 = DEF_m_m_valid_0_lat_0_whas____d3 ? DEF_m_m_valid_0_lat_0_wget____d4 : DEF_m_m_valid_0_rl__h2361;
  DEF_NOT_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_val_ETC___d20 = !DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19;
  wop_primExtractWide(79u, 91u, ARG_enq_x, 32u, 90u, 32u, 12u, DEF_enq_x_BITS_90_TO_12___d21);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    if (DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6)
      dollar_fdisplay(sim_hdl, this, "32,s", 2147483650u, &__str_literal_1);
    if (DEF_NOT_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_val_ETC___d20)
      dollar_display(sim_hdl, this, "s", &__str_literal_2);
    if (DEF_NOT_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_val_ETC___d20)
      dollar_finish(sim_hdl, "32", 0u);
  }
  INST_m_m_valid_0_lat_1.METH_wset((tUInt8)1u);
  INST_m_m_specBits_0_lat_0.METH_wset(DEF_x__h5676);
  INST_m_m_row_0.METH_write(DEF_enq_x_BITS_90_TO_12___d21);
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_enq()
{
  tUInt8 DEF_CAN_FIRE_enq;
  tUInt8 PORT_RDY_enq;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_m_m_valid_0_lat_0_whas____d3 = INST_m_m_valid_0_lat_0.METH_whas();
  DEF_m_m_valid_0_lat_0_wget____d4 = INST_m_m_valid_0_lat_0.METH_wget();
  DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 = DEF_m_m_valid_0_lat_0_whas____d3 ? !DEF_m_m_valid_0_lat_0_wget____d4 : !DEF_m_m_valid_0_rl__h2361;
  DEF_CAN_FIRE_enq = DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 && !INST_m_m_wrongSpec_enq_conflict.METH_whas();
  PORT_RDY_enq = DEF_CAN_FIRE_enq;
  return PORT_RDY_enq;
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_notFull()
{
  tUInt8 PORT_notFull;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_m_m_valid_0_lat_0_whas____d3 = INST_m_m_valid_0_lat_0.METH_whas();
  DEF_m_m_valid_0_lat_0_wget____d4 = INST_m_m_valid_0_lat_0.METH_wget();
  DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 = DEF_m_m_valid_0_lat_0_whas____d3 ? !DEF_m_m_valid_0_lat_0_wget____d4 : !DEF_m_m_valid_0_rl__h2361;
  PORT_notFull = DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19;
  return PORT_notFull;
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_notFull()
{
  tUInt8 DEF_CAN_FIRE_notFull;
  tUInt8 PORT_RDY_notFull;
  DEF_CAN_FIRE_notFull = (tUInt8)1u;
  PORT_RDY_notFull = DEF_CAN_FIRE_notFull;
  return PORT_RDY_notFull;
}

void MOD_mkFpuMulDivDispToRegFifo::METH_deq()
{
  INST_m_m_valid_0_lat_0.METH_wset((tUInt8)0u);
  INST_m_m_deqP_ehr_lat_0.METH_wset();
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_deq()
{
  tUInt8 DEF_CAN_FIRE_deq;
  tUInt8 PORT_RDY_deq;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_CAN_FIRE_deq = DEF_m_m_valid_0_rl__h2361 && !INST_m_m_wrongSpec_deq_conflict.METH_whas();
  PORT_RDY_deq = DEF_CAN_FIRE_deq;
  return PORT_RDY_deq;
}

tUWide MOD_mkFpuMulDivDispToRegFifo::METH_first()
{
  DEF_m_m_row_0___d27 = INST_m_m_row_0.METH_read();
  DEF_upd__h9426 = INST_m_m_specBits_0_rl.METH_read();
  PORT_first.set_bits_in_word(primExtract32(27u, 79u, DEF_m_m_row_0___d27, 32u, 78u, 32u, 52u),
			      2u,
			      0u,
			      27u).set_whole_word(primExtract32(32u, 79u, DEF_m_m_row_0___d27, 32u, 51u, 32u, 20u),
						  1u).set_whole_word((DEF_m_m_row_0___d27.get_bits_in_word32(0u,
													     0u,
													     20u) << 12u) | DEF_upd__h9426,
								     0u);
  return PORT_first;
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_first()
{
  tUInt8 DEF_CAN_FIRE_first;
  tUInt8 PORT_RDY_first;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  DEF_CAN_FIRE_first = DEF_m_m_valid_0_rl__h2361;
  PORT_RDY_first = DEF_CAN_FIRE_first;
  return PORT_RDY_first;
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_notEmpty()
{
  tUInt8 PORT_notEmpty;
  DEF_m_m_valid_0_rl__h2361 = INST_m_m_valid_0_rl.METH_read();
  PORT_notEmpty = DEF_m_m_valid_0_rl__h2361;
  return PORT_notEmpty;
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_notEmpty()
{
  tUInt8 DEF_CAN_FIRE_notEmpty;
  tUInt8 PORT_RDY_notEmpty;
  DEF_CAN_FIRE_notEmpty = (tUInt8)1u;
  PORT_RDY_notEmpty = DEF_CAN_FIRE_notEmpty;
  return PORT_RDY_notEmpty;
}

void MOD_mkFpuMulDivDispToRegFifo::METH_specUpdate_incorrectSpeculation(tUInt8 ARG_specUpdate_incorrectSpeculation_kill_all,
									tUInt8 ARG_specUpdate_incorrectSpeculation_kill_tag)
{
  tUInt8 DEF_specUpdate_incorrectSpeculation_kill_all_OR_m__ETC___d29;
  DEF_upd__h9426 = INST_m_m_specBits_0_rl.METH_read();
  DEF_specUpdate_incorrectSpeculation_kill_all_OR_m__ETC___d29 = ARG_specUpdate_incorrectSpeculation_kill_all || primExtract8(1u,
															      12u,
															      (tUInt32)(DEF_upd__h9426),
															      4u,
															      (tUInt8)(ARG_specUpdate_incorrectSpeculation_kill_tag),
															      4u,
															      (tUInt8)(ARG_specUpdate_incorrectSpeculation_kill_tag));
  if (DEF_specUpdate_incorrectSpeculation_kill_all_OR_m__ETC___d29)
    INST_m_m_valid_0_lat_0.METH_wset((tUInt8)0u);
  INST_m_m_wrongSpec_enq_conflict.METH_wset();
  INST_m_m_wrongSpec_deq_conflict.METH_wset();
  INST_m_m_wrongSpec_canon_conflict.METH_wset();
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_specUpdate_incorrectSpeculation()
{
  tUInt8 DEF_CAN_FIRE_specUpdate_incorrectSpeculation;
  tUInt8 PORT_RDY_specUpdate_incorrectSpeculation;
  DEF_CAN_FIRE_specUpdate_incorrectSpeculation = (tUInt8)1u;
  PORT_RDY_specUpdate_incorrectSpeculation = DEF_CAN_FIRE_specUpdate_incorrectSpeculation;
  return PORT_RDY_specUpdate_incorrectSpeculation;
}

void MOD_mkFpuMulDivDispToRegFifo::METH_specUpdate_correctSpeculation(tUInt32 ARG_specUpdate_correctSpeculation_mask)
{
  tUInt32 DEF_x__h9395;
  DEF_x_wget__h896 = INST_m_m_specBits_0_lat_0.METH_wget();
  DEF_upd__h1165 = DEF_x_wget__h896;
  DEF_upd__h9426 = INST_m_m_specBits_0_rl.METH_read();
  DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15 = INST_m_m_specBits_0_lat_0.METH_whas() ? DEF_upd__h1165 : DEF_upd__h9426;
  DEF_x__h9395 = DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15 & ARG_specUpdate_correctSpeculation_mask;
  INST_m_m_specBits_0_lat_1.METH_wset(DEF_x__h9395);
}

tUInt8 MOD_mkFpuMulDivDispToRegFifo::METH_RDY_specUpdate_correctSpeculation()
{
  tUInt8 DEF_CAN_FIRE_specUpdate_correctSpeculation;
  tUInt8 PORT_RDY_specUpdate_correctSpeculation;
  DEF_CAN_FIRE_specUpdate_correctSpeculation = (tUInt8)1u;
  PORT_RDY_specUpdate_correctSpeculation = DEF_CAN_FIRE_specUpdate_correctSpeculation;
  return PORT_RDY_specUpdate_correctSpeculation;
}


/* Reset routines */

void MOD_mkFpuMulDivDispToRegFifo::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_m_m_valid_0_rl.reset_RST(ARG_rst_in);
  INST_m_m_specBits_0_rl.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkFpuMulDivDispToRegFifo::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkFpuMulDivDispToRegFifo::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_m_m_deqP_ehr_lat_0.dump_state(indent + 2u);
  INST_m_m_deqP_ehr_lat_1.dump_state(indent + 2u);
  INST_m_m_row_0.dump_state(indent + 2u);
  INST_m_m_specBits_0_lat_0.dump_state(indent + 2u);
  INST_m_m_specBits_0_lat_1.dump_state(indent + 2u);
  INST_m_m_specBits_0_rl.dump_state(indent + 2u);
  INST_m_m_valid_0_lat_0.dump_state(indent + 2u);
  INST_m_m_valid_0_lat_1.dump_state(indent + 2u);
  INST_m_m_valid_0_rl.dump_state(indent + 2u);
  INST_m_m_wrongSpec_canon_conflict.dump_state(indent + 2u);
  INST_m_m_wrongSpec_deq_conflict.dump_state(indent + 2u);
  INST_m_m_wrongSpec_enq_conflict.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkFpuMulDivDispToRegFifo::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 26u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "enq_x_BITS_90_TO_12___d21", 79u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_m_row_0___d27", 79u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_m_valid_0_lat_0_wget____d4", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_m_valid_0_lat_0_whas____d3", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "m_m_valid_0_rl__h2361", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h1165", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h9426", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h896", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "enq_x", 91u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "first", 91u);
  num = INST_m_m_deqP_ehr_lat_0.dump_VCD_defs(num);
  num = INST_m_m_deqP_ehr_lat_1.dump_VCD_defs(num);
  num = INST_m_m_row_0.dump_VCD_defs(num);
  num = INST_m_m_specBits_0_lat_0.dump_VCD_defs(num);
  num = INST_m_m_specBits_0_lat_1.dump_VCD_defs(num);
  num = INST_m_m_specBits_0_rl.dump_VCD_defs(num);
  num = INST_m_m_valid_0_lat_0.dump_VCD_defs(num);
  num = INST_m_m_valid_0_lat_1.dump_VCD_defs(num);
  num = INST_m_m_valid_0_rl.dump_VCD_defs(num);
  num = INST_m_m_wrongSpec_canon_conflict.dump_VCD_defs(num);
  num = INST_m_m_wrongSpec_deq_conflict.dump_VCD_defs(num);
  num = INST_m_m_wrongSpec_enq_conflict.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkFpuMulDivDispToRegFifo::dump_VCD(tVCDDumpType dt,
					    unsigned int levels,
					    MOD_mkFpuMulDivDispToRegFifo &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkFpuMulDivDispToRegFifo::vcd_defs(tVCDDumpType dt, MOD_mkFpuMulDivDispToRegFifo &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 79u);
    vcd_write_x(sim_hdl, num++, 79u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 91u);
    vcd_write_x(sim_hdl, num++, 91u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15) != DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15, 12u);
	backing.DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15 = DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15;
      }
      ++num;
      if ((backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19) != DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19, 1u);
	backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 = DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19;
      }
      ++num;
      if ((backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6) != DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6, 1u);
	backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6 = DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_enq_x_BITS_90_TO_12___d21) != DEF_enq_x_BITS_90_TO_12___d21)
      {
	vcd_write_val(sim_hdl, num, DEF_enq_x_BITS_90_TO_12___d21, 79u);
	backing.DEF_enq_x_BITS_90_TO_12___d21 = DEF_enq_x_BITS_90_TO_12___d21;
      }
      ++num;
      if ((backing.DEF_m_m_row_0___d27) != DEF_m_m_row_0___d27)
      {
	vcd_write_val(sim_hdl, num, DEF_m_m_row_0___d27, 79u);
	backing.DEF_m_m_row_0___d27 = DEF_m_m_row_0___d27;
      }
      ++num;
      if ((backing.DEF_m_m_valid_0_lat_0_wget____d4) != DEF_m_m_valid_0_lat_0_wget____d4)
      {
	vcd_write_val(sim_hdl, num, DEF_m_m_valid_0_lat_0_wget____d4, 1u);
	backing.DEF_m_m_valid_0_lat_0_wget____d4 = DEF_m_m_valid_0_lat_0_wget____d4;
      }
      ++num;
      if ((backing.DEF_m_m_valid_0_lat_0_whas____d3) != DEF_m_m_valid_0_lat_0_whas____d3)
      {
	vcd_write_val(sim_hdl, num, DEF_m_m_valid_0_lat_0_whas____d3, 1u);
	backing.DEF_m_m_valid_0_lat_0_whas____d3 = DEF_m_m_valid_0_lat_0_whas____d3;
      }
      ++num;
      if ((backing.DEF_m_m_valid_0_rl__h2361) != DEF_m_m_valid_0_rl__h2361)
      {
	vcd_write_val(sim_hdl, num, DEF_m_m_valid_0_rl__h2361, 1u);
	backing.DEF_m_m_valid_0_rl__h2361 = DEF_m_m_valid_0_rl__h2361;
      }
      ++num;
      if ((backing.DEF_upd__h1165) != DEF_upd__h1165)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h1165, 12u);
	backing.DEF_upd__h1165 = DEF_upd__h1165;
      }
      ++num;
      if ((backing.DEF_upd__h9426) != DEF_upd__h9426)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h9426, 12u);
	backing.DEF_upd__h9426 = DEF_upd__h9426;
      }
      ++num;
      if ((backing.DEF_x_wget__h896) != DEF_x_wget__h896)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h896, 12u);
	backing.DEF_x_wget__h896 = DEF_x_wget__h896;
      }
      ++num;
      if ((backing.PORT_enq_x) != PORT_enq_x)
      {
	vcd_write_val(sim_hdl, num, PORT_enq_x, 91u);
	backing.PORT_enq_x = PORT_enq_x;
      }
      ++num;
      if ((backing.PORT_first) != PORT_first)
      {
	vcd_write_val(sim_hdl, num, PORT_first, 91u);
	backing.PORT_first = PORT_first;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15, 12u);
      backing.DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15 = DEF_IF_m_m_specBits_0_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d15;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19, 1u);
      backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19 = DEF_IF_m_m_valid_0_lat_0_whas_THEN_NOT_m_m_valid_0_ETC___d19;
      vcd_write_val(sim_hdl, num++, DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6, 1u);
      backing.DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6 = DEF_IF_m_m_valid_0_lat_0_whas_THEN_m_m_valid_0_lat_ETC___d6;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_enq_x_BITS_90_TO_12___d21, 79u);
      backing.DEF_enq_x_BITS_90_TO_12___d21 = DEF_enq_x_BITS_90_TO_12___d21;
      vcd_write_val(sim_hdl, num++, DEF_m_m_row_0___d27, 79u);
      backing.DEF_m_m_row_0___d27 = DEF_m_m_row_0___d27;
      vcd_write_val(sim_hdl, num++, DEF_m_m_valid_0_lat_0_wget____d4, 1u);
      backing.DEF_m_m_valid_0_lat_0_wget____d4 = DEF_m_m_valid_0_lat_0_wget____d4;
      vcd_write_val(sim_hdl, num++, DEF_m_m_valid_0_lat_0_whas____d3, 1u);
      backing.DEF_m_m_valid_0_lat_0_whas____d3 = DEF_m_m_valid_0_lat_0_whas____d3;
      vcd_write_val(sim_hdl, num++, DEF_m_m_valid_0_rl__h2361, 1u);
      backing.DEF_m_m_valid_0_rl__h2361 = DEF_m_m_valid_0_rl__h2361;
      vcd_write_val(sim_hdl, num++, DEF_upd__h1165, 12u);
      backing.DEF_upd__h1165 = DEF_upd__h1165;
      vcd_write_val(sim_hdl, num++, DEF_upd__h9426, 12u);
      backing.DEF_upd__h9426 = DEF_upd__h9426;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h896, 12u);
      backing.DEF_x_wget__h896 = DEF_x_wget__h896;
      vcd_write_val(sim_hdl, num++, PORT_enq_x, 91u);
      backing.PORT_enq_x = PORT_enq_x;
      vcd_write_val(sim_hdl, num++, PORT_first, 91u);
      backing.PORT_first = PORT_first;
    }
}

void MOD_mkFpuMulDivDispToRegFifo::vcd_prims(tVCDDumpType dt, MOD_mkFpuMulDivDispToRegFifo &backing)
{
  INST_m_m_deqP_ehr_lat_0.dump_VCD(dt, backing.INST_m_m_deqP_ehr_lat_0);
  INST_m_m_deqP_ehr_lat_1.dump_VCD(dt, backing.INST_m_m_deqP_ehr_lat_1);
  INST_m_m_row_0.dump_VCD(dt, backing.INST_m_m_row_0);
  INST_m_m_specBits_0_lat_0.dump_VCD(dt, backing.INST_m_m_specBits_0_lat_0);
  INST_m_m_specBits_0_lat_1.dump_VCD(dt, backing.INST_m_m_specBits_0_lat_1);
  INST_m_m_specBits_0_rl.dump_VCD(dt, backing.INST_m_m_specBits_0_rl);
  INST_m_m_valid_0_lat_0.dump_VCD(dt, backing.INST_m_m_valid_0_lat_0);
  INST_m_m_valid_0_lat_1.dump_VCD(dt, backing.INST_m_m_valid_0_lat_1);
  INST_m_m_valid_0_rl.dump_VCD(dt, backing.INST_m_m_valid_0_rl);
  INST_m_m_wrongSpec_canon_conflict.dump_VCD(dt, backing.INST_m_m_wrongSpec_canon_conflict);
  INST_m_m_wrongSpec_deq_conflict.dump_VCD(dt, backing.INST_m_m_wrongSpec_deq_conflict);
  INST_m_m_wrongSpec_enq_conflict.dump_VCD(dt, backing.INST_m_m_wrongSpec_enq_conflict);
}
