/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 23:49:49 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkICoCache_h__
#define __mkICoCache_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkIBankWrapper.h"


/* Class declaration for the mkICoCache module */
class MOD_mkICoCache : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkIBankWrapper INST_cache;
  MOD_Wire<tUInt8> INST_perfReqQ_clearReq_lat_0;
  MOD_Wire<tUInt8> INST_perfReqQ_clearReq_lat_1;
  MOD_Reg<tUInt8> INST_perfReqQ_clearReq_rl;
  MOD_Reg<tUInt8> INST_perfReqQ_data_0;
  MOD_Wire<tUInt8> INST_perfReqQ_deqReq_lat_0;
  MOD_Wire<tUInt8> INST_perfReqQ_deqReq_lat_1;
  MOD_Wire<tUInt8> INST_perfReqQ_deqReq_lat_2;
  MOD_Reg<tUInt8> INST_perfReqQ_deqReq_rl;
  MOD_Reg<tUInt8> INST_perfReqQ_empty;
  MOD_Wire<tUInt8> INST_perfReqQ_enqReq_lat_0;
  MOD_Wire<tUInt8> INST_perfReqQ_enqReq_lat_1;
  MOD_Wire<tUInt8> INST_perfReqQ_enqReq_lat_2;
  MOD_Reg<tUInt8> INST_perfReqQ_enqReq_rl;
  MOD_Reg<tUInt8> INST_perfReqQ_full;
 
 /* Constructor */
 public:
  MOD_mkICoCache(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_to_parent_fromP_enq_x;
  tUWide PORT_cRqStuck_get;
  tUWide PORT_perf_resp;
  tUWide PORT_to_proc_response_get;
  tUWide PORT_to_parent_rsToP_first;
  tUWide PORT_to_parent_rqToP_first;
  tUWide PORT_pRqStuck_get;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_NOT_perfReqQ_empty_0___d67;
  tUInt8 DEF_perfReqQ_full__h3387;
  tUInt8 DEF_perfReqQ_empty__h3423;
 
 /* Local definitions */
 private:
  tUInt8 DEF_IF_perfReqQ_clearReq_lat_0_whas__3_THEN_perfRe_ETC___d26;
  tUWide DEF_cache_to_parent_rsToP_first____d68;
  tUInt8 DEF_perfReqQ_enqReq_rl___d7;
  tUInt8 DEF_perfReqQ_enqReq_lat_1_wget____d4;
  tUInt8 DEF_perfReqQ_enqReq_lat_0_wget____d6;
  tUInt8 DEF_perfReqQ_clearReq_rl__h2421;
  tUInt8 DEF_perfReqQ_clearReq_lat_0_whas____d23;
  tUInt8 DEF_perfReqQ_clearReq_lat_0_wget____d24;
  tUInt8 DEF_perfReqQ_deqReq_rl__h1843;
  tUInt8 DEF_perfReqQ_deqReq_lat_1_whas____d13;
  tUInt8 DEF_perfReqQ_deqReq_lat_1_wget____d14;
  tUInt8 DEF_perfReqQ_deqReq_lat_0_whas____d15;
  tUInt8 DEF_perfReqQ_deqReq_lat_0_wget____d16;
  tUInt8 DEF_perfReqQ_enqReq_lat_1_whas____d3;
  tUInt8 DEF_perfReqQ_enqReq_lat_0_whas____d5;
  tUInt8 DEF_IF_perfReqQ_deqReq_lat_1_whas__3_THEN_perfReqQ_ETC___d19;
 
 /* Rules */
 public:
  void RL_perfReqQ_enqReq_canon();
  void RL_perfReqQ_deqReq_canon();
  void RL_perfReqQ_clearReq_canon();
  void RL_perfReqQ_canonicalize();
 
 /* Methods */
 public:
  tUInt8 METH_flush_done();
  tUInt8 METH_RDY_flush_done();
  void METH_to_proc_request_put(tUInt64 ARG_to_proc_request_put);
  tUInt8 METH_RDY_to_proc_request_put();
  tUWide METH_to_proc_response_get();
  tUInt8 METH_RDY_to_proc_response_get();
  void METH_flush();
  tUInt8 METH_RDY_flush();
  void METH_perf_setStatus(tUInt8 ARG_perf_setStatus_doStats);
  tUInt8 METH_RDY_perf_setStatus();
  void METH_perf_req(tUInt8 ARG_perf_req_r);
  tUInt8 METH_RDY_perf_req();
  tUWide METH_perf_resp();
  tUInt8 METH_RDY_perf_resp();
  tUInt8 METH_perf_respValid();
  tUInt8 METH_RDY_perf_respValid();
  tUInt64 METH_events();
  tUInt8 METH_RDY_events();
  tUInt8 METH_to_parent_rsToP_notEmpty();
  tUInt8 METH_RDY_to_parent_rsToP_notEmpty();
  void METH_to_parent_rsToP_deq();
  tUInt8 METH_RDY_to_parent_rsToP_deq();
  tUWide METH_to_parent_rsToP_first();
  tUInt8 METH_RDY_to_parent_rsToP_first();
  tUInt8 METH_to_parent_rqToP_notEmpty();
  tUInt8 METH_RDY_to_parent_rqToP_notEmpty();
  void METH_to_parent_rqToP_deq();
  tUInt8 METH_RDY_to_parent_rqToP_deq();
  tUWide METH_to_parent_rqToP_first();
  tUInt8 METH_RDY_to_parent_rqToP_first();
  tUInt8 METH_to_parent_fromP_notFull();
  tUInt8 METH_RDY_to_parent_fromP_notFull();
  void METH_to_parent_fromP_enq(tUWide ARG_to_parent_fromP_enq_x);
  tUInt8 METH_RDY_to_parent_fromP_enq();
  tUWide METH_cRqStuck_get();
  tUInt8 METH_RDY_cRqStuck_get();
  tUWide METH_pRqStuck_get();
  tUInt8 METH_RDY_pRqStuck_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkICoCache &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkICoCache &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkICoCache &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkICoCache &backing);
};

#endif /* ifndef __mkICoCache_h__ */
