/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 23:49:49 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkIPRqMshrWrapper_h__
#define __mkIPRqMshrWrapper_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkIPRqMshrWrapper module */
class MOD_mkIPRqMshrWrapper : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUInt8> INST_m_m_emptyEntryQ;
  MOD_Reg<tUInt8> INST_m_m_initIdx;
  MOD_Reg<tUInt8> INST_m_m_inited;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_data_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_data_0_lat_1;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_data_0_rl;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_empty_rl;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_full_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_full_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_full_lat_2;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_pipelineResp_full_rl;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_data_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_data_0_lat_1;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_data_0_rl;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_empty_rl;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_full_lat_0;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_full_lat_1;
  MOD_Wire<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_full_lat_2;
  MOD_Reg<tUInt8> INST_m_m_releaseEntryQ_sendRsToP_pRq_full_rl;
  MOD_Wire<tUWide> INST_m_m_reqVec_0_lat_0;
  MOD_Wire<tUWide> INST_m_m_reqVec_0_lat_1;
  MOD_Wire<tUWide> INST_m_m_reqVec_0_lat_2;
  MOD_Reg<tUWide> INST_m_m_reqVec_0_rl;
  MOD_Wire<tUWide> INST_m_m_reqVec_1_lat_0;
  MOD_Wire<tUWide> INST_m_m_reqVec_1_lat_1;
  MOD_Wire<tUWide> INST_m_m_reqVec_1_lat_2;
  MOD_Reg<tUWide> INST_m_m_reqVec_1_rl;
  MOD_Wire<tUWide> INST_m_m_reqVec_2_lat_0;
  MOD_Wire<tUWide> INST_m_m_reqVec_2_lat_1;
  MOD_Wire<tUWide> INST_m_m_reqVec_2_lat_2;
  MOD_Reg<tUWide> INST_m_m_reqVec_2_rl;
  MOD_Wire<tUWide> INST_m_m_reqVec_3_lat_0;
  MOD_Wire<tUWide> INST_m_m_reqVec_3_lat_1;
  MOD_Wire<tUWide> INST_m_m_reqVec_3_lat_2;
  MOD_Reg<tUWide> INST_m_m_reqVec_3_rl;
  MOD_Wire<tUInt8> INST_m_m_stateVec_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_stateVec_0_lat_1;
  MOD_Wire<tUInt8> INST_m_m_stateVec_0_lat_2;
  MOD_Reg<tUInt8> INST_m_m_stateVec_0_rl;
  MOD_Wire<tUInt8> INST_m_m_stateVec_1_lat_0;
  MOD_Wire<tUInt8> INST_m_m_stateVec_1_lat_1;
  MOD_Wire<tUInt8> INST_m_m_stateVec_1_lat_2;
  MOD_Reg<tUInt8> INST_m_m_stateVec_1_rl;
  MOD_Wire<tUInt8> INST_m_m_stateVec_2_lat_0;
  MOD_Wire<tUInt8> INST_m_m_stateVec_2_lat_1;
  MOD_Wire<tUInt8> INST_m_m_stateVec_2_lat_2;
  MOD_Reg<tUInt8> INST_m_m_stateVec_2_rl;
  MOD_Wire<tUInt8> INST_m_m_stateVec_3_lat_0;
  MOD_Wire<tUInt8> INST_m_m_stateVec_3_lat_1;
  MOD_Wire<tUInt8> INST_m_m_stateVec_3_lat_2;
  MOD_Reg<tUInt8> INST_m_m_stateVec_3_rl;
 
 /* Constructor */
 public:
  MOD_mkIPRqMshrWrapper(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_getEmptyEntryInit_r;
  tUWide PORT_pipelineResp_getRq;
  tUWide PORT_stuck_get;
  tUWide PORT_sendRsToP_pRq_getRq;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_m_m_inited___d140;
  tUInt8 DEF_m_m_releaseEntryQ_pipelineResp_full_rl__h9258;
  tUInt8 DEF_m_m_releaseEntryQ_pipelineResp_empty_rl__h10710;
  tUInt8 DEF_m_m_releaseEntryQ_pipelineResp_empty_lat_0_whas____d123;
  tUInt8 DEF_m_m_releaseEntryQ_pipelineResp_empty_lat_0_wget____d124;
  tUInt8 DEF_m_m_releaseEntryQ_sendRsToP_pRq_full_rl__h7021;
  tUInt8 DEF_m_m_releaseEntryQ_sendRsToP_pRq_empty_rl__h9990;
  tUInt8 DEF_m_m_releaseEntryQ_sendRsToP_pRq_empty_lat_0_whas____d94;
  tUInt8 DEF_m_m_releaseEntryQ_sendRsToP_pRq_empty_lat_0_wget____d95;
 
 /* Local definitions */
 private:
  tUWide DEF_m_m_reqVec_3_rl___d77;
  tUWide DEF_m_m_reqVec_3_lat_2_wget____d72;
  tUWide DEF_m_m_reqVec_3_lat_1_wget____d74;
  tUWide DEF_m_m_reqVec_3_lat_0_wget____d76;
  tUWide DEF_m_m_reqVec_2_rl___d67;
  tUWide DEF_m_m_reqVec_2_lat_2_wget____d62;
  tUWide DEF_m_m_reqVec_2_lat_1_wget____d64;
  tUWide DEF_m_m_reqVec_2_lat_0_wget____d66;
  tUWide DEF_m_m_reqVec_1_rl___d57;
  tUWide DEF_m_m_reqVec_1_lat_2_wget____d52;
  tUWide DEF_m_m_reqVec_1_lat_1_wget____d54;
  tUWide DEF_m_m_reqVec_1_lat_0_wget____d56;
  tUWide DEF_m_m_reqVec_0_rl___d47;
  tUWide DEF_m_m_reqVec_0_lat_2_wget____d42;
  tUWide DEF_m_m_reqVec_0_lat_1_wget____d44;
  tUWide DEF_m_m_reqVec_0_lat_0_wget____d46;
  tUInt8 DEF_upd__h10819;
  tUInt8 DEF_x_wget__h7283;
  tUInt8 DEF_upd__h10099;
  tUInt8 DEF_x_wget__h5046;
  tUInt8 DEF_m_m_reqVec_3_lat_0_whas____d75;
  tUInt8 DEF_m_m_reqVec_2_lat_0_whas____d65;
  tUInt8 DEF_m_m_reqVec_1_lat_0_whas____d55;
  tUInt8 DEF_m_m_reqVec_0_lat_0_whas____d45;
  tUInt64 DEF__read_addr__h4574;
  tUInt64 DEF__read_addr__h4047;
  tUInt64 DEF__read_addr__h2993;
  tUInt64 DEF__read_addr__h3520;
  tUInt8 DEF_m_m_reqVec_3_rl_7_BITS_2_TO_0___d186;
  tUInt8 DEF_m_m_reqVec_2_rl_7_BITS_2_TO_0___d183;
  tUInt8 DEF_m_m_reqVec_0_rl_7_BITS_2_TO_0___d177;
  tUInt8 DEF_m_m_reqVec_1_rl_7_BITS_2_TO_0___d180;
  tUWide DEF_IF_m_m_reqVec_3_lat_2_whas__1_THEN_m_m_reqVec__ETC___d80;
  tUWide DEF_IF_m_m_reqVec_3_lat_1_whas__3_THEN_m_m_reqVec__ETC___d79;
  tUWide DEF_IF_m_m_reqVec_3_lat_0_whas__5_THEN_m_m_reqVec__ETC___d78;
  tUWide DEF_IF_m_m_reqVec_2_lat_2_whas__1_THEN_m_m_reqVec__ETC___d70;
  tUWide DEF_IF_m_m_reqVec_2_lat_1_whas__3_THEN_m_m_reqVec__ETC___d69;
  tUWide DEF_IF_m_m_reqVec_2_lat_0_whas__5_THEN_m_m_reqVec__ETC___d68;
  tUWide DEF_IF_m_m_reqVec_1_lat_2_whas__1_THEN_m_m_reqVec__ETC___d60;
  tUWide DEF_IF_m_m_reqVec_1_lat_1_whas__3_THEN_m_m_reqVec__ETC___d59;
  tUWide DEF_IF_m_m_reqVec_1_lat_0_whas__5_THEN_m_m_reqVec__ETC___d58;
  tUWide DEF_IF_m_m_reqVec_0_lat_2_whas__1_THEN_m_m_reqVec__ETC___d50;
  tUWide DEF_IF_m_m_reqVec_0_lat_1_whas__3_THEN_m_m_reqVec__ETC___d49;
  tUWide DEF_IF_m_m_reqVec_0_lat_0_whas__5_THEN_m_m_reqVec__ETC___d48;
  tUInt8 DEF_IF_m_m_releaseEntryQ_pipelineResp_data_0_lat_0_ETC___d117;
  tUInt8 DEF_upd__h7550;
  tUInt8 DEF_IF_m_m_releaseEntryQ_sendRsToP_pRq_data_0_lat__ETC___d88;
  tUInt8 DEF_upd__h5313;
 
 /* Rules */
 public:
  void RL_m_m_stateVec_0_canon();
  void RL_m_m_stateVec_1_canon();
  void RL_m_m_stateVec_2_canon();
  void RL_m_m_stateVec_3_canon();
  void RL_m_m_reqVec_0_canon();
  void RL_m_m_reqVec_1_canon();
  void RL_m_m_reqVec_2_canon();
  void RL_m_m_reqVec_3_canon();
  void RL_m_m_releaseEntryQ_sendRsToP_pRq_data_0_canon();
  void RL_m_m_releaseEntryQ_sendRsToP_pRq_empty_canon();
  void RL_m_m_releaseEntryQ_sendRsToP_pRq_full_canon();
  void RL_m_m_releaseEntryQ_pipelineResp_data_0_canon();
  void RL_m_m_releaseEntryQ_pipelineResp_empty_canon();
  void RL_m_m_releaseEntryQ_pipelineResp_full_canon();
  void RL_m_m_initEmptyEntry();
  void RL_m_m_doReleaseEntry_sendRsToP_pRq();
  void RL_m_m_doReleaseEntry_pipelineResp();
 
 /* Methods */
 public:
  tUInt8 METH_getEmptyEntryInit(tUWide ARG_getEmptyEntryInit_r);
  tUInt8 METH_RDY_getEmptyEntryInit();
  tUWide METH_sendRsToP_pRq_getRq(tUInt8 ARG_sendRsToP_pRq_getRq_n);
  tUInt8 METH_RDY_sendRsToP_pRq_getRq();
  void METH_sendRsToP_pRq_releaseEntry(tUInt8 ARG_sendRsToP_pRq_releaseEntry_n);
  tUInt8 METH_RDY_sendRsToP_pRq_releaseEntry();
  tUWide METH_pipelineResp_getRq(tUInt8 ARG_pipelineResp_getRq_n);
  tUInt8 METH_RDY_pipelineResp_getRq();
  void METH_pipelineResp_releaseEntry(tUInt8 ARG_pipelineResp_releaseEntry_n);
  tUInt8 METH_RDY_pipelineResp_releaseEntry();
  void METH_pipelineResp_setDone(tUInt8 ARG_pipelineResp_setDone_n);
  tUInt8 METH_RDY_pipelineResp_setDone();
  tUWide METH_stuck_get();
  tUInt8 METH_RDY_stuck_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkIPRqMshrWrapper &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkIPRqMshrWrapper &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkIPRqMshrWrapper &backing);
};

#endif /* ifndef __mkIPRqMshrWrapper_h__ */
