/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkMem_Controller_h__
#define __mkMem_Controller_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMem_Controller module */
class MOD_mkMem_Controller : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt8> INST_cfg_verbosity;
  MOD_CReg<tUWide> INST_f_raw_mem_reqs_rv;
  MOD_CReg<tUWide> INST_f_raw_mem_rsps_rv;
  MOD_CReg<tUWide> INST_f_reqs_rv;
  MOD_Fifo<tUInt8> INST_f_reset_reqs;
  MOD_Fifo<tUInt8> INST_f_reset_rsps;
  MOD_Reg<tUInt64> INST_rg_addr_base;
  MOD_Reg<tUInt64> INST_rg_addr_lim;
  MOD_Reg<tUInt8> INST_rg_cached_clean;
  MOD_Reg<tUInt64> INST_rg_cached_raw_mem_addr;
  MOD_Reg<tUWide> INST_rg_cached_raw_mem_word;
  MOD_Reg<tUInt8> INST_rg_state;
  MOD_Reg<tUInt8> INST_rg_status;
  MOD_Reg<tUInt64> INST_rg_tohost_addr;
  MOD_Reg<tUInt8> INST_rg_watch_tohost;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_arff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_awff;
  MOD_Fifo<tUInt32> INST_slavePortShim_shim_bff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_rff;
  MOD_Fifo<tUWide> INST_slavePortShim_shim_wff;
 
 /* Constructor */
 public:
  MOD_mkMem_Controller(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_set_addr_map;
  tUWide PORT_to_raw_mem_response_put;
  tUWide PORT_slave_aw_put_val;
  tUWide PORT_slave_w_put_val;
  tUWide PORT_slave_ar_put_val;
  tUWide PORT_to_raw_mem_request_get;
  tUWide PORT_slave_r_peek;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_set_addr_map;
  tUInt8 DEF_slavePortShim_shim_rff_i_notEmpty____d349;
  tUInt8 DEF_slavePortShim_shim_bff_i_notEmpty____d348;
  tUWide DEF_f_raw_mem_reqs_rv_port0__read____d350;
  tUInt8 DEF_rg_state__h1627;
  tUWide DEF_f_raw_mem_reqs_rv_port1__read____d17;
  tUWide DEF_f_raw_mem_rsps_rv_port1__read____d352;
  tUWide DEF_f_raw_mem_rsps_rv_port0__read____d183;
  tUWide DEF_f_reqs_rv_port1__read____d27;
  tUWide DEF_f_reqs_rv_port0__read____d108;
  tUInt64 DEF_x__h5951;
  tUInt64 DEF_addr_lim__h8972;
  tUInt64 DEF_addr_base__h8970;
  tUInt64 DEF_addr__h3477;
  tUInt8 DEF_x__h3789;
  tUInt8 DEF_x__h3750;
  tUInt8 DEF_x__h3711;
  tUInt8 DEF_x__h3672;
  tUInt8 DEF_x__h3633;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90___d122;
  tUInt8 DEF_x__h3594;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BIT_101___d125;
  tUInt64 DEF_req_raw_mem_addr__h3265;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_107_TO_101_55_E_ETC___d156;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_106_TO_101_50_E_ETC___d151;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_105_TO_101_45_E_ETC___d146;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_104_TO_101_40_E_ETC___d141;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_103_TO_101_35_E_ETC___d136;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d154;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d149;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d144;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d139;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d134;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d129;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ_0b1___d124;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ_0b0___d123;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_102_TO_101_30_E_ETC___d131;
  tUInt8 DEF_NOT_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_ETC___d329;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_92_TO_90_22_EQ__ETC___d158;
 
 /* Local definitions */
 private:
  tUWide DEF__0_CONCAT_DONTCARE___d8;
  tUWide DEF__0_CONCAT_DONTCARE___d9;
  tUWide DEF__0_CONCAT_DONTCARE___d207;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_105_TO_104___d203;
  tUInt32 DEF_v__h10008;
  tUInt32 DEF_v__h9339;
  tUInt32 DEF_v__h8487;
  tUInt32 DEF_v__h7963;
  tUInt32 DEF_v__h7729;
  tUInt32 DEF_v__h5454;
  tUInt32 DEF_v__h4741;
  tUInt32 DEF_v__h4452;
  tUInt32 DEF_v__h3957;
  tUInt32 DEF_v__h3440;
  tUInt32 DEF_v__h3109;
  tUInt32 DEF_v__h2741;
  tUInt32 DEF_v__h2421;
  tUInt32 DEF_v__h1988;
  tUInt32 DEF_v__h1680;
  tUWide DEF_rg_cached_raw_mem_word__h6453;
  tUWide DEF_slavePortShim_shim_arff_first____d32;
  tUWide DEF_slavePortShim_shim_awff_first____d71;
  tUWide DEF_slavePortShim_shim_wff_first____d72;
  tUInt8 DEF_x__h7692;
  tUWide DEF_raw_mem_word__h4617;
  tUWide DEF_f_reqs_rv_port0__read__08_BITS_172_TO_101___d337;
  tUInt64 DEF_rg_cached_raw_mem_word_17_BITS_255_TO_192___d201;
  tUInt64 DEF_rg_cached_raw_mem_word_17_BITS_191_TO_128___d200;
  tUInt64 DEF_rg_cached_raw_mem_word_17_BITS_127_TO_64___d199;
  tUInt64 DEF_rg_cached_raw_mem_word_17_BITS_63_TO_0___d198;
  tUInt64 DEF_value__h5617;
  tUInt8 DEF_rdr_rid__h5153;
  tUInt8 DEF_value__h5550;
  tUInt8 DEF_value__h5613;
  tUInt8 DEF_value__h5593;
  tUInt8 DEF_value__h5601;
  tUInt8 DEF_value__h5605;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_82_TO_80___d229;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_89_TO_88___d211;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BIT_87___d224;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_89_TO_88_11_EQ_2___d216;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_89_TO_88_11_EQ_1___d214;
  tUInt8 DEF_f_reqs_rv_port0__read__08_BITS_89_TO_88_11_EQ_0___d212;
  tUInt8 DEF_NOT_f_reqs_rv_port0__read__08_BITS_89_TO_88_11_ETC___d222;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_NOT_f_reqs_rv_ETC___d227;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1___d5;
  tUInt8 DEF_NOT_f_reqs_rv_port0__read__08_BIT_87_24___d226;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_f_reqs_rv_por_ETC___d225;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_NOT_f_reqs_rv_ETC___d223;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_f_reqs_rv_por_ETC___d217;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_f_reqs_rv_por_ETC___d213;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_1_AND_f_reqs_rv_por_ETC___d215;
  tUInt8 DEF_NOT_cfg_verbosity_read_ULE_2_4___d35;
  tUWide DEF__237684487524346268706922299392_CONCAT_DONTCARE___d22;
  tUWide DEF__17179869183_CONCAT_rg_cached_raw_mem_addr_16_C_ETC___d118;
  tUWide DEF__12884901887_CONCAT_0_CONCAT_f_reqs_rv_port0__r_ETC___d180;
  tUWide DEF__1_CONCAT_to_raw_mem_response_put___d351;
  tUWide DEF_x__h5982;
  tUWide DEF_IF_f_reqs_rv_port0__read__08_BITS_105_TO_104_0_ETC___d278;
  tUWide DEF__3_CONCAT_slavePortShim_shim_awff_first__1_CONC_ETC___d76;
  tUWide DEF_slavePortShim_shim_wff_first__2_BITS_8_TO_1_3__ETC___d75;
  tUWide DEF__2_CONCAT_slavePortShim_shim_arff_first__2_CONC_ETC___d33;
  tUWide DEF_f_reqs_rv_port0__read__08_BITS_172_TO_101_37_C_ETC___d338;
  tUWide DEF_f_reqs_rv_port0__read__08_BITS_172_TO_165_97_C_ETC___d206;
 
 /* Rules */
 public:
  void RL_rl_power_on_reset();
  void RL_rl_external_reset();
  void RL_rl_reset_reload_cache();
  void RL_rl_merge_rd_req();
  void RL_rl_merge_wr_req();
  void RL_rl_writeback_dirty_idle();
  void RL_rl_writeback_dirty();
  void RL_rl_miss_clean_req();
  void RL_rl_reload();
  void RL_rl_process_rd_req();
  void RL_rl_process_wr_req();
  void RL_rl_invalid_rd_address();
  void RL_rl_invalid_wr_address();
 
 /* Methods */
 public:
  void METH_server_reset_request_put(tUInt8 ARG_server_reset_request_put);
  tUInt8 METH_RDY_server_reset_request_put();
  void METH_server_reset_response_get();
  tUInt8 METH_RDY_server_reset_response_get();
  void METH_set_addr_map(tUInt64 ARG_set_addr_map_addr_base, tUInt64 ARG_set_addr_map_addr_lim);
  tUInt8 METH_RDY_set_addr_map();
  tUInt8 METH_slave_aw_canPut();
  tUInt8 METH_RDY_slave_aw_canPut();
  void METH_slave_aw_put(tUWide ARG_slave_aw_put_val);
  tUInt8 METH_RDY_slave_aw_put();
  tUInt8 METH_slave_w_canPut();
  tUInt8 METH_RDY_slave_w_canPut();
  void METH_slave_w_put(tUWide ARG_slave_w_put_val);
  tUInt8 METH_RDY_slave_w_put();
  tUInt8 METH_slave_b_canPeek();
  tUInt8 METH_RDY_slave_b_canPeek();
  tUInt32 METH_slave_b_peek();
  tUInt8 METH_RDY_slave_b_peek();
  void METH_slave_b_drop();
  tUInt8 METH_RDY_slave_b_drop();
  tUInt8 METH_slave_ar_canPut();
  tUInt8 METH_RDY_slave_ar_canPut();
  void METH_slave_ar_put(tUWide ARG_slave_ar_put_val);
  tUInt8 METH_RDY_slave_ar_put();
  tUInt8 METH_slave_r_canPeek();
  tUInt8 METH_RDY_slave_r_canPeek();
  tUWide METH_slave_r_peek();
  tUInt8 METH_RDY_slave_r_peek();
  void METH_slave_r_drop();
  tUInt8 METH_RDY_slave_r_drop();
  tUWide METH_to_raw_mem_request_get();
  tUInt8 METH_RDY_to_raw_mem_request_get();
  void METH_to_raw_mem_response_put(tUWide ARG_to_raw_mem_response_put);
  tUInt8 METH_RDY_to_raw_mem_response_put();
  tUInt8 METH_status();
  tUInt8 METH_RDY_status();
  void METH_set_watch_tohost(tUInt8 ARG_set_watch_tohost_watch_tohost,
			     tUInt64 ARG_set_watch_tohost_tohost_addr);
  tUInt8 METH_RDY_set_watch_tohost();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMem_Controller &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMem_Controller &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMem_Controller &backing);
};

#endif /* ifndef __mkMem_Controller_h__ */
