/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkMem_Model_h__
#define __mkMem_Model_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMem_Model module */
class MOD_mkMem_Model : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Fifo<tUWide> INST_f_raw_mem_rsps;
  MOD_Reg<tUInt8> INST_reset_done;
  MOD_RegFile<tUInt64,tUWide> INST_rf;
 
 /* Constructor */
 public:
  MOD_mkMem_Model(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_mem_server_request_put;
  tUWide PORT_mem_server_response_get;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_x__h368;
  tUInt32 DEF_v__h395;
  tUWide DEF_x__h441;
  tUWide DEF_mem_server_response_get__avValue1;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_mem_server_request_put(tUWide ARG_mem_server_request_put);
  tUInt8 METH_RDY_mem_server_request_put();
  tUWide METH_mem_server_response_get();
  tUInt8 METH_RDY_mem_server_response_get();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMem_Model &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMem_Model &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMem_Model &backing);
};

#endif /* ifndef __mkMem_Model_h__ */
