/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkMinimumExecQ_h__
#define __mkMinimumExecQ_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMinimumExecQ module */
class MOD_mkMinimumExecQ : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_m_deqP;
  MOD_Reg<tUInt8> INST_m_m_enqP;
  MOD_Wire<tUInt8> INST_m_m_poisoned_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_poisoned_0_lat_1;
  MOD_Reg<tUInt8> INST_m_m_poisoned_0_rl;
  MOD_Wire<tUInt8> INST_m_m_poisoned_1_lat_0;
  MOD_Wire<tUInt8> INST_m_m_poisoned_1_lat_1;
  MOD_Reg<tUInt8> INST_m_m_poisoned_1_rl;
  MOD_Reg<tUInt32> INST_m_m_row_0;
  MOD_Reg<tUInt32> INST_m_m_row_1;
  MOD_Wire<tUInt32> INST_m_m_specBits_0_lat_0;
  MOD_Wire<tUInt32> INST_m_m_specBits_0_lat_1;
  MOD_Reg<tUInt32> INST_m_m_specBits_0_rl;
  MOD_Wire<tUInt32> INST_m_m_specBits_1_lat_0;
  MOD_Wire<tUInt32> INST_m_m_specBits_1_lat_1;
  MOD_Reg<tUInt32> INST_m_m_specBits_1_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_valid_0_lat_1;
  MOD_Reg<tUInt8> INST_m_m_valid_0_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_1_lat_0;
  MOD_Wire<tUInt8> INST_m_m_valid_1_lat_1;
  MOD_Reg<tUInt8> INST_m_m_valid_1_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_for_enq_wire;
  MOD_Wire<tUInt8> INST_m_m_wrongSpec_enq_conflict;
 
 /* Constructor */
 public:
  MOD_mkMinimumExecQ(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_SEL_ARR_m_m_valid_0_rl_m_m_valid_1_rl_2_7_m_m__ETC___d64;
  tUInt8 DEF_x__h4690;
  tUInt8 DEF_m_m_valid_1_rl__h898;
  tUInt8 DEF_m_m_valid_0_rl__h555;
 
 /* Local definitions */
 private:
  tUInt32 DEF_upd__h5240;
  tUInt32 DEF_x_wget__h2597;
  tUInt32 DEF_upd__h5123;
  tUInt32 DEF_x_wget__h2249;
  tUInt8 DEF_m_m_enqP__h4174;
  tUInt8 DEF_m_m_poisoned_1_rl__h1815;
  tUInt8 DEF_m_m_poisoned_0_rl__h1467;
  tUInt32 DEF_IF_m_m_specBits_1_lat_0_whas__1_THEN_IF_m_m_sp_ETC___d45;
  tUInt32 DEF_upd__h2856;
  tUInt32 DEF_IF_m_m_specBits_0_lat_0_whas__2_THEN_IF_m_m_sp_ETC___d36;
  tUInt32 DEF_upd__h2518;
 
 /* Rules */
 public:
  void RL_m_m_valid_0_canon();
  void RL_m_m_valid_1_canon();
  void RL_m_m_poisoned_0_canon();
  void RL_m_m_poisoned_1_canon();
  void RL_m_m_specBits_0_canon();
  void RL_m_m_specBits_1_canon();
  void RL_m_m_setEnqWire();
 
 /* Methods */
 public:
  void METH_enq(tUInt64 ARG_enq_x);
  tUInt8 METH_RDY_enq();
  void METH_deq();
  tUInt8 METH_RDY_deq();
  tUInt64 METH_first_data();
  tUInt8 METH_RDY_first_data();
  tUInt8 METH_first_poisoned();
  tUInt8 METH_RDY_first_poisoned();
  void METH_specUpdate_incorrectSpeculation(tUInt8 ARG_specUpdate_incorrectSpeculation_kill_all,
					    tUInt8 ARG_specUpdate_incorrectSpeculation_kill_tag);
  tUInt8 METH_RDY_specUpdate_incorrectSpeculation();
  void METH_specUpdate_correctSpeculation(tUInt32 ARG_specUpdate_correctSpeculation_mask);
  tUInt8 METH_RDY_specUpdate_correctSpeculation();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMinimumExecQ &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMinimumExecQ &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMinimumExecQ &backing);
};

#endif /* ifndef __mkMinimumExecQ_h__ */
