/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 23:12:49 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkMMIOInst_h__
#define __mkMMIOInst_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkSoC_Map.h"


/* Class declaration for the mkMMIOInst module */
class MOD_mkMMIOInst : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt64> INST_fromHostAddr;
  MOD_Wire<tUInt8> INST_pendQ_clearReq_lat_0;
  MOD_Wire<tUInt8> INST_pendQ_clearReq_lat_1;
  MOD_Reg<tUInt8> INST_pendQ_clearReq_rl;
  MOD_Wire<tUInt8> INST_pendQ_deqReq_lat_0;
  MOD_Wire<tUInt8> INST_pendQ_deqReq_lat_1;
  MOD_Wire<tUInt8> INST_pendQ_deqReq_lat_2;
  MOD_Reg<tUInt8> INST_pendQ_deqReq_rl;
  MOD_Reg<tUInt8> INST_pendQ_empty;
  MOD_Wire<tUInt8> INST_pendQ_enqReq_lat_0;
  MOD_Wire<tUInt8> INST_pendQ_enqReq_lat_1;
  MOD_Wire<tUInt8> INST_pendQ_enqReq_lat_2;
  MOD_Reg<tUInt8> INST_pendQ_enqReq_rl;
  MOD_Reg<tUInt8> INST_pendQ_full;
  MOD_Wire<tUInt8> INST_reqQ_clearReq_lat_0;
  MOD_Wire<tUInt8> INST_reqQ_clearReq_lat_1;
  MOD_Reg<tUInt8> INST_reqQ_clearReq_rl;
  MOD_Reg<tUWide> INST_reqQ_data_0;
  MOD_Wire<tUInt8> INST_reqQ_deqReq_lat_0;
  MOD_Wire<tUInt8> INST_reqQ_deqReq_lat_1;
  MOD_Wire<tUInt8> INST_reqQ_deqReq_lat_2;
  MOD_Reg<tUInt8> INST_reqQ_deqReq_rl;
  MOD_Reg<tUInt8> INST_reqQ_empty;
  MOD_Wire<tUWide> INST_reqQ_enqReq_lat_0;
  MOD_Wire<tUWide> INST_reqQ_enqReq_lat_1;
  MOD_Wire<tUWide> INST_reqQ_enqReq_lat_2;
  MOD_Reg<tUWide> INST_reqQ_enqReq_rl;
  MOD_Reg<tUInt8> INST_reqQ_full;
  MOD_Wire<tUInt8> INST_respQ_clearReq_lat_0;
  MOD_Wire<tUInt8> INST_respQ_clearReq_lat_1;
  MOD_Reg<tUInt8> INST_respQ_clearReq_rl;
  MOD_Reg<tUWide> INST_respQ_data_0;
  MOD_Wire<tUInt8> INST_respQ_deqReq_lat_0;
  MOD_Wire<tUInt8> INST_respQ_deqReq_lat_1;
  MOD_Wire<tUInt8> INST_respQ_deqReq_lat_2;
  MOD_Reg<tUInt8> INST_respQ_deqReq_rl;
  MOD_Reg<tUInt8> INST_respQ_empty;
  MOD_Wire<tUWide> INST_respQ_enqReq_lat_0;
  MOD_Wire<tUWide> INST_respQ_enqReq_lat_1;
  MOD_Wire<tUWide> INST_respQ_enqReq_lat_2;
  MOD_Reg<tUWide> INST_respQ_enqReq_rl;
  MOD_Reg<tUInt8> INST_respQ_full;
  MOD_mkSoC_Map INST_soc_map;
  MOD_ConfigReg<tUInt64> INST_toHostAddr;
 
 /* Constructor */
 public:
  MOD_mkMMIOInst(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_toCore_instResp_enq_x;
  tUWide PORT_bootRomResp;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_NOT_reqQ_empty_0___d191;
  tUInt8 DEF_NOT_respQ_full_02___d193;
  tUInt8 DEF_pendQ_full__h13976;
  tUInt8 DEF_pendQ_empty__h14012;
  tUInt8 DEF_respQ_full__h10732;
  tUInt8 DEF_respQ_empty__h10768;
  tUInt8 DEF_reqQ_full__h3359;
  tUInt8 DEF_reqQ_empty__h3395;
 
 /* Local definitions */
 private:
  tUInt8 DEF_IF_pendQ_enqReq_lat_1_whas__24_THEN_pendQ_enqR_ETC___d130;
  tUInt8 DEF_IF_pendQ_clearReq_lat_0_whas__44_THEN_pendQ_cl_ETC___d147;
  tUInt8 DEF_IF_respQ_clearReq_lat_0_whas__4_THEN_respQ_cle_ETC___d87;
  tUInt8 DEF_IF_reqQ_clearReq_lat_0_whas__3_THEN_reqQ_clear_ETC___d26;
  tUWide DEF_respQ_enqReq_rl___d68;
  tUWide DEF_respQ_enqReq_lat_2_wget____d63;
  tUWide DEF_respQ_enqReq_lat_1_wget____d65;
  tUWide DEF_respQ_enqReq_lat_0_wget____d67;
  tUWide DEF_respQ_data_0__h14977;
  tUWide DEF_reqQ_enqReq_rl___d7;
  tUWide DEF_reqQ_enqReq_lat_2_wget____d2;
  tUWide DEF_reqQ_enqReq_lat_1_wget____d4;
  tUWide DEF_reqQ_enqReq_lat_0_wget____d6;
  tUWide DEF_reqQ_data_0___d192;
  tUInt8 DEF_pendQ_clearReq_rl__h13096;
  tUInt8 DEF_pendQ_clearReq_lat_0_whas____d144;
  tUInt8 DEF_pendQ_clearReq_lat_0_wget____d145;
  tUInt8 DEF_pendQ_deqReq_rl__h12520;
  tUInt8 DEF_pendQ_deqReq_lat_1_whas____d134;
  tUInt8 DEF_pendQ_deqReq_lat_1_wget____d135;
  tUInt8 DEF_pendQ_deqReq_lat_0_whas____d136;
  tUInt8 DEF_pendQ_deqReq_lat_0_wget____d137;
  tUInt8 DEF_pendQ_enqReq_rl__h11768;
  tUInt8 DEF_pendQ_enqReq_lat_1_whas____d124;
  tUInt8 DEF_pendQ_enqReq_lat_1_wget____d125;
  tUInt8 DEF_pendQ_enqReq_lat_0_whas____d126;
  tUInt8 DEF_pendQ_enqReq_lat_0_wget____d127;
  tUInt8 DEF_respQ_clearReq_rl__h7945;
  tUInt8 DEF_respQ_clearReq_lat_0_whas____d84;
  tUInt8 DEF_respQ_clearReq_lat_0_wget____d85;
  tUInt8 DEF_respQ_deqReq_rl__h7369;
  tUInt8 DEF_respQ_deqReq_lat_1_whas____d74;
  tUInt8 DEF_respQ_deqReq_lat_1_wget____d75;
  tUInt8 DEF_respQ_deqReq_lat_0_whas____d76;
  tUInt8 DEF_respQ_deqReq_lat_0_wget____d77;
  tUInt8 DEF_respQ_enqReq_lat_1_whas____d64;
  tUInt8 DEF_respQ_enqReq_lat_0_whas____d66;
  tUInt8 DEF_reqQ_clearReq_rl__h2341;
  tUInt8 DEF_reqQ_clearReq_lat_0_whas____d23;
  tUInt8 DEF_reqQ_clearReq_lat_0_wget____d24;
  tUInt8 DEF_reqQ_deqReq_rl__h1763;
  tUInt8 DEF_reqQ_deqReq_lat_1_whas____d13;
  tUInt8 DEF_reqQ_deqReq_lat_1_wget____d14;
  tUInt8 DEF_reqQ_deqReq_lat_0_whas____d15;
  tUInt8 DEF_reqQ_deqReq_lat_0_wget____d16;
  tUInt8 DEF_reqQ_enqReq_lat_1_whas____d3;
  tUInt8 DEF_reqQ_enqReq_lat_0_whas____d5;
  tUWide DEF_respQ_enqReq_rl_8_BITS_67_TO_0___d118;
  tUWide DEF_respQ_enqReq_lat_1_wget__5_BITS_67_TO_0___d116;
  tUWide DEF_respQ_enqReq_lat_0_wget__7_BITS_67_TO_0___d117;
  tUWide DEF_reqQ_enqReq_rl_BITS_65_TO_0___d57;
  tUWide DEF_reqQ_enqReq_lat_1_wget_BITS_65_TO_0___d55;
  tUWide DEF_reqQ_enqReq_lat_0_wget_BITS_65_TO_0___d56;
  tUWide DEF_IF_respQ_enqReq_lat_2_whas__2_THEN_respQ_enqRe_ETC___d71;
  tUWide DEF_IF_respQ_enqReq_lat_1_whas__4_THEN_respQ_enqRe_ETC___d70;
  tUWide DEF_IF_respQ_enqReq_lat_0_whas__6_THEN_respQ_enqRe_ETC___d69;
  tUWide DEF_IF_respQ_enqReq_lat_0_whas__6_THEN_respQ_enqRe_ETC___d119;
  tUWide DEF_IF_respQ_enqReq_lat_1_whas__4_THEN_respQ_enqRe_ETC___d120;
  tUWide DEF_IF_reqQ_enqReq_lat_2_whas_THEN_reqQ_enqReq_lat_ETC___d10;
  tUWide DEF_IF_reqQ_enqReq_lat_1_whas_THEN_reqQ_enqReq_lat_ETC___d9;
  tUWide DEF_IF_reqQ_enqReq_lat_0_whas_THEN_reqQ_enqReq_lat_ETC___d8;
  tUWide DEF_IF_IF_reqQ_enqReq_lat_1_whas_THEN_NOT_reqQ_enq_ETC___d60;
  tUWide DEF_IF_reqQ_enqReq_lat_1_whas_THEN_reqQ_enqReq_lat_ETC___d59;
  tUWide DEF_IF_reqQ_enqReq_lat_0_whas_THEN_reqQ_enqReq_lat_ETC___d58;
  tUInt8 DEF_IF_pendQ_deqReq_lat_1_whas__34_THEN_pendQ_deqR_ETC___d140;
  tUInt8 DEF_IF_respQ_deqReq_lat_1_whas__4_THEN_respQ_deqRe_ETC___d80;
  tUInt8 DEF_IF_reqQ_deqReq_lat_1_whas__3_THEN_reqQ_deqReq__ETC___d19;
  tUWide DEF__1_CONCAT_toCore_instResp_enq_x___d194;
  tUWide DEF__0_CONCAT_DONTCARE___d121;
  tUWide DEF__1_CONCAT_bootRomReq_phyPc_CONCAT_bootRomReq_ma_ETC___d185;
  tUWide DEF__0_CONCAT_DONTCARE___d61;
 
 /* Rules */
 public:
  void RL_reqQ_enqReq_canon();
  void RL_reqQ_deqReq_canon();
  void RL_reqQ_clearReq_canon();
  void RL_reqQ_canonicalize();
  void RL_respQ_enqReq_canon();
  void RL_respQ_deqReq_canon();
  void RL_respQ_clearReq_canon();
  void RL_respQ_canonicalize();
  void RL_pendQ_enqReq_canon();
  void RL_pendQ_deqReq_canon();
  void RL_pendQ_clearReq_canon();
  void RL_pendQ_canonicalize();
 
 /* Methods */
 public:
  tUInt8 METH_getFetchTarget(tUInt64 ARG_getFetchTarget_phyPc);
  tUInt8 METH_RDY_getFetchTarget();
  void METH_bootRomReq(tUInt64 ARG_bootRomReq_phyPc, tUInt8 ARG_bootRomReq_maxWay);
  tUInt8 METH_RDY_bootRomReq();
  tUWide METH_bootRomResp();
  tUInt8 METH_RDY_bootRomResp();
  tUInt8 METH_toCore_instReq_notEmpty();
  tUInt8 METH_RDY_toCore_instReq_notEmpty();
  void METH_toCore_instReq_deq();
  tUInt8 METH_RDY_toCore_instReq_deq();
  tUInt64 METH_toCore_instReq_first_fst();
  tUInt8 METH_RDY_toCore_instReq_first_fst();
  tUInt8 METH_toCore_instReq_first_snd();
  tUInt8 METH_RDY_toCore_instReq_first_snd();
  tUInt8 METH_toCore_instResp_notFull();
  tUInt8 METH_RDY_toCore_instResp_notFull();
  void METH_toCore_instResp_enq(tUWide ARG_toCore_instResp_enq_x);
  tUInt8 METH_RDY_toCore_instResp_enq();
  void METH_toCore_setHtifAddrs(tUInt64 ARG_toCore_setHtifAddrs_toHost,
				tUInt64 ARG_toCore_setHtifAddrs_fromHost);
  tUInt8 METH_RDY_toCore_setHtifAddrs();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMMIOInst &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMMIOInst &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMMIOInst &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkMMIOInst &backing);
};

#endif /* ifndef __mkMMIOInst_h__ */
