/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkPerfCountersToooba_h__
#define __mkPerfCountersToooba_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkPerfCountersToooba module */
class MOD_mkPerfCountersToooba : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUWide> INST_perf_counters_events_wire;
  MOD_ConfigReg<tUInt32> INST_perf_counters_rg_ctr_inhibit;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_0;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_1;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_10;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_11;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_12;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_13;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_14;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_15;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_16;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_17;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_18;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_19;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_2;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_20;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_21;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_22;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_23;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_24;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_25;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_26;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_27;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_28;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_3;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_4;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_5;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_6;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_7;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_8;
  MOD_ConfigReg<tUInt64> INST_perf_counters_vec_rg_counter_9;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_0;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_1;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_10;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_11;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_12;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_13;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_14;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_15;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_16;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_17;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_18;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_19;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_2;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_20;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_21;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_22;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_23;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_24;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_25;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_26;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_27;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_28;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_3;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_4;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_5;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_6;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_7;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_8;
  MOD_ConfigReg<tUInt8> INST_perf_counters_vec_rg_event_sel_9;
  MOD_Wire<tUInt32> INST_perf_counters_wr_overflow;
  MOD_Wire<tUWide> INST_perf_counters_write_counter_wire;
  MOD_Wire<tUInt32> INST_perf_counters_write_ctr_sel_wire;
  MOD_Fifo<tUWide> INST_writeCounterFF;
  MOD_Fifo<tUInt32> INST_writeCounterInhibitFF;
  MOD_Fifo<tUInt32> INST_writeCounterSelFF;
 
 /* Constructor */
 public:
  MOD_mkPerfCountersToooba(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_send_performance_events_evts;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_writeCounterSelFF_i_notFull____d830;
  tUInt8 DEF_writeCounterFF_i_notFull____d799;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h32536;
  tUInt8 DEF_x__h32465;
  tUInt8 DEF_x__h32394;
  tUInt8 DEF_x__h32323;
  tUInt8 DEF_x__h32252;
  tUInt8 DEF_x__h32181;
  tUInt8 DEF_x__h32110;
  tUInt8 DEF_x__h32039;
  tUInt8 DEF_x__h31968;
  tUInt8 DEF_x__h31897;
  tUInt8 DEF_x__h31826;
  tUInt8 DEF_x__h31755;
  tUInt8 DEF_x__h31684;
  tUInt8 DEF_x__h31613;
  tUInt8 DEF_x__h31542;
  tUInt8 DEF_x__h31471;
  tUInt8 DEF_x__h31400;
  tUInt8 DEF_x__h31329;
  tUInt8 DEF_x__h31258;
  tUInt8 DEF_x__h31187;
  tUInt8 DEF_x__h31116;
  tUInt8 DEF_x__h31045;
  tUInt8 DEF_x__h30974;
  tUInt8 DEF_x__h30903;
  tUInt8 DEF_x__h30832;
  tUInt8 DEF_x__h30761;
  tUInt8 DEF_x__h30690;
  tUInt8 DEF_x__h30619;
  tUInt8 DEF_x__h29952;
  tUWide DEF_perf_counters_events_wire_wget____d98;
  tUWide DEF_perf_counters_write_counter_wire_wget____d615;
  tUWide DEF_writeCounterFF_first____d793;
  tUInt64 DEF_perf_counters_vec_rg_counter_28_read____d601;
  tUInt64 DEF_perf_counters_vec_rg_counter_27_read____d588;
  tUInt64 DEF_perf_counters_vec_rg_counter_26_read____d574;
  tUInt64 DEF_perf_counters_vec_rg_counter_25_read____d560;
  tUInt64 DEF_perf_counters_vec_rg_counter_24_read____d546;
  tUInt64 DEF_perf_counters_vec_rg_counter_23_read____d532;
  tUInt64 DEF_perf_counters_vec_rg_counter_22_read____d518;
  tUInt64 DEF_perf_counters_vec_rg_counter_21_read____d504;
  tUInt64 DEF_perf_counters_vec_rg_counter_20_read____d490;
  tUInt64 DEF_perf_counters_vec_rg_counter_19_read____d476;
  tUInt64 DEF_perf_counters_vec_rg_counter_18_read____d462;
  tUInt64 DEF_perf_counters_vec_rg_counter_17_read____d448;
  tUInt64 DEF_perf_counters_vec_rg_counter_16_read____d434;
  tUInt64 DEF_perf_counters_vec_rg_counter_15_read____d420;
  tUInt64 DEF_perf_counters_vec_rg_counter_14_read____d406;
  tUInt64 DEF_perf_counters_vec_rg_counter_13_read____d392;
  tUInt64 DEF_perf_counters_vec_rg_counter_12_read____d378;
  tUInt64 DEF_perf_counters_vec_rg_counter_11_read____d364;
  tUInt64 DEF_perf_counters_vec_rg_counter_10_read____d350;
  tUInt64 DEF_perf_counters_vec_rg_counter_9_read____d336;
  tUInt64 DEF_perf_counters_vec_rg_counter_8_read____d322;
  tUInt64 DEF_perf_counters_vec_rg_counter_7_read____d308;
  tUInt64 DEF_perf_counters_vec_rg_counter_6_read____d294;
  tUInt64 DEF_perf_counters_vec_rg_counter_5_read____d280;
  tUInt64 DEF_perf_counters_vec_rg_counter_4_read____d266;
  tUInt64 DEF_perf_counters_vec_rg_counter_3_read____d252;
  tUInt64 DEF_perf_counters_vec_rg_counter_2_read____d238;
  tUInt64 DEF_perf_counters_vec_rg_counter_1_read____d224;
  tUInt64 DEF_perf_counters_vec_rg_counter_0_read____d94;
  tUInt32 DEF_perf_counters_rg_ctr_inhibit_read____d64;
  tUWide DEF_count_sum__h5674;
  tUWide DEF_count_sum__h5721;
  tUWide DEF_count_sum__h5768;
  tUWide DEF_count_sum__h5815;
  tUWide DEF_count_sum__h5862;
  tUWide DEF_count_sum__h5909;
  tUWide DEF_count_sum__h5956;
  tUWide DEF_count_sum__h6003;
  tUWide DEF_count_sum__h6050;
  tUWide DEF_count_sum__h6097;
  tUWide DEF_count_sum__h6144;
  tUWide DEF_count_sum__h6191;
  tUWide DEF_count_sum__h6238;
  tUWide DEF_count_sum__h6285;
  tUWide DEF_count_sum__h6332;
  tUWide DEF_count_sum__h6379;
  tUWide DEF_count_sum__h6426;
  tUWide DEF_count_sum__h6473;
  tUWide DEF_count_sum__h6520;
  tUWide DEF_count_sum__h6567;
  tUWide DEF_count_sum__h6614;
  tUWide DEF_count_sum__h6661;
  tUWide DEF_count_sum__h6708;
  tUWide DEF_count_sum__h6755;
  tUWide DEF_count_sum__h6802;
  tUWide DEF_count_sum__h6849;
  tUWide DEF_count_sum__h6896;
  tUWide DEF_count_sum__h6943;
  tUWide DEF_count_sum__h6990;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_28_read__01___d602;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_28__ETC___d608;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_27_read__88___d589;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_27__ETC___d595;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_26_read__74___d575;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_26__ETC___d581;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_25_read__60___d561;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_25__ETC___d567;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_24_read__46___d547;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_24__ETC___d553;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_23_read__32___d533;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_23__ETC___d539;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_22_read__18___d519;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_22__ETC___d525;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_21_read__04___d505;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_21__ETC___d511;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_20_read__90___d491;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_20__ETC___d497;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_19_read__76___d477;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_19__ETC___d483;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_18_read__62___d463;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_18__ETC___d469;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_17_read__48___d449;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_17__ETC___d455;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_16_read__34___d435;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_16__ETC___d441;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_15_read__20___d421;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_15__ETC___d427;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_14_read__06___d407;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_14__ETC___d413;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_13_read__92___d393;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_13__ETC___d399;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_12_read__78___d379;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_12__ETC___d385;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_11_read__64___d365;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_11__ETC___d371;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_10_read__50___d351;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_10__ETC___d357;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_9_read__36___d337;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_9_r_ETC___d343;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_8_read__22___d323;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_8_r_ETC___d329;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_7_read__08___d309;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_7_r_ETC___d315;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_6_read__94___d295;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_6_r_ETC___d301;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_5_read__80___d281;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_5_r_ETC___d287;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_4_read__66___d267;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_4_r_ETC___d273;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_3_read__52___d253;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_3_r_ETC___d259;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_2_read__38___d239;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_2_r_ETC___d245;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_1_read__24___d225;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_1_r_ETC___d231;
  tUWide DEF__0_CONCAT_perf_counters_vec_rg_counter_0_read__4___d95;
  tUWide DEF__0_CONCAT_IF_perf_counters_vec_rg_event_sel_0_r_ETC___d218;
  tUWide DEF__28_CONCAT_counter_vec_28__write_1___d827;
  tUWide DEF__27_CONCAT_counter_vec_27__write_1___d826;
  tUWide DEF__26_CONCAT_counter_vec_26__write_1___d825;
  tUWide DEF__25_CONCAT_counter_vec_25__write_1___d824;
  tUWide DEF__24_CONCAT_counter_vec_24__write_1___d823;
  tUWide DEF__23_CONCAT_counter_vec_23__write_1___d822;
  tUWide DEF__22_CONCAT_counter_vec_22__write_1___d821;
  tUWide DEF__21_CONCAT_counter_vec_21__write_1___d820;
  tUWide DEF__20_CONCAT_counter_vec_20__write_1___d819;
  tUWide DEF__19_CONCAT_counter_vec_19__write_1___d818;
  tUWide DEF__18_CONCAT_counter_vec_18__write_1___d817;
  tUWide DEF__17_CONCAT_counter_vec_17__write_1___d816;
  tUWide DEF__16_CONCAT_counter_vec_16__write_1___d815;
  tUWide DEF__15_CONCAT_counter_vec_15__write_1___d814;
  tUWide DEF__14_CONCAT_counter_vec_14__write_1___d813;
  tUWide DEF__13_CONCAT_counter_vec_13__write_1___d812;
  tUWide DEF__12_CONCAT_counter_vec_12__write_1___d811;
  tUWide DEF__11_CONCAT_counter_vec_11__write_1___d810;
  tUWide DEF__10_CONCAT_counter_vec_10__write_1___d809;
  tUWide DEF__9_CONCAT_counter_vec_9__write_1___d808;
  tUWide DEF__8_CONCAT_counter_vec_8__write_1___d807;
  tUWide DEF__7_CONCAT_counter_vec_7__write_1___d806;
  tUWide DEF__6_CONCAT_counter_vec_6__write_1___d805;
  tUWide DEF__5_CONCAT_counter_vec_5__write_1___d804;
  tUWide DEF__4_CONCAT_counter_vec_4__write_1___d803;
  tUWide DEF__3_CONCAT_counter_vec_3__write_1___d802;
  tUWide DEF__2_CONCAT_counter_vec_2__write_1___d801;
  tUWide DEF__1_CONCAT_counter_vec_1__write_1___d800;
  tUWide DEF__0_CONCAT_counter_vec_0__write_1___d798;
 
 /* Rules */
 public:
  void RL_perf_counters_do_writes();
  void RL_forwardWriteCounter();
  void RL_forwardWriteCounterSel();
  void RL_forwardWriteCounterInhibit();
 
 /* Methods */
 public:
  void METH_counter_vec_0__write(tUInt64 ARG_counter_vec_0__write_1);
  tUInt8 METH_RDY_counter_vec_0__write();
  tUInt64 METH_counter_vec_0__read();
  tUInt8 METH_RDY_counter_vec_0__read();
  void METH_counter_vec_1__write(tUInt64 ARG_counter_vec_1__write_1);
  tUInt8 METH_RDY_counter_vec_1__write();
  tUInt64 METH_counter_vec_1__read();
  tUInt8 METH_RDY_counter_vec_1__read();
  void METH_counter_vec_2__write(tUInt64 ARG_counter_vec_2__write_1);
  tUInt8 METH_RDY_counter_vec_2__write();
  tUInt64 METH_counter_vec_2__read();
  tUInt8 METH_RDY_counter_vec_2__read();
  void METH_counter_vec_3__write(tUInt64 ARG_counter_vec_3__write_1);
  tUInt8 METH_RDY_counter_vec_3__write();
  tUInt64 METH_counter_vec_3__read();
  tUInt8 METH_RDY_counter_vec_3__read();
  void METH_counter_vec_4__write(tUInt64 ARG_counter_vec_4__write_1);
  tUInt8 METH_RDY_counter_vec_4__write();
  tUInt64 METH_counter_vec_4__read();
  tUInt8 METH_RDY_counter_vec_4__read();
  void METH_counter_vec_5__write(tUInt64 ARG_counter_vec_5__write_1);
  tUInt8 METH_RDY_counter_vec_5__write();
  tUInt64 METH_counter_vec_5__read();
  tUInt8 METH_RDY_counter_vec_5__read();
  void METH_counter_vec_6__write(tUInt64 ARG_counter_vec_6__write_1);
  tUInt8 METH_RDY_counter_vec_6__write();
  tUInt64 METH_counter_vec_6__read();
  tUInt8 METH_RDY_counter_vec_6__read();
  void METH_counter_vec_7__write(tUInt64 ARG_counter_vec_7__write_1);
  tUInt8 METH_RDY_counter_vec_7__write();
  tUInt64 METH_counter_vec_7__read();
  tUInt8 METH_RDY_counter_vec_7__read();
  void METH_counter_vec_8__write(tUInt64 ARG_counter_vec_8__write_1);
  tUInt8 METH_RDY_counter_vec_8__write();
  tUInt64 METH_counter_vec_8__read();
  tUInt8 METH_RDY_counter_vec_8__read();
  void METH_counter_vec_9__write(tUInt64 ARG_counter_vec_9__write_1);
  tUInt8 METH_RDY_counter_vec_9__write();
  tUInt64 METH_counter_vec_9__read();
  tUInt8 METH_RDY_counter_vec_9__read();
  void METH_counter_vec_10__write(tUInt64 ARG_counter_vec_10__write_1);
  tUInt8 METH_RDY_counter_vec_10__write();
  tUInt64 METH_counter_vec_10__read();
  tUInt8 METH_RDY_counter_vec_10__read();
  void METH_counter_vec_11__write(tUInt64 ARG_counter_vec_11__write_1);
  tUInt8 METH_RDY_counter_vec_11__write();
  tUInt64 METH_counter_vec_11__read();
  tUInt8 METH_RDY_counter_vec_11__read();
  void METH_counter_vec_12__write(tUInt64 ARG_counter_vec_12__write_1);
  tUInt8 METH_RDY_counter_vec_12__write();
  tUInt64 METH_counter_vec_12__read();
  tUInt8 METH_RDY_counter_vec_12__read();
  void METH_counter_vec_13__write(tUInt64 ARG_counter_vec_13__write_1);
  tUInt8 METH_RDY_counter_vec_13__write();
  tUInt64 METH_counter_vec_13__read();
  tUInt8 METH_RDY_counter_vec_13__read();
  void METH_counter_vec_14__write(tUInt64 ARG_counter_vec_14__write_1);
  tUInt8 METH_RDY_counter_vec_14__write();
  tUInt64 METH_counter_vec_14__read();
  tUInt8 METH_RDY_counter_vec_14__read();
  void METH_counter_vec_15__write(tUInt64 ARG_counter_vec_15__write_1);
  tUInt8 METH_RDY_counter_vec_15__write();
  tUInt64 METH_counter_vec_15__read();
  tUInt8 METH_RDY_counter_vec_15__read();
  void METH_counter_vec_16__write(tUInt64 ARG_counter_vec_16__write_1);
  tUInt8 METH_RDY_counter_vec_16__write();
  tUInt64 METH_counter_vec_16__read();
  tUInt8 METH_RDY_counter_vec_16__read();
  void METH_counter_vec_17__write(tUInt64 ARG_counter_vec_17__write_1);
  tUInt8 METH_RDY_counter_vec_17__write();
  tUInt64 METH_counter_vec_17__read();
  tUInt8 METH_RDY_counter_vec_17__read();
  void METH_counter_vec_18__write(tUInt64 ARG_counter_vec_18__write_1);
  tUInt8 METH_RDY_counter_vec_18__write();
  tUInt64 METH_counter_vec_18__read();
  tUInt8 METH_RDY_counter_vec_18__read();
  void METH_counter_vec_19__write(tUInt64 ARG_counter_vec_19__write_1);
  tUInt8 METH_RDY_counter_vec_19__write();
  tUInt64 METH_counter_vec_19__read();
  tUInt8 METH_RDY_counter_vec_19__read();
  void METH_counter_vec_20__write(tUInt64 ARG_counter_vec_20__write_1);
  tUInt8 METH_RDY_counter_vec_20__write();
  tUInt64 METH_counter_vec_20__read();
  tUInt8 METH_RDY_counter_vec_20__read();
  void METH_counter_vec_21__write(tUInt64 ARG_counter_vec_21__write_1);
  tUInt8 METH_RDY_counter_vec_21__write();
  tUInt64 METH_counter_vec_21__read();
  tUInt8 METH_RDY_counter_vec_21__read();
  void METH_counter_vec_22__write(tUInt64 ARG_counter_vec_22__write_1);
  tUInt8 METH_RDY_counter_vec_22__write();
  tUInt64 METH_counter_vec_22__read();
  tUInt8 METH_RDY_counter_vec_22__read();
  void METH_counter_vec_23__write(tUInt64 ARG_counter_vec_23__write_1);
  tUInt8 METH_RDY_counter_vec_23__write();
  tUInt64 METH_counter_vec_23__read();
  tUInt8 METH_RDY_counter_vec_23__read();
  void METH_counter_vec_24__write(tUInt64 ARG_counter_vec_24__write_1);
  tUInt8 METH_RDY_counter_vec_24__write();
  tUInt64 METH_counter_vec_24__read();
  tUInt8 METH_RDY_counter_vec_24__read();
  void METH_counter_vec_25__write(tUInt64 ARG_counter_vec_25__write_1);
  tUInt8 METH_RDY_counter_vec_25__write();
  tUInt64 METH_counter_vec_25__read();
  tUInt8 METH_RDY_counter_vec_25__read();
  void METH_counter_vec_26__write(tUInt64 ARG_counter_vec_26__write_1);
  tUInt8 METH_RDY_counter_vec_26__write();
  tUInt64 METH_counter_vec_26__read();
  tUInt8 METH_RDY_counter_vec_26__read();
  void METH_counter_vec_27__write(tUInt64 ARG_counter_vec_27__write_1);
  tUInt8 METH_RDY_counter_vec_27__write();
  tUInt64 METH_counter_vec_27__read();
  tUInt8 METH_RDY_counter_vec_27__read();
  void METH_counter_vec_28__write(tUInt64 ARG_counter_vec_28__write_1);
  tUInt8 METH_RDY_counter_vec_28__write();
  tUInt64 METH_counter_vec_28__read();
  tUInt8 METH_RDY_counter_vec_28__read();
  void METH_event_vec_0__write(tUInt64 ARG_event_vec_0__write_1);
  tUInt8 METH_RDY_event_vec_0__write();
  tUInt64 METH_event_vec_0__read();
  tUInt8 METH_RDY_event_vec_0__read();
  void METH_event_vec_1__write(tUInt64 ARG_event_vec_1__write_1);
  tUInt8 METH_RDY_event_vec_1__write();
  tUInt64 METH_event_vec_1__read();
  tUInt8 METH_RDY_event_vec_1__read();
  void METH_event_vec_2__write(tUInt64 ARG_event_vec_2__write_1);
  tUInt8 METH_RDY_event_vec_2__write();
  tUInt64 METH_event_vec_2__read();
  tUInt8 METH_RDY_event_vec_2__read();
  void METH_event_vec_3__write(tUInt64 ARG_event_vec_3__write_1);
  tUInt8 METH_RDY_event_vec_3__write();
  tUInt64 METH_event_vec_3__read();
  tUInt8 METH_RDY_event_vec_3__read();
  void METH_event_vec_4__write(tUInt64 ARG_event_vec_4__write_1);
  tUInt8 METH_RDY_event_vec_4__write();
  tUInt64 METH_event_vec_4__read();
  tUInt8 METH_RDY_event_vec_4__read();
  void METH_event_vec_5__write(tUInt64 ARG_event_vec_5__write_1);
  tUInt8 METH_RDY_event_vec_5__write();
  tUInt64 METH_event_vec_5__read();
  tUInt8 METH_RDY_event_vec_5__read();
  void METH_event_vec_6__write(tUInt64 ARG_event_vec_6__write_1);
  tUInt8 METH_RDY_event_vec_6__write();
  tUInt64 METH_event_vec_6__read();
  tUInt8 METH_RDY_event_vec_6__read();
  void METH_event_vec_7__write(tUInt64 ARG_event_vec_7__write_1);
  tUInt8 METH_RDY_event_vec_7__write();
  tUInt64 METH_event_vec_7__read();
  tUInt8 METH_RDY_event_vec_7__read();
  void METH_event_vec_8__write(tUInt64 ARG_event_vec_8__write_1);
  tUInt8 METH_RDY_event_vec_8__write();
  tUInt64 METH_event_vec_8__read();
  tUInt8 METH_RDY_event_vec_8__read();
  void METH_event_vec_9__write(tUInt64 ARG_event_vec_9__write_1);
  tUInt8 METH_RDY_event_vec_9__write();
  tUInt64 METH_event_vec_9__read();
  tUInt8 METH_RDY_event_vec_9__read();
  void METH_event_vec_10__write(tUInt64 ARG_event_vec_10__write_1);
  tUInt8 METH_RDY_event_vec_10__write();
  tUInt64 METH_event_vec_10__read();
  tUInt8 METH_RDY_event_vec_10__read();
  void METH_event_vec_11__write(tUInt64 ARG_event_vec_11__write_1);
  tUInt8 METH_RDY_event_vec_11__write();
  tUInt64 METH_event_vec_11__read();
  tUInt8 METH_RDY_event_vec_11__read();
  void METH_event_vec_12__write(tUInt64 ARG_event_vec_12__write_1);
  tUInt8 METH_RDY_event_vec_12__write();
  tUInt64 METH_event_vec_12__read();
  tUInt8 METH_RDY_event_vec_12__read();
  void METH_event_vec_13__write(tUInt64 ARG_event_vec_13__write_1);
  tUInt8 METH_RDY_event_vec_13__write();
  tUInt64 METH_event_vec_13__read();
  tUInt8 METH_RDY_event_vec_13__read();
  void METH_event_vec_14__write(tUInt64 ARG_event_vec_14__write_1);
  tUInt8 METH_RDY_event_vec_14__write();
  tUInt64 METH_event_vec_14__read();
  tUInt8 METH_RDY_event_vec_14__read();
  void METH_event_vec_15__write(tUInt64 ARG_event_vec_15__write_1);
  tUInt8 METH_RDY_event_vec_15__write();
  tUInt64 METH_event_vec_15__read();
  tUInt8 METH_RDY_event_vec_15__read();
  void METH_event_vec_16__write(tUInt64 ARG_event_vec_16__write_1);
  tUInt8 METH_RDY_event_vec_16__write();
  tUInt64 METH_event_vec_16__read();
  tUInt8 METH_RDY_event_vec_16__read();
  void METH_event_vec_17__write(tUInt64 ARG_event_vec_17__write_1);
  tUInt8 METH_RDY_event_vec_17__write();
  tUInt64 METH_event_vec_17__read();
  tUInt8 METH_RDY_event_vec_17__read();
  void METH_event_vec_18__write(tUInt64 ARG_event_vec_18__write_1);
  tUInt8 METH_RDY_event_vec_18__write();
  tUInt64 METH_event_vec_18__read();
  tUInt8 METH_RDY_event_vec_18__read();
  void METH_event_vec_19__write(tUInt64 ARG_event_vec_19__write_1);
  tUInt8 METH_RDY_event_vec_19__write();
  tUInt64 METH_event_vec_19__read();
  tUInt8 METH_RDY_event_vec_19__read();
  void METH_event_vec_20__write(tUInt64 ARG_event_vec_20__write_1);
  tUInt8 METH_RDY_event_vec_20__write();
  tUInt64 METH_event_vec_20__read();
  tUInt8 METH_RDY_event_vec_20__read();
  void METH_event_vec_21__write(tUInt64 ARG_event_vec_21__write_1);
  tUInt8 METH_RDY_event_vec_21__write();
  tUInt64 METH_event_vec_21__read();
  tUInt8 METH_RDY_event_vec_21__read();
  void METH_event_vec_22__write(tUInt64 ARG_event_vec_22__write_1);
  tUInt8 METH_RDY_event_vec_22__write();
  tUInt64 METH_event_vec_22__read();
  tUInt8 METH_RDY_event_vec_22__read();
  void METH_event_vec_23__write(tUInt64 ARG_event_vec_23__write_1);
  tUInt8 METH_RDY_event_vec_23__write();
  tUInt64 METH_event_vec_23__read();
  tUInt8 METH_RDY_event_vec_23__read();
  void METH_event_vec_24__write(tUInt64 ARG_event_vec_24__write_1);
  tUInt8 METH_RDY_event_vec_24__write();
  tUInt64 METH_event_vec_24__read();
  tUInt8 METH_RDY_event_vec_24__read();
  void METH_event_vec_25__write(tUInt64 ARG_event_vec_25__write_1);
  tUInt8 METH_RDY_event_vec_25__write();
  tUInt64 METH_event_vec_25__read();
  tUInt8 METH_RDY_event_vec_25__read();
  void METH_event_vec_26__write(tUInt64 ARG_event_vec_26__write_1);
  tUInt8 METH_RDY_event_vec_26__write();
  tUInt64 METH_event_vec_26__read();
  tUInt8 METH_RDY_event_vec_26__read();
  void METH_event_vec_27__write(tUInt64 ARG_event_vec_27__write_1);
  tUInt8 METH_RDY_event_vec_27__write();
  tUInt64 METH_event_vec_27__read();
  tUInt8 METH_RDY_event_vec_27__read();
  void METH_event_vec_28__write(tUInt64 ARG_event_vec_28__write_1);
  tUInt8 METH_RDY_event_vec_28__write();
  tUInt64 METH_event_vec_28__read();
  tUInt8 METH_RDY_event_vec_28__read();
  void METH_inhibit__write(tUInt32 ARG_inhibit__write_1);
  tUInt8 METH_RDY_inhibit__write();
  tUInt32 METH_inhibit__read();
  tUInt8 METH_RDY_inhibit__read();
  void METH_send_performance_events(tUWide ARG_send_performance_events_evts);
  tUInt8 METH_RDY_send_performance_events();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkPerfCountersToooba &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkPerfCountersToooba &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkPerfCountersToooba &backing);
};

#endif /* ifndef __mkPerfCountersToooba_h__ */
