/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkPLIC_16_CoreNumX2_7_h__
#define __mkPLIC_16_CoreNumX2_7_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkPLIC_16_CoreNumX2_7 module */
class MOD_mkPLIC_16_CoreNumX2_7 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_ConfigReg<tUInt8> INST_m_cfg_verbosity;
  MOD_Fifo<tUInt8> INST_m_f_reset_reqs;
  MOD_Fifo<tUInt8> INST_m_f_reset_rsps;
  MOD_Reg<tUInt64> INST_m_rg_addr_base;
  MOD_Reg<tUInt64> INST_m_rg_addr_lim;
  MOD_Fifo<tUWide> INST_m_slavePortShim_shim_arff;
  MOD_Fifo<tUWide> INST_m_slavePortShim_shim_awff;
  MOD_Fifo<tUInt8> INST_m_slavePortShim_shim_bff;
  MOD_Fifo<tUWide> INST_m_slavePortShim_shim_rff;
  MOD_Fifo<tUWide> INST_m_slavePortShim_shim_wff;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_0;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_1;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_10;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_11;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_12;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_13;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_14;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_15;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_16;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_2;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_3;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_4;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_5;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_6;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_7;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_8;
  MOD_Reg<tUInt8> INST_m_vrg_source_busy_9;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_0;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_1;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_10;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_11;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_12;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_13;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_14;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_15;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_16;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_2;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_3;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_4;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_5;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_6;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_7;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_8;
  MOD_ConfigReg<tUInt8> INST_m_vrg_source_ip_9;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_0;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_1;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_10;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_11;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_12;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_13;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_14;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_15;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_16;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_2;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_3;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_4;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_5;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_6;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_7;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_8;
  MOD_Reg<tUInt8> INST_m_vrg_source_prio_9;
  MOD_Reg<tUInt8> INST_m_vrg_target_threshold_0;
  MOD_Reg<tUInt8> INST_m_vrg_target_threshold_1;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_0;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_1;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_10;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_11;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_12;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_13;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_14;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_15;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_16;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_2;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_3;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_4;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_5;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_6;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_7;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_8;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_0_9;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_0;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_1;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_10;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_11;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_12;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_13;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_14;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_15;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_16;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_2;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_3;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_4;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_5;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_6;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_7;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_8;
  MOD_Reg<tUInt8> INST_m_vvrg_ie_1_9;
 
 /* Constructor */
 public:
  MOD_mkPLIC_16_CoreNumX2_7(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_axi4_slave_aw_put_val;
  tUWide PORT_axi4_slave_w_put_val;
  tUWide PORT_axi4_slave_ar_put_val;
  tUWide PORT_axi4_slave_r_peek;
  tUInt8 PORT_RDY_v_sources_0_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_1_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_2_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_3_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_4_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_5_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_6_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_7_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_8_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_9_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_10_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_11_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_12_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_13_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_14_m_interrupt_req;
  tUInt8 PORT_RDY_v_sources_15_m_interrupt_req;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_m_slavePortShim_shim_rff_i_notEmpty____d3271;
  tUInt8 DEF_m_slavePortShim_shim_bff_i_notEmpty____d3270;
 
 /* Local definitions */
 private:
  tUInt8 DEF_m_vrg_source_ip_16_read____d119;
  tUInt8 DEF_m_vrg_source_ip_15_read____d118;
  tUInt8 DEF_m_vrg_source_ip_14_read____d117;
  tUInt8 DEF_m_vrg_source_ip_13_read____d116;
  tUInt8 DEF_m_vrg_source_ip_12_read____d115;
  tUInt8 DEF_m_vrg_source_ip_11_read____d114;
  tUInt8 DEF_m_vrg_source_ip_10_read____d113;
  tUInt8 DEF_m_vrg_source_ip_9_read____d112;
  tUInt8 DEF_m_vrg_source_ip_8_read____d111;
  tUInt8 DEF_m_vrg_source_ip_7_read____d110;
  tUInt8 DEF_m_vrg_source_ip_6_read____d109;
  tUInt8 DEF_m_vrg_source_ip_5_read____d108;
  tUInt8 DEF_m_vrg_source_ip_4_read____d107;
  tUInt8 DEF_m_vrg_source_ip_3_read____d106;
  tUInt8 DEF_m_vrg_source_ip_2_read____d105;
  tUInt8 DEF_m_vrg_source_ip_1_read____d104;
  tUInt8 DEF_x__h78315;
  tUInt8 DEF_max_prio__h91410;
  tUInt8 DEF_m_vvrg_ie_1_16__h20604;
  tUInt8 DEF_m_vrg_source_ip_16_read__19_AND_NOT_m_vrg_sour_ETC___d3240;
  tUInt8 DEF_m_vvrg_ie_1_15__h20602;
  tUInt8 DEF_m_vrg_source_ip_15_read__18_AND_NOT_m_vrg_sour_ETC___d3235;
  tUInt8 DEF_m_vvrg_ie_1_14__h20600;
  tUInt8 DEF_m_vrg_source_ip_14_read__17_AND_NOT_m_vrg_sour_ETC___d3230;
  tUInt8 DEF_m_vvrg_ie_1_13__h20598;
  tUInt8 DEF_m_vrg_source_ip_13_read__16_AND_NOT_m_vrg_sour_ETC___d3225;
  tUInt8 DEF_m_vvrg_ie_1_12__h20596;
  tUInt8 DEF_m_vrg_source_ip_12_read__15_AND_NOT_m_vrg_sour_ETC___d3220;
  tUInt8 DEF_m_vvrg_ie_1_11__h20594;
  tUInt8 DEF_m_vrg_source_ip_11_read__14_AND_NOT_m_vrg_sour_ETC___d3215;
  tUInt8 DEF_m_vvrg_ie_1_10__h20592;
  tUInt8 DEF_m_vrg_source_ip_10_read__13_AND_NOT_m_vrg_sour_ETC___d3210;
  tUInt8 DEF_m_vvrg_ie_1_9__h20590;
  tUInt8 DEF_m_vrg_source_ip_9_read__12_AND_NOT_m_vrg_sourc_ETC___d3205;
  tUInt8 DEF_m_vvrg_ie_1_8__h20588;
  tUInt8 DEF_m_vrg_source_ip_8_read__11_AND_NOT_m_vrg_sourc_ETC___d3200;
  tUInt8 DEF_m_vvrg_ie_1_7__h20586;
  tUInt8 DEF_m_vrg_source_ip_7_read__10_AND_NOT_m_vrg_sourc_ETC___d3195;
  tUInt8 DEF_m_vvrg_ie_1_6__h20584;
  tUInt8 DEF_m_vrg_source_ip_6_read__09_AND_NOT_m_vrg_sourc_ETC___d3190;
  tUInt8 DEF_m_vvrg_ie_1_5__h20582;
  tUInt8 DEF_m_vrg_source_ip_5_read__08_AND_NOT_m_vrg_sourc_ETC___d3185;
  tUInt8 DEF_m_vvrg_ie_1_4__h20580;
  tUInt8 DEF_m_vrg_source_ip_4_read__07_AND_NOT_m_vrg_sourc_ETC___d3180;
  tUInt8 DEF_m_vvrg_ie_1_3__h20578;
  tUInt8 DEF_m_vrg_source_ip_3_read__06_AND_NOT_m_vrg_sourc_ETC___d3175;
  tUInt8 DEF_m_vvrg_ie_1_2__h20576;
  tUInt8 DEF_m_vrg_source_ip_2_read__05_AND_NOT_m_vrg_sourc_ETC___d3170;
  tUInt8 DEF_m_vvrg_ie_0_16__h20570;
  tUInt8 DEF_m_vrg_source_ip_16_read__19_AND_NOT_m_vrg_sour_ETC___d3146;
  tUInt8 DEF_m_vvrg_ie_0_15__h20568;
  tUInt8 DEF_m_vrg_source_ip_15_read__18_AND_NOT_m_vrg_sour_ETC___d3141;
  tUInt8 DEF_m_vvrg_ie_0_14__h20566;
  tUInt8 DEF_m_vrg_source_ip_14_read__17_AND_NOT_m_vrg_sour_ETC___d3136;
  tUInt8 DEF_m_vvrg_ie_0_13__h20564;
  tUInt8 DEF_m_vrg_source_ip_13_read__16_AND_NOT_m_vrg_sour_ETC___d3131;
  tUInt8 DEF_m_vvrg_ie_0_12__h20562;
  tUInt8 DEF_m_vrg_source_ip_12_read__15_AND_NOT_m_vrg_sour_ETC___d3126;
  tUInt8 DEF_m_vvrg_ie_0_11__h20560;
  tUInt8 DEF_m_vrg_source_ip_11_read__14_AND_NOT_m_vrg_sour_ETC___d3121;
  tUInt8 DEF_m_vvrg_ie_0_10__h20558;
  tUInt8 DEF_m_vrg_source_ip_10_read__13_AND_NOT_m_vrg_sour_ETC___d3116;
  tUInt8 DEF_m_vvrg_ie_0_9__h20556;
  tUInt8 DEF_m_vrg_source_ip_9_read__12_AND_NOT_m_vrg_sourc_ETC___d3111;
  tUInt8 DEF_m_vvrg_ie_0_8__h20554;
  tUInt8 DEF_m_vrg_source_ip_8_read__11_AND_NOT_m_vrg_sourc_ETC___d3106;
  tUInt8 DEF_m_vvrg_ie_0_7__h20552;
  tUInt8 DEF_m_vrg_source_ip_7_read__10_AND_NOT_m_vrg_sourc_ETC___d3101;
  tUInt8 DEF_m_vvrg_ie_0_6__h20550;
  tUInt8 DEF_m_vrg_source_ip_6_read__09_AND_NOT_m_vrg_sourc_ETC___d3096;
  tUInt8 DEF_m_vvrg_ie_0_5__h20548;
  tUInt8 DEF_m_vrg_source_ip_5_read__08_AND_NOT_m_vrg_sourc_ETC___d3091;
  tUInt8 DEF_m_vvrg_ie_0_4__h20546;
  tUInt8 DEF_m_vrg_source_ip_4_read__07_AND_NOT_m_vrg_sourc_ETC___d3086;
  tUInt8 DEF_m_vvrg_ie_0_3__h20544;
  tUInt8 DEF_m_vrg_source_ip_3_read__06_AND_NOT_m_vrg_sourc_ETC___d3081;
  tUInt8 DEF_m_vvrg_ie_0_2__h20542;
  tUInt8 DEF_m_vrg_source_ip_2_read__05_AND_NOT_m_vrg_sourc_ETC___d3076;
  tUInt32 DEF_v__h89563;
  tUInt32 DEF_v__h89368;
  tUInt32 DEF_v__h89173;
  tUInt32 DEF_v__h88978;
  tUInt32 DEF_v__h88783;
  tUInt32 DEF_v__h88588;
  tUInt32 DEF_v__h88393;
  tUInt32 DEF_v__h88198;
  tUInt32 DEF_v__h88003;
  tUInt32 DEF_v__h87808;
  tUInt32 DEF_v__h87613;
  tUInt32 DEF_v__h87418;
  tUInt32 DEF_v__h87223;
  tUInt32 DEF_v__h87028;
  tUInt32 DEF_v__h86833;
  tUInt32 DEF_v__h86638;
  tUInt32 DEF_v__h85803;
  tUInt32 DEF_v__h85676;
  tUInt32 DEF_v__h85570;
  tUInt32 DEF_v__h78343;
  tUInt32 DEF_v__h78095;
  tUInt32 DEF_v__h77914;
  tUInt32 DEF_v__h77820;
  tUInt32 DEF_v__h77185;
  tUInt32 DEF_v__h76883;
  tUInt32 DEF_v__h28765;
  tUInt32 DEF_v__h28590;
  tUInt32 DEF_v__h27486;
  tUInt32 DEF_v__h27225;
  tUInt32 DEF_v__h26888;
  tUInt32 DEF_v__h26658;
  tUInt32 DEF_v__h26430;
  tUInt32 DEF_v__h24130;
  tUInt32 DEF_v__h18517;
  tUInt32 DEF_v__h14047;
  tUInt32 DEF_v__h13800;
  tUInt32 DEF_v__h13554;
  tUInt32 DEF_v__h13341;
  tUInt32 DEF_v__h5961;
  tUInt32 DEF_signed_1___d3164;
  tUWide DEF_m_slavePortShim_shim_arff_first____d21;
  tUWide DEF_m_slavePortShim_shim_awff_first____d838;
  tUWide DEF_m_slavePortShim_shim_wff_first____d864;
  tUInt64 DEF_y__h27456;
  tUInt8 DEF__read__h4170;
  tUInt8 DEF__read__h4139;
  tUInt8 DEF_max_prio__h92070;
  tUInt8 DEF_max_prio__h92026;
  tUInt8 DEF_max_prio__h91982;
  tUInt8 DEF_max_prio__h91938;
  tUInt8 DEF_max_prio__h91894;
  tUInt8 DEF_max_prio__h91850;
  tUInt8 DEF_max_prio__h91806;
  tUInt8 DEF_max_prio__h91762;
  tUInt8 DEF_max_prio__h91718;
  tUInt8 DEF_max_prio__h91674;
  tUInt8 DEF_max_prio__h91630;
  tUInt8 DEF_max_prio__h91586;
  tUInt8 DEF_max_prio__h91542;
  tUInt8 DEF_max_prio__h91498;
  tUInt8 DEF_max_prio__h91454;
  tUInt8 DEF__read__h3462;
  tUInt8 DEF_m_vvrg_ie_1_1__h20574;
  tUInt8 DEF_m_vvrg_ie_1_0__h20572;
  tUInt8 DEF_m_vvrg_ie_0_1__h20540;
  tUInt8 DEF_m_vvrg_ie_0_0__h20538;
  tUInt8 DEF_m_vrg_source_busy_16__h81056;
  tUInt8 DEF_m_vrg_source_busy_15__h81012;
  tUInt8 DEF_m_vrg_source_busy_14__h80968;
  tUInt8 DEF_m_vrg_source_busy_13__h80924;
  tUInt8 DEF_m_vrg_source_busy_12__h80880;
  tUInt8 DEF_m_vrg_source_busy_11__h80836;
  tUInt8 DEF_m_vrg_source_busy_10__h80792;
  tUInt8 DEF_m_vrg_source_busy_9__h80748;
  tUInt8 DEF_m_vrg_source_busy_8__h80704;
  tUInt8 DEF_m_vrg_source_busy_7__h80660;
  tUInt8 DEF_m_vrg_source_busy_6__h80616;
  tUInt8 DEF_m_vrg_source_busy_5__h80572;
  tUInt8 DEF_m_vrg_source_busy_4__h80528;
  tUInt8 DEF_m_vrg_source_busy_3__h80484;
  tUInt8 DEF_m_vrg_source_busy_2__h80440;
  tUInt8 DEF_m_vrg_source_busy_1__h80396;
  tUInt8 DEF_m_vrg_source_ip_0_read____d103;
  tUInt8 DEF_m_vrg_source_ip_1_read__04_AND_NOT_m_vrg_sourc_ETC___d3165;
  tUInt8 DEF_m_vrg_source_ip_1_read__04_AND_NOT_m_vrg_sourc_ETC___d3071;
  tUInt8 DEF_a__h84219;
  tUInt8 DEF_IF_m_vrg_source_ip_15_read__18_AND_NOT_m_vrg_s_ETC___d3236;
  tUInt8 DEF_IF_m_vrg_source_ip_14_read__17_AND_NOT_m_vrg_s_ETC___d3231;
  tUInt8 DEF_IF_m_vrg_source_ip_13_read__16_AND_NOT_m_vrg_s_ETC___d3226;
  tUInt8 DEF_IF_m_vrg_source_ip_12_read__15_AND_NOT_m_vrg_s_ETC___d3221;
  tUInt8 DEF_IF_m_vrg_source_ip_11_read__14_AND_NOT_m_vrg_s_ETC___d3216;
  tUInt8 DEF_IF_m_vrg_source_ip_10_read__13_AND_NOT_m_vrg_s_ETC___d3211;
  tUInt8 DEF_IF_m_vrg_source_ip_9_read__12_AND_NOT_m_vrg_so_ETC___d3206;
  tUInt8 DEF_IF_m_vrg_source_ip_8_read__11_AND_NOT_m_vrg_so_ETC___d3201;
  tUInt8 DEF_IF_m_vrg_source_ip_7_read__10_AND_NOT_m_vrg_so_ETC___d3196;
  tUInt8 DEF_IF_m_vrg_source_ip_6_read__09_AND_NOT_m_vrg_so_ETC___d3191;
  tUInt8 DEF_IF_m_vrg_source_ip_5_read__08_AND_NOT_m_vrg_so_ETC___d3186;
  tUInt8 DEF_IF_m_vrg_source_ip_4_read__07_AND_NOT_m_vrg_so_ETC___d3181;
  tUInt8 DEF_IF_m_vrg_source_ip_3_read__06_AND_NOT_m_vrg_so_ETC___d3176;
  tUInt8 DEF_IF_m_vrg_source_ip_2_read__05_AND_NOT_m_vrg_so_ETC___d3171;
  tUInt8 DEF_IF_m_vrg_source_ip_1_read__04_AND_NOT_m_vrg_so_ETC___d3166;
  tUInt8 DEF_a__h82065;
  tUInt8 DEF_IF_m_vrg_source_ip_15_read__18_AND_NOT_m_vrg_s_ETC___d3142;
  tUInt8 DEF_IF_m_vrg_source_ip_14_read__17_AND_NOT_m_vrg_s_ETC___d3137;
  tUInt8 DEF_IF_m_vrg_source_ip_13_read__16_AND_NOT_m_vrg_s_ETC___d3132;
  tUInt8 DEF_IF_m_vrg_source_ip_12_read__15_AND_NOT_m_vrg_s_ETC___d3127;
  tUInt8 DEF_IF_m_vrg_source_ip_11_read__14_AND_NOT_m_vrg_s_ETC___d3122;
  tUInt8 DEF_IF_m_vrg_source_ip_10_read__13_AND_NOT_m_vrg_s_ETC___d3117;
  tUInt8 DEF_IF_m_vrg_source_ip_9_read__12_AND_NOT_m_vrg_so_ETC___d3112;
  tUInt8 DEF_IF_m_vrg_source_ip_8_read__11_AND_NOT_m_vrg_so_ETC___d3107;
  tUInt8 DEF_IF_m_vrg_source_ip_7_read__10_AND_NOT_m_vrg_so_ETC___d3102;
  tUInt8 DEF_IF_m_vrg_source_ip_6_read__09_AND_NOT_m_vrg_so_ETC___d3097;
  tUInt8 DEF_IF_m_vrg_source_ip_5_read__08_AND_NOT_m_vrg_so_ETC___d3092;
  tUInt8 DEF_IF_m_vrg_source_ip_4_read__07_AND_NOT_m_vrg_so_ETC___d3087;
  tUInt8 DEF_IF_m_vrg_source_ip_3_read__06_AND_NOT_m_vrg_so_ETC___d3082;
  tUInt8 DEF_IF_m_vrg_source_ip_2_read__05_AND_NOT_m_vrg_so_ETC___d3077;
  tUInt8 DEF_IF_m_vrg_source_ip_1_read__04_AND_NOT_m_vrg_so_ETC___d3072;
  tUWide DEF_m_slavePortShim_shim_arff_first__1_BITS_98_TO__ETC___d812;
  tUInt8 DEF_NOT_m_cfg_verbosity_read_EQ_0___d6;
  tUInt8 DEF_m_vrg_source_ip_1_read__04_AND_NOT_m_vrg_sourc_ETC___d571;
  tUInt8 DEF_NOT_m_cfg_verbosity_read_ULE_1_7___d18;
 
 /* Rules */
 public:
  void RL_m_rl_reset();
  void RL_m_rl_process_rd_req();
  void RL_m_rl_process_wr_req();
 
 /* Methods */
 public:
  void METH_set_verbosity(tUInt8 ARG_set_verbosity_verbosity);
  tUInt8 METH_RDY_set_verbosity();
  void METH_show_PLIC_state();
  tUInt8 METH_RDY_show_PLIC_state();
  void METH_server_reset_request_put(tUInt8 ARG_server_reset_request_put);
  tUInt8 METH_RDY_server_reset_request_put();
  void METH_server_reset_response_get();
  tUInt8 METH_RDY_server_reset_response_get();
  void METH_set_addr_map(tUInt64 ARG_set_addr_map_addr_base, tUInt64 ARG_set_addr_map_addr_lim);
  tUInt8 METH_RDY_set_addr_map();
  tUInt8 METH_axi4_slave_aw_canPut();
  tUInt8 METH_RDY_axi4_slave_aw_canPut();
  void METH_axi4_slave_aw_put(tUWide ARG_axi4_slave_aw_put_val);
  tUInt8 METH_RDY_axi4_slave_aw_put();
  tUInt8 METH_axi4_slave_w_canPut();
  tUInt8 METH_RDY_axi4_slave_w_canPut();
  void METH_axi4_slave_w_put(tUWide ARG_axi4_slave_w_put_val);
  tUInt8 METH_RDY_axi4_slave_w_put();
  tUInt8 METH_axi4_slave_b_canPeek();
  tUInt8 METH_RDY_axi4_slave_b_canPeek();
  tUInt8 METH_axi4_slave_b_peek();
  tUInt8 METH_RDY_axi4_slave_b_peek();
  void METH_axi4_slave_b_drop();
  tUInt8 METH_RDY_axi4_slave_b_drop();
  tUInt8 METH_axi4_slave_ar_canPut();
  tUInt8 METH_RDY_axi4_slave_ar_canPut();
  void METH_axi4_slave_ar_put(tUWide ARG_axi4_slave_ar_put_val);
  tUInt8 METH_RDY_axi4_slave_ar_put();
  tUInt8 METH_axi4_slave_r_canPeek();
  tUInt8 METH_RDY_axi4_slave_r_canPeek();
  tUWide METH_axi4_slave_r_peek();
  tUInt8 METH_RDY_axi4_slave_r_peek();
  void METH_axi4_slave_r_drop();
  tUInt8 METH_RDY_axi4_slave_r_drop();
  void METH_v_sources_0_m_interrupt_req(tUInt8 ARG_v_sources_0_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_0_m_interrupt_req();
  void METH_v_sources_1_m_interrupt_req(tUInt8 ARG_v_sources_1_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_1_m_interrupt_req();
  void METH_v_sources_2_m_interrupt_req(tUInt8 ARG_v_sources_2_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_2_m_interrupt_req();
  void METH_v_sources_3_m_interrupt_req(tUInt8 ARG_v_sources_3_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_3_m_interrupt_req();
  void METH_v_sources_4_m_interrupt_req(tUInt8 ARG_v_sources_4_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_4_m_interrupt_req();
  void METH_v_sources_5_m_interrupt_req(tUInt8 ARG_v_sources_5_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_5_m_interrupt_req();
  void METH_v_sources_6_m_interrupt_req(tUInt8 ARG_v_sources_6_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_6_m_interrupt_req();
  void METH_v_sources_7_m_interrupt_req(tUInt8 ARG_v_sources_7_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_7_m_interrupt_req();
  void METH_v_sources_8_m_interrupt_req(tUInt8 ARG_v_sources_8_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_8_m_interrupt_req();
  void METH_v_sources_9_m_interrupt_req(tUInt8 ARG_v_sources_9_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_9_m_interrupt_req();
  void METH_v_sources_10_m_interrupt_req(tUInt8 ARG_v_sources_10_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_10_m_interrupt_req();
  void METH_v_sources_11_m_interrupt_req(tUInt8 ARG_v_sources_11_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_11_m_interrupt_req();
  void METH_v_sources_12_m_interrupt_req(tUInt8 ARG_v_sources_12_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_12_m_interrupt_req();
  void METH_v_sources_13_m_interrupt_req(tUInt8 ARG_v_sources_13_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_13_m_interrupt_req();
  void METH_v_sources_14_m_interrupt_req(tUInt8 ARG_v_sources_14_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_14_m_interrupt_req();
  void METH_v_sources_15_m_interrupt_req(tUInt8 ARG_v_sources_15_m_interrupt_req_set_not_clear);
  tUInt8 METH_RDY_v_sources_15_m_interrupt_req();
  tUInt8 METH_v_targets_0_m_eip();
  tUInt8 METH_RDY_v_targets_0_m_eip();
  tUInt8 METH_v_targets_1_m_eip();
  tUInt8 METH_RDY_v_targets_1_m_eip();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkPLIC_16_CoreNumX2_7 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkPLIC_16_CoreNumX2_7 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkPLIC_16_CoreNumX2_7 &backing);
};

#endif /* ifndef __mkPLIC_16_CoreNumX2_7_h__ */
