/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkRas_h__
#define __mkRas_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkRas module */
class MOD_mkRas : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_delay;
  MOD_Wire<tUInt8> INST_head_lat_0;
  MOD_Wire<tUInt8> INST_head_lat_1;
  MOD_Wire<tUInt8> INST_head_lat_2;
  MOD_Wire<tUInt8> INST_head_lat_3;
  MOD_Wire<tUInt8> INST_head_lat_4;
  MOD_Reg<tUInt8> INST_head_rl;
  MOD_Wire<tUWide> INST_stack_0_lat_0;
  MOD_Wire<tUWide> INST_stack_0_lat_1;
  MOD_Reg<tUWide> INST_stack_0_rl;
  MOD_Wire<tUWide> INST_stack_10_lat_0;
  MOD_Wire<tUWide> INST_stack_10_lat_1;
  MOD_Reg<tUWide> INST_stack_10_rl;
  MOD_Wire<tUWide> INST_stack_11_lat_0;
  MOD_Wire<tUWide> INST_stack_11_lat_1;
  MOD_Reg<tUWide> INST_stack_11_rl;
  MOD_Wire<tUWide> INST_stack_12_lat_0;
  MOD_Wire<tUWide> INST_stack_12_lat_1;
  MOD_Reg<tUWide> INST_stack_12_rl;
  MOD_Wire<tUWide> INST_stack_13_lat_0;
  MOD_Wire<tUWide> INST_stack_13_lat_1;
  MOD_Reg<tUWide> INST_stack_13_rl;
  MOD_Wire<tUWide> INST_stack_14_lat_0;
  MOD_Wire<tUWide> INST_stack_14_lat_1;
  MOD_Reg<tUWide> INST_stack_14_rl;
  MOD_Wire<tUWide> INST_stack_15_lat_0;
  MOD_Wire<tUWide> INST_stack_15_lat_1;
  MOD_Reg<tUWide> INST_stack_15_rl;
  MOD_Wire<tUWide> INST_stack_1_lat_0;
  MOD_Wire<tUWide> INST_stack_1_lat_1;
  MOD_Reg<tUWide> INST_stack_1_rl;
  MOD_Wire<tUWide> INST_stack_2_lat_0;
  MOD_Wire<tUWide> INST_stack_2_lat_1;
  MOD_Reg<tUWide> INST_stack_2_rl;
  MOD_Wire<tUWide> INST_stack_3_lat_0;
  MOD_Wire<tUWide> INST_stack_3_lat_1;
  MOD_Reg<tUWide> INST_stack_3_rl;
  MOD_Wire<tUWide> INST_stack_4_lat_0;
  MOD_Wire<tUWide> INST_stack_4_lat_1;
  MOD_Reg<tUWide> INST_stack_4_rl;
  MOD_Wire<tUWide> INST_stack_5_lat_0;
  MOD_Wire<tUWide> INST_stack_5_lat_1;
  MOD_Reg<tUWide> INST_stack_5_rl;
  MOD_Wire<tUWide> INST_stack_6_lat_0;
  MOD_Wire<tUWide> INST_stack_6_lat_1;
  MOD_Reg<tUWide> INST_stack_6_rl;
  MOD_Wire<tUWide> INST_stack_7_lat_0;
  MOD_Wire<tUWide> INST_stack_7_lat_1;
  MOD_Reg<tUWide> INST_stack_7_rl;
  MOD_Wire<tUWide> INST_stack_8_lat_0;
  MOD_Wire<tUWide> INST_stack_8_lat_1;
  MOD_Reg<tUWide> INST_stack_8_rl;
  MOD_Wire<tUWide> INST_stack_9_lat_0;
  MOD_Wire<tUWide> INST_stack_9_lat_1;
  MOD_Reg<tUWide> INST_stack_9_rl;
  MOD_Wire<tUInt8> INST_valids_0_lat_0;
  MOD_Wire<tUInt8> INST_valids_0_lat_1;
  MOD_Wire<tUInt8> INST_valids_0_lat_2;
  MOD_Reg<tUInt8> INST_valids_0_rl;
  MOD_Wire<tUInt8> INST_valids_10_lat_0;
  MOD_Wire<tUInt8> INST_valids_10_lat_1;
  MOD_Wire<tUInt8> INST_valids_10_lat_2;
  MOD_Reg<tUInt8> INST_valids_10_rl;
  MOD_Wire<tUInt8> INST_valids_11_lat_0;
  MOD_Wire<tUInt8> INST_valids_11_lat_1;
  MOD_Wire<tUInt8> INST_valids_11_lat_2;
  MOD_Reg<tUInt8> INST_valids_11_rl;
  MOD_Wire<tUInt8> INST_valids_12_lat_0;
  MOD_Wire<tUInt8> INST_valids_12_lat_1;
  MOD_Wire<tUInt8> INST_valids_12_lat_2;
  MOD_Reg<tUInt8> INST_valids_12_rl;
  MOD_Wire<tUInt8> INST_valids_13_lat_0;
  MOD_Wire<tUInt8> INST_valids_13_lat_1;
  MOD_Wire<tUInt8> INST_valids_13_lat_2;
  MOD_Reg<tUInt8> INST_valids_13_rl;
  MOD_Wire<tUInt8> INST_valids_14_lat_0;
  MOD_Wire<tUInt8> INST_valids_14_lat_1;
  MOD_Wire<tUInt8> INST_valids_14_lat_2;
  MOD_Reg<tUInt8> INST_valids_14_rl;
  MOD_Wire<tUInt8> INST_valids_15_lat_0;
  MOD_Wire<tUInt8> INST_valids_15_lat_1;
  MOD_Wire<tUInt8> INST_valids_15_lat_2;
  MOD_Reg<tUInt8> INST_valids_15_rl;
  MOD_Wire<tUInt8> INST_valids_1_lat_0;
  MOD_Wire<tUInt8> INST_valids_1_lat_1;
  MOD_Wire<tUInt8> INST_valids_1_lat_2;
  MOD_Reg<tUInt8> INST_valids_1_rl;
  MOD_Wire<tUInt8> INST_valids_2_lat_0;
  MOD_Wire<tUInt8> INST_valids_2_lat_1;
  MOD_Wire<tUInt8> INST_valids_2_lat_2;
  MOD_Reg<tUInt8> INST_valids_2_rl;
  MOD_Wire<tUInt8> INST_valids_3_lat_0;
  MOD_Wire<tUInt8> INST_valids_3_lat_1;
  MOD_Wire<tUInt8> INST_valids_3_lat_2;
  MOD_Reg<tUInt8> INST_valids_3_rl;
  MOD_Wire<tUInt8> INST_valids_4_lat_0;
  MOD_Wire<tUInt8> INST_valids_4_lat_1;
  MOD_Wire<tUInt8> INST_valids_4_lat_2;
  MOD_Reg<tUInt8> INST_valids_4_rl;
  MOD_Wire<tUInt8> INST_valids_5_lat_0;
  MOD_Wire<tUInt8> INST_valids_5_lat_1;
  MOD_Wire<tUInt8> INST_valids_5_lat_2;
  MOD_Reg<tUInt8> INST_valids_5_rl;
  MOD_Wire<tUInt8> INST_valids_6_lat_0;
  MOD_Wire<tUInt8> INST_valids_6_lat_1;
  MOD_Wire<tUInt8> INST_valids_6_lat_2;
  MOD_Reg<tUInt8> INST_valids_6_rl;
  MOD_Wire<tUInt8> INST_valids_7_lat_0;
  MOD_Wire<tUInt8> INST_valids_7_lat_1;
  MOD_Wire<tUInt8> INST_valids_7_lat_2;
  MOD_Reg<tUInt8> INST_valids_7_rl;
  MOD_Wire<tUInt8> INST_valids_8_lat_0;
  MOD_Wire<tUInt8> INST_valids_8_lat_1;
  MOD_Wire<tUInt8> INST_valids_8_lat_2;
  MOD_Reg<tUInt8> INST_valids_8_rl;
  MOD_Wire<tUInt8> INST_valids_9_lat_0;
  MOD_Wire<tUInt8> INST_valids_9_lat_1;
  MOD_Wire<tUInt8> INST_valids_9_lat_2;
  MOD_Reg<tUInt8> INST_valids_9_rl;
 
 /* Constructor */
 public:
  MOD_mkRas(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_write_pushAddr;
  tUWide PORT_push_pushAddr;
  tUWide PORT_ras_0_first;
  tUWide PORT_ras_1_first;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_upd__h18862;
  tUInt8 DEF_SEL_ARR_NOT_valids_0_rl_51_28_NOT_valids_1_rl__ETC___d345;
  tUWide DEF_n__read__h18411;
  tUWide DEF_x_wget__h5929;
  tUWide DEF_x_wget__h5883;
  tUWide DEF_n__read__h18409;
  tUWide DEF_x_wget__h5591;
  tUWide DEF_x_wget__h5545;
  tUWide DEF_n__read__h18407;
  tUWide DEF_x_wget__h5253;
  tUWide DEF_x_wget__h5207;
  tUWide DEF_n__read__h18405;
  tUWide DEF_x_wget__h4915;
  tUWide DEF_x_wget__h4869;
  tUWide DEF_n__read__h18403;
  tUWide DEF_x_wget__h4577;
  tUWide DEF_x_wget__h4531;
  tUWide DEF_n__read__h18401;
  tUWide DEF_x_wget__h4239;
  tUWide DEF_x_wget__h4193;
  tUWide DEF_n__read__h18399;
  tUWide DEF_x_wget__h3901;
  tUWide DEF_x_wget__h3855;
  tUWide DEF_n__read__h18397;
  tUWide DEF_x_wget__h3563;
  tUWide DEF_x_wget__h3517;
  tUWide DEF_n__read__h18395;
  tUWide DEF_x_wget__h3225;
  tUWide DEF_x_wget__h3179;
  tUWide DEF_n__read__h18393;
  tUWide DEF_x_wget__h2887;
  tUWide DEF_x_wget__h2841;
  tUWide DEF_n__read__h18391;
  tUWide DEF_x_wget__h2549;
  tUWide DEF_x_wget__h2503;
  tUWide DEF_n__read__h18389;
  tUWide DEF_x_wget__h2211;
  tUWide DEF_x_wget__h2165;
  tUWide DEF_n__read__h18387;
  tUWide DEF_x_wget__h1873;
  tUWide DEF_x_wget__h1827;
  tUWide DEF_n__read__h18385;
  tUWide DEF_x_wget__h1535;
  tUWide DEF_x_wget__h1489;
  tUWide DEF_n__read__h18383;
  tUWide DEF_x_wget__h1197;
  tUWide DEF_x_wget__h1151;
  tUWide DEF_n__read__h18381;
  tUWide DEF_x_wget__h679;
  tUWide DEF_x_wget__h630;
  tUInt8 DEF_x_wget__h14660;
  tUInt8 DEF_x_wget__h14611;
  tUInt8 DEF_x_wget__h14562;
  tUInt8 DEF_x_wget__h14513;
  tUInt8 DEF_valids_15_rl__h16771;
  tUInt8 DEF_valids_14_rl__h16770;
  tUInt8 DEF_valids_13_rl__h16769;
  tUInt8 DEF_valids_12_rl__h16768;
  tUInt8 DEF_valids_11_rl__h16767;
  tUInt8 DEF_valids_10_rl__h16766;
  tUInt8 DEF_valids_9_rl__h16765;
  tUInt8 DEF_valids_8_rl__h16764;
  tUInt8 DEF_valids_7_rl__h16763;
  tUInt8 DEF_valids_6_rl__h16762;
  tUInt8 DEF_valids_5_rl__h16761;
  tUInt8 DEF_valids_4_rl__h16760;
  tUInt8 DEF_valids_3_rl__h16759;
  tUInt8 DEF_valids_2_rl__h16758;
  tUInt8 DEF_valids_1_rl__h16757;
  tUInt8 DEF_valids_0_rl__h16756;
  tUWide DEF_SEL_ARR_stack_0_rl_stack_1_rl_6_stack_2_rl_5_s_ETC___d385;
  tUWide DEF_IF_stack_15_lat_0_whas__39_THEN_IF_stack_15_la_ETC___d143;
  tUWide DEF_upd__h6142;
  tUWide DEF_x__h6001;
  tUWide DEF_upd__h6115;
  tUWide DEF_IF_stack_14_lat_0_whas__30_THEN_IF_stack_14_la_ETC___d134;
  tUWide DEF_upd__h5804;
  tUWide DEF_x__h5663;
  tUWide DEF_upd__h5777;
  tUWide DEF_IF_stack_13_lat_0_whas__21_THEN_IF_stack_13_la_ETC___d125;
  tUWide DEF_upd__h5466;
  tUWide DEF_x__h5325;
  tUWide DEF_upd__h5439;
  tUWide DEF_IF_stack_12_lat_0_whas__12_THEN_IF_stack_12_la_ETC___d116;
  tUWide DEF_upd__h5128;
  tUWide DEF_x__h4987;
  tUWide DEF_upd__h5101;
  tUWide DEF_IF_stack_11_lat_0_whas__03_THEN_IF_stack_11_la_ETC___d107;
  tUWide DEF_upd__h4790;
  tUWide DEF_x__h4649;
  tUWide DEF_upd__h4763;
  tUWide DEF_IF_stack_10_lat_0_whas__4_THEN_IF_stack_10_lat_ETC___d98;
  tUWide DEF_upd__h4452;
  tUWide DEF_x__h4311;
  tUWide DEF_upd__h4425;
  tUWide DEF_IF_stack_9_lat_0_whas__5_THEN_IF_stack_9_lat_0_ETC___d89;
  tUWide DEF_upd__h4114;
  tUWide DEF_x__h3973;
  tUWide DEF_upd__h4087;
  tUWide DEF_IF_stack_8_lat_0_whas__6_THEN_IF_stack_8_lat_0_ETC___d80;
  tUWide DEF_upd__h3776;
  tUWide DEF_x__h3635;
  tUWide DEF_upd__h3749;
  tUWide DEF_IF_stack_7_lat_0_whas__7_THEN_IF_stack_7_lat_0_ETC___d71;
  tUWide DEF_upd__h3438;
  tUWide DEF_x__h3297;
  tUWide DEF_upd__h3411;
  tUWide DEF_IF_stack_6_lat_0_whas__8_THEN_IF_stack_6_lat_0_ETC___d62;
  tUWide DEF_upd__h3100;
  tUWide DEF_x__h2959;
  tUWide DEF_upd__h3073;
  tUWide DEF_IF_stack_5_lat_0_whas__9_THEN_IF_stack_5_lat_0_ETC___d53;
  tUWide DEF_upd__h2762;
  tUWide DEF_x__h2621;
  tUWide DEF_upd__h2735;
  tUWide DEF_IF_stack_4_lat_0_whas__0_THEN_IF_stack_4_lat_0_ETC___d44;
  tUWide DEF_upd__h2424;
  tUWide DEF_x__h2283;
  tUWide DEF_upd__h2397;
  tUWide DEF_IF_stack_3_lat_0_whas__1_THEN_IF_stack_3_lat_0_ETC___d35;
  tUWide DEF_upd__h2086;
  tUWide DEF_x__h1945;
  tUWide DEF_upd__h2059;
  tUWide DEF_IF_stack_2_lat_0_whas__2_THEN_IF_stack_2_lat_0_ETC___d26;
  tUWide DEF_upd__h1748;
  tUWide DEF_x__h1607;
  tUWide DEF_upd__h1721;
  tUWide DEF_IF_stack_1_lat_0_whas__3_THEN_IF_stack_1_lat_0_ETC___d17;
  tUWide DEF_upd__h1410;
  tUWide DEF_x__h1269;
  tUWide DEF_upd__h1383;
  tUWide DEF_x__h931;
  tUWide DEF_upd__h1045;
  tUWide DEF_IF_stack_0_lat_0_whas_THEN_IF_stack_0_lat_0_wh_ETC___d8;
  tUWide DEF_upd__h1072;
  tUInt8 DEF_IF_head_lat_0_whas__17_THEN_IF_head_lat_0_whas_ETC___d321;
  tUInt8 DEF_upd__h15119;
  tUInt8 DEF_upd__h15092;
  tUInt8 DEF_upd__h15065;
  tUInt8 DEF_IF_head_lat_3_whas__08_THEN_IF_head_lat_3_whas_ETC___d324;
  tUInt8 DEF_upd__h15038;
 
 /* Rules */
 public:
  void RL_stack_0_canon();
  void RL_stack_1_canon();
  void RL_stack_2_canon();
  void RL_stack_3_canon();
  void RL_stack_4_canon();
  void RL_stack_5_canon();
  void RL_stack_6_canon();
  void RL_stack_7_canon();
  void RL_stack_8_canon();
  void RL_stack_9_canon();
  void RL_stack_10_canon();
  void RL_stack_11_canon();
  void RL_stack_12_canon();
  void RL_stack_13_canon();
  void RL_stack_14_canon();
  void RL_stack_15_canon();
  void RL_valids_0_canon();
  void RL_valids_1_canon();
  void RL_valids_2_canon();
  void RL_valids_3_canon();
  void RL_valids_4_canon();
  void RL_valids_5_canon();
  void RL_valids_6_canon();
  void RL_valids_7_canon();
  void RL_valids_8_canon();
  void RL_valids_9_canon();
  void RL_valids_10_canon();
  void RL_valids_11_canon();
  void RL_valids_12_canon();
  void RL_valids_13_canon();
  void RL_valids_14_canon();
  void RL_valids_15_canon();
  void RL_head_canon();
  void RL_resetValidHead();
 
 /* Methods */
 public:
  tUInt8 METH_flush_done();
  tUInt8 METH_RDY_flush_done();
  tUWide METH_ras_0_first();
  tUInt8 METH_RDY_ras_0_first();
  tUInt8 METH_ras_0_pop(tUInt8 ARG_ras_0_pop_doPop);
  tUInt8 METH_RDY_ras_0_pop();
  tUWide METH_ras_1_first();
  tUInt8 METH_RDY_ras_1_first();
  tUInt8 METH_ras_1_pop(tUInt8 ARG_ras_1_pop_doPop);
  tUInt8 METH_RDY_ras_1_pop();
  tUInt8 METH_pendingPush();
  tUInt8 METH_RDY_pendingPush();
  void METH_push(tUWide ARG_push_pushAddr);
  tUInt8 METH_RDY_push();
  void METH_write(tUWide ARG_write_pushAddr, tUInt8 ARG_write_h);
  tUInt8 METH_RDY_write();
  void METH_setHead(tUInt8 ARG_setHead_h);
  tUInt8 METH_RDY_setHead();
  void METH_flush();
  tUInt8 METH_RDY_flush();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkRas &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkRas &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkRas &backing);
};

#endif /* ifndef __mkRas_h__ */
