/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkRobRowSynth_h__
#define __mkRobRowSynth_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkRobRowSynth module */
class MOD_mkRobRowSynth : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_m_claimed_phy_reg;
  MOD_Reg<tUInt32> INST_m_csr;
  MOD_Reg<tUInt8> INST_m_epochIncremented;
  MOD_Wire<tUInt8> INST_m_fflags_lat_0;
  MOD_Wire<tUInt8> INST_m_fflags_lat_1;
  MOD_Reg<tUInt8> INST_m_fflags_rl;
  MOD_Reg<tUInt8> INST_m_iType;
  MOD_Wire<tUInt8> INST_m_ldKilled_lat_0;
  MOD_Wire<tUInt8> INST_m_ldKilled_lat_1;
  MOD_Reg<tUInt8> INST_m_ldKilled_rl;
  MOD_Wire<tUInt8> INST_m_lsqAtCommitNotified_lat_0;
  MOD_Wire<tUInt8> INST_m_lsqAtCommitNotified_lat_1;
  MOD_Reg<tUInt8> INST_m_lsqAtCommitNotified_rl;
  MOD_Reg<tUInt8> INST_m_lsqTag;
  MOD_Wire<tUInt8> INST_m_memAccessAtCommit_lat_0;
  MOD_Wire<tUInt8> INST_m_memAccessAtCommit_lat_1;
  MOD_Wire<tUInt8> INST_m_memAccessAtCommit_lat_2;
  MOD_Reg<tUInt8> INST_m_memAccessAtCommit_rl;
  MOD_Wire<tUInt8> INST_m_nonMMIOStDone_lat_0;
  MOD_Wire<tUInt8> INST_m_nonMMIOStDone_lat_1;
  MOD_Reg<tUInt8> INST_m_nonMMIOStDone_rl;
  MOD_Reg<tUInt32> INST_m_orig_inst;
  MOD_Reg<tUWide> INST_m_pc;
  MOD_Wire<tUWide> INST_m_ppc_vaddr_csrData_lat_0;
  MOD_Wire<tUWide> INST_m_ppc_vaddr_csrData_lat_1;
  MOD_Wire<tUWide> INST_m_ppc_vaddr_csrData_lat_2;
  MOD_Wire<tUWide> INST_m_ppc_vaddr_csrData_lat_3;
  MOD_Reg<tUWide> INST_m_ppc_vaddr_csrData_rl;
  MOD_Wire<tUWide> INST_m_predPcWire;
  MOD_Reg<tUInt8> INST_m_rg_dst_reg;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_0;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_1;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_2;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_3;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_4;
  MOD_Wire<tUInt8> INST_m_rob_inst_state_lat_5;
  MOD_Reg<tUInt8> INST_m_rob_inst_state_rl;
  MOD_Reg<tUInt8> INST_m_scr;
  MOD_Wire<tUInt32> INST_m_spec_bits_lat_0;
  MOD_Wire<tUInt32> INST_m_spec_bits_lat_1;
  MOD_Wire<tUInt32> INST_m_spec_bits_lat_2;
  MOD_Reg<tUInt32> INST_m_spec_bits_rl;
  MOD_Wire<tUInt32> INST_m_trap_lat_0;
  MOD_Wire<tUInt32> INST_m_trap_lat_1;
  MOD_Wire<tUInt32> INST_m_trap_lat_2;
  MOD_Wire<tUInt32> INST_m_trap_lat_3;
  MOD_Reg<tUInt32> INST_m_trap_rl;
  MOD_Reg<tUInt8> INST_m_will_dirty_fpu_state;
 
 /* Constructor */
 public:
  MOD_mkRobRowSynth(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_setExecuted_doFinishAlu_0_set_csrData;
  tUWide PORT_setExecuted_doFinishAlu_1_set_csrData;
  tUWide PORT_write_enq_x;
  tUWide PORT_getOrigPredPC;
  tUWide PORT_getOrigPC;
  tUWide PORT_read_deq;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_m_ppc_vaddr_csrData_rl___d154;
  tUWide DEF_m_ppc_vaddr_csrData_lat_3_wget____d119;
  tUWide DEF_m_ppc_vaddr_csrData_lat_2_wget____d128;
  tUWide DEF_m_ppc_vaddr_csrData_lat_1_wget____d137;
  tUWide DEF_m_ppc_vaddr_csrData_lat_0_wget____d146;
  tUWide DEF_x_read_deq_pc__h10454;
  tUInt32 DEF_x_read_deq_orig_inst__h10455;
  tUInt32 DEF_m_trap_rl___d13;
  tUInt32 DEF_m_csr___d341;
  tUInt32 DEF_upd__h13568;
  tUInt32 DEF_x_wget__h7239;
  tUInt32 DEF_x_wget__h7190;
  tUInt8 DEF_m_scr___d340;
  tUInt8 DEF_x_read_deq_fflags__h10463;
  tUInt8 DEF_m_iType__h10476;
  tUInt8 DEF_m_ldKilled_rl___d267;
  tUInt8 DEF_m_nonMMIOStDone_rl__h6962;
  tUInt8 DEF_m_lsqAtCommitNotified_rl__h6496;
  tUInt8 DEF_m_memAccessAtCommit_rl__h6022;
  tUInt8 DEF_m_rob_inst_state_rl__h4736;
  tUWide DEF_write_enq_x_BITS_162_TO_32___d322;
  tUWide DEF_x__h3103;
  tUWide DEF_x__h3096;
  tUWide DEF_x__h3089;
  tUWide DEF_x__h3082;
  tUWide DEF_x__h3075;
  tUWide DEF_x__h8039;
  tUInt8 DEF_m_ppc_vaddr_csrData_rl_54_BITS_130_TO_129___d155;
  tUWide DEF_IF_setExecuted_doFinishAlu_1_set_csrData_BITS__ETC___d377;
  tUWide DEF_IF_write_enq_x_BITS_162_TO_161_16_EQ_0_17_OR_w_ETC___d323;
  tUWide DEF_IF_setExecuted_doFinishAlu_0_set_csrData_BITS__ETC___d361;
  tUWide DEF_IF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN__ETC___d233;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN_IF__ETC___d183;
  tUWide DEF_IF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN__ETC___d232;
  tUWide DEF_DONTCARE_CONCAT_IF_m_ppc_vaddr_csrData_lat_3_w_ETC___d207;
  tUWide DEF_IF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN__ETC___d231;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN_IF__ETC___d230;
  tUWide DEF_IF_m_ppc_vaddr_csrData_rl_54_BITS_130_TO_129_5_ETC___d226;
  tUWide DEF_IF_m_ppc_vaddr_csrData_rl_54_BITS_130_TO_129_5_ETC___d225;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_0_wget__46_BITS_130_ETC___d223;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_0_wget__46_BITS_130_ETC___d222;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_1_wget__37_BITS_130_ETC___d220;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_1_wget__37_BITS_130_ETC___d219;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_2_wget__28_BITS_130_ETC___d217;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_2_wget__28_BITS_130_ETC___d216;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_wget__19_BITS_130_ETC___d214;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_wget__19_BITS_130_ETC___d213;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_wget__19_BITS_130_ETC___d171;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_2_whas__27_THEN_IF__ETC___d182;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_2_whas__27_THEN_IF__ETC___d229;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_2_wget__28_BITS_130_ETC___d173;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_1_whas__36_THEN_IF__ETC___d181;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_1_whas__36_THEN_IF__ETC___d228;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_1_wget__37_BITS_130_ETC___d175;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_0_whas__45_THEN_IF__ETC___d180;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_0_whas__45_THEN_IF__ETC___d227;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_0_wget__46_BITS_130_ETC___d177;
  tUWide DEF_IF_m_ppc_vaddr_csrData_rl_54_BITS_130_TO_129_5_ETC___d179;
  tUWide DEF_x1__h7686;
  tUInt8 DEF_m_ppc_vaddr_csrData_rl_54_BITS_130_TO_129_55_EQ_0___d156;
  tUInt32 DEF_upd__h7573;
  tUInt32 DEF_IF_m_spec_bits_lat_1_whas__97_THEN_IF_m_spec_b_ETC___d305;
  tUInt32 DEF_upd__h7546;
  tUWide DEF_m_iType_38_CONCAT_m_rg_dst_reg_39_CONCAT_m_scr_ETC___d353;
  tUWide DEF_m_scr_40_CONCAT_m_csr_41_CONCAT_m_claimed_phy__ETC___d352;
  tUWide DEF_m_claimed_phy_reg_42_CONCAT_m_trap_rl_3_CONCAT_ETC___d351;
  tUWide DEF_m_ppc_vaddr_csrData_rl_54_CONCAT_m_fflags_rl_4_ETC___d350;
  tUWide DEF__1_CONCAT_DONTCARE_CONCAT_setExecuted_doFinishM_ETC___d386;
  tUWide DEF_IF_m_ppc_vaddr_csrData_lat_3_whas__18_THEN_IF__ETC___d234;
  tUInt8 DEF_NOT_m_csr_41_BIT_12_65_66_AND_NOT_m_scr_40_BIT_ETC___d369;
 
 /* Rules */
 public:
  void RL_m_trap_canon();
  void RL_m_ppc_vaddr_csrData_canon();
  void RL_m_fflags_canon();
  void RL_m_rob_inst_state_canon();
  void RL_m_ldKilled_canon();
  void RL_m_memAccessAtCommit_canon();
  void RL_m_lsqAtCommitNotified_canon();
  void RL_m_nonMMIOStDone_canon();
  void RL_m_spec_bits_canon();
  void RL_m_setPcWires();
 
 /* Methods */
 public:
  void METH_write_enq(tUWide ARG_write_enq_x);
  tUInt8 METH_RDY_write_enq();
  tUWide METH_read_deq();
  tUInt8 METH_RDY_read_deq();
  void METH_setLSQAtCommitNotified();
  tUInt8 METH_RDY_setLSQAtCommitNotified();
  void METH_setExecuted_deqLSQ(tUInt32 ARG_setExecuted_deqLSQ_cause,
			       tUInt8 ARG_setExecuted_deqLSQ_ld_killed);
  tUInt8 METH_RDY_setExecuted_deqLSQ();
  void METH_setExecuted_doFinishAlu_0_set(tUWide ARG_setExecuted_doFinishAlu_0_set_csrData,
					  tUInt32 ARG_setExecuted_doFinishAlu_0_set_cause);
  tUInt8 METH_RDY_setExecuted_doFinishAlu_0_set();
  void METH_setExecuted_doFinishAlu_1_set(tUWide ARG_setExecuted_doFinishAlu_1_set_csrData,
					  tUInt32 ARG_setExecuted_doFinishAlu_1_set_cause);
  tUInt8 METH_RDY_setExecuted_doFinishAlu_1_set();
  void METH_setExecuted_doFinishFpuMulDiv_0_set(tUInt8 ARG_setExecuted_doFinishFpuMulDiv_0_set_fflags);
  tUInt8 METH_RDY_setExecuted_doFinishFpuMulDiv_0_set();
  void METH_setExecuted_doFinishMem(tUInt64 ARG_setExecuted_doFinishMem_vaddr,
				    tUInt8 ARG_setExecuted_doFinishMem_access_at_commit,
				    tUInt8 ARG_setExecuted_doFinishMem_non_mmio_st_done);
  tUInt8 METH_RDY_setExecuted_doFinishMem();
  tUWide METH_getOrigPC();
  tUInt8 METH_RDY_getOrigPC();
  tUWide METH_getOrigPredPC();
  tUInt8 METH_RDY_getOrigPredPC();
  tUInt32 METH_getOrig_Inst();
  tUInt8 METH_RDY_getOrig_Inst();
  tUInt8 METH_dependsOn_wrongSpec(tUInt8 ARG_dependsOn_wrongSpec_tag);
  tUInt8 METH_RDY_dependsOn_wrongSpec();
  void METH_correctSpeculation(tUInt32 ARG_correctSpeculation_mask);
  tUInt8 METH_RDY_correctSpeculation();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkRobRowSynth &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkRobRowSynth &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkRobRowSynth &backing);
};

#endif /* ifndef __mkRobRowSynth_h__ */
