/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkSimpleRespQ_h__
#define __mkSimpleRespQ_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkSimpleRespQ module */
class MOD_mkSimpleRespQ : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_m_m_deqP_ehr_lat_0;
  MOD_Wire<tUInt8> INST_m_m_deqP_ehr_lat_1;
  MOD_Reg<tUInt8> INST_m_m_deqP_ehr_rl;
  MOD_Wire<tUInt8> INST_m_m_deqP_for_enq_wire;
  MOD_Wire<tUInt8> INST_m_m_empty_for_enq_wire;
  MOD_Reg<tUInt8> INST_m_m_enqP;
  MOD_Reg<tUWide> INST_m_m_row_0;
  MOD_Reg<tUWide> INST_m_m_row_1;
  MOD_Wire<tUInt32> INST_m_m_specBits_0_lat_0;
  MOD_Wire<tUInt32> INST_m_m_specBits_0_lat_1;
  MOD_Reg<tUInt32> INST_m_m_specBits_0_rl;
  MOD_Wire<tUInt32> INST_m_m_specBits_1_lat_0;
  MOD_Wire<tUInt32> INST_m_m_specBits_1_lat_1;
  MOD_Reg<tUInt32> INST_m_m_specBits_1_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_0_lat_0;
  MOD_Wire<tUInt8> INST_m_m_valid_0_lat_1;
  MOD_Reg<tUInt8> INST_m_m_valid_0_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_1_lat_0;
  MOD_Wire<tUInt8> INST_m_m_valid_1_lat_1;
  MOD_Reg<tUInt8> INST_m_m_valid_1_rl;
  MOD_Wire<tUInt8> INST_m_m_valid_for_enq_wire;
  MOD_Wire<tUInt8> INST_m_m_wrongSpec_canon_conflict;
  MOD_Wire<tUInt8> INST_m_m_wrongSpec_deq_conflict;
  MOD_Wire<tUInt8> INST_m_m_wrongSpec_enq_conflict;
 
 /* Constructor */
 public:
  MOD_mkSimpleRespQ(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_enq_x;
  tUWide PORT_first;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_SEL_ARR_m_m_valid_0_rl_m_m_valid_1_rl_2_9_m_m__ETC___d78;
  tUInt8 DEF_m_m_empty_for_enq_wire_wget__9_OR_NOT_m_m_enqP_ETC___d73;
  tUInt8 DEF_m_m_valid_0_rl__h3543;
  tUInt8 DEF_x__h4243;
  tUInt8 DEF_m_m_valid_1_rl__h3114;
  tUInt8 DEF_deqP_for_enq__h3631;
  tUInt8 DEF_x__h4839;
  tUInt8 DEF_NOT_m_m_valid_0_rl___d42;
  tUInt8 DEF_NOT_m_m_valid_1_rl_2___d43;
 
 /* Local definitions */
 private:
  tUWide DEF_m_m_row_1___d83;
  tUWide DEF_m_m_row_0___d81;
  tUInt32 DEF_upd__h5605;
  tUInt32 DEF_x_wget__h1697;
  tUInt32 DEF_upd__h5496;
  tUInt32 DEF_x_wget__h1349;
  tUWide DEF_enq_x_BITS_101_TO_12___d67;
  tUInt32 DEF_IF_m_m_specBits_1_lat_0_whas__7_THEN_IF_m_m_sp_ETC___d31;
  tUInt32 DEF_upd__h1956;
  tUInt32 DEF_IF_m_m_specBits_0_lat_0_whas__8_THEN_IF_m_m_sp_ETC___d22;
  tUInt32 DEF_upd__h1618;
  tUInt8 DEF_x__h4537;
  tUWide DEF_SEL_ARR_m_m_row_0_1_BITS_89_TO_26_2_m_m_row_1__ETC___d91;
 
 /* Rules */
 public:
  void RL_m_m_valid_0_canon();
  void RL_m_m_valid_1_canon();
  void RL_m_m_specBits_0_canon();
  void RL_m_m_specBits_1_canon();
  void RL_m_m_deqP_ehr_canon();
  void RL_m_m_canon_deqP();
  void RL_m_m_setWireForEnq();
 
 /* Methods */
 public:
  void METH_enq(tUWide ARG_enq_x);
  tUInt8 METH_RDY_enq();
  tUInt8 METH_notFull();
  tUInt8 METH_RDY_notFull();
  void METH_deq();
  tUInt8 METH_RDY_deq();
  tUWide METH_first();
  tUInt8 METH_RDY_first();
  tUInt8 METH_notEmpty();
  tUInt8 METH_RDY_notEmpty();
  void METH_specUpdate_incorrectSpeculation(tUInt8 ARG_specUpdate_incorrectSpeculation_kill_all,
					    tUInt8 ARG_specUpdate_incorrectSpeculation_kill_tag);
  tUInt8 METH_RDY_specUpdate_incorrectSpeculation();
  void METH_specUpdate_correctSpeculation(tUInt32 ARG_specUpdate_correctSpeculation_mask);
  tUInt8 METH_RDY_specUpdate_correctSpeculation();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSimpleRespQ &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkSimpleRespQ &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkSimpleRespQ &backing);
};

#endif /* ifndef __mkSimpleRespQ_h__ */
