/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkSplitTransCache_h__
#define __mkSplitTransCache_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkSplitTransCache module */
class MOD_mkSplitTransCache : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_caches_0_flushEn;
  MOD_Wire<tUInt32> INST_caches_0_lruBit_lat_0;
  MOD_Wire<tUInt32> INST_caches_0_lruBit_lat_1;
  MOD_Reg<tUInt32> INST_caches_0_lruBit_rl;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_0;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_1;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_10;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_11;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_12;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_13;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_14;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_15;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_16;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_17;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_18;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_19;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_2;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_20;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_21;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_22;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_23;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_3;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_4;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_5;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_6;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_7;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_8;
  MOD_Reg<tUInt64> INST_caches_0_ppnVec_9;
  MOD_Reg<tUInt8> INST_caches_0_randIdx;
  MOD_Wire<tUInt8> INST_caches_0_updRepIdx_lat_0;
  MOD_Wire<tUInt8> INST_caches_0_updRepIdx_lat_1;
  MOD_Reg<tUInt8> INST_caches_0_updRepIdx_rl;
  MOD_Reg<tUInt8> INST_caches_0_validVec_0;
  MOD_Reg<tUInt8> INST_caches_0_validVec_1;
  MOD_Reg<tUInt8> INST_caches_0_validVec_10;
  MOD_Reg<tUInt8> INST_caches_0_validVec_11;
  MOD_Reg<tUInt8> INST_caches_0_validVec_12;
  MOD_Reg<tUInt8> INST_caches_0_validVec_13;
  MOD_Reg<tUInt8> INST_caches_0_validVec_14;
  MOD_Reg<tUInt8> INST_caches_0_validVec_15;
  MOD_Reg<tUInt8> INST_caches_0_validVec_16;
  MOD_Reg<tUInt8> INST_caches_0_validVec_17;
  MOD_Reg<tUInt8> INST_caches_0_validVec_18;
  MOD_Reg<tUInt8> INST_caches_0_validVec_19;
  MOD_Reg<tUInt8> INST_caches_0_validVec_2;
  MOD_Reg<tUInt8> INST_caches_0_validVec_20;
  MOD_Reg<tUInt8> INST_caches_0_validVec_21;
  MOD_Reg<tUInt8> INST_caches_0_validVec_22;
  MOD_Reg<tUInt8> INST_caches_0_validVec_23;
  MOD_Reg<tUInt8> INST_caches_0_validVec_3;
  MOD_Reg<tUInt8> INST_caches_0_validVec_4;
  MOD_Reg<tUInt8> INST_caches_0_validVec_5;
  MOD_Reg<tUInt8> INST_caches_0_validVec_6;
  MOD_Reg<tUInt8> INST_caches_0_validVec_7;
  MOD_Reg<tUInt8> INST_caches_0_validVec_8;
  MOD_Reg<tUInt8> INST_caches_0_validVec_9;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_0;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_1;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_10;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_11;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_12;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_13;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_14;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_15;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_16;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_17;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_18;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_19;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_2;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_20;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_21;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_22;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_23;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_3;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_4;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_5;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_6;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_7;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_8;
  MOD_Reg<tUInt32> INST_caches_0_vpnVec_9;
  MOD_Wire<tUInt8> INST_caches_1_flushEn;
  MOD_Wire<tUInt32> INST_caches_1_lruBit_lat_0;
  MOD_Wire<tUInt32> INST_caches_1_lruBit_lat_1;
  MOD_Reg<tUInt32> INST_caches_1_lruBit_rl;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_0;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_1;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_10;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_11;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_12;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_13;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_14;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_15;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_16;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_17;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_18;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_19;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_2;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_20;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_21;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_22;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_23;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_3;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_4;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_5;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_6;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_7;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_8;
  MOD_Reg<tUInt64> INST_caches_1_ppnVec_9;
  MOD_Reg<tUInt8> INST_caches_1_randIdx;
  MOD_Wire<tUInt8> INST_caches_1_updRepIdx_lat_0;
  MOD_Wire<tUInt8> INST_caches_1_updRepIdx_lat_1;
  MOD_Reg<tUInt8> INST_caches_1_updRepIdx_rl;
  MOD_Reg<tUInt8> INST_caches_1_validVec_0;
  MOD_Reg<tUInt8> INST_caches_1_validVec_1;
  MOD_Reg<tUInt8> INST_caches_1_validVec_10;
  MOD_Reg<tUInt8> INST_caches_1_validVec_11;
  MOD_Reg<tUInt8> INST_caches_1_validVec_12;
  MOD_Reg<tUInt8> INST_caches_1_validVec_13;
  MOD_Reg<tUInt8> INST_caches_1_validVec_14;
  MOD_Reg<tUInt8> INST_caches_1_validVec_15;
  MOD_Reg<tUInt8> INST_caches_1_validVec_16;
  MOD_Reg<tUInt8> INST_caches_1_validVec_17;
  MOD_Reg<tUInt8> INST_caches_1_validVec_18;
  MOD_Reg<tUInt8> INST_caches_1_validVec_19;
  MOD_Reg<tUInt8> INST_caches_1_validVec_2;
  MOD_Reg<tUInt8> INST_caches_1_validVec_20;
  MOD_Reg<tUInt8> INST_caches_1_validVec_21;
  MOD_Reg<tUInt8> INST_caches_1_validVec_22;
  MOD_Reg<tUInt8> INST_caches_1_validVec_23;
  MOD_Reg<tUInt8> INST_caches_1_validVec_3;
  MOD_Reg<tUInt8> INST_caches_1_validVec_4;
  MOD_Reg<tUInt8> INST_caches_1_validVec_5;
  MOD_Reg<tUInt8> INST_caches_1_validVec_6;
  MOD_Reg<tUInt8> INST_caches_1_validVec_7;
  MOD_Reg<tUInt8> INST_caches_1_validVec_8;
  MOD_Reg<tUInt8> INST_caches_1_validVec_9;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_0;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_1;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_10;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_11;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_12;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_13;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_14;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_15;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_16;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_17;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_18;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_19;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_2;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_20;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_21;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_22;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_23;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_3;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_4;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_5;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_6;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_7;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_8;
  MOD_Reg<tUInt32> INST_caches_1_vpnVec_9;
  MOD_Reg<tUInt64> INST_respQ_data_0;
  MOD_Wire<tUInt8> INST_respQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_respQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_respQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_respQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_respQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_respQ_empty_rl;
  MOD_Wire<tUInt8> INST_respQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_respQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_respQ_full_lat_0;
  MOD_Wire<tUInt8> INST_respQ_full_lat_1;
  MOD_Wire<tUInt8> INST_respQ_full_lat_2;
  MOD_Reg<tUInt8> INST_respQ_full_rl;
 
 /* Constructor */
 public:
  MOD_mkSplitTransCache(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_flush;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_flush;
  tUInt8 DEF_NOT_respQ_empty_rl_4___d767;
  tUInt8 DEF_IF_respQ_full_lat_0_whas__2_THEN_NOT_respQ_ful_ETC___d765;
  tUInt8 DEF_IF_caches_0_updRepIdx_lat_0_whas__2_THEN_NOT_c_ETC___d757;
  tUInt8 DEF_caches_1_updRepIdx_rl___d43;
  tUInt8 DEF_caches_1_updRepIdx_lat_0_wget____d42;
  tUInt8 DEF_caches_0_updRepIdx_rl___d14;
  tUInt8 DEF_caches_0_updRepIdx_lat_0_wget____d13;
  tUInt8 DEF_respQ_full_rl__h36706;
  tUInt8 DEF_respQ_full_lat_0_whas____d72;
  tUInt8 DEF_respQ_full_lat_0_wget____d73;
  tUInt8 DEF_respQ_empty_rl__h14505;
  tUInt8 DEF_caches_1_updRepIdx_lat_0_whas____d41;
  tUInt8 DEF_caches_0_updRepIdx_lat_0_whas____d12;
  tUInt8 DEF_caches_1_updRepIdx_rl_3_BIT_5___d48;
  tUInt8 DEF_caches_0_updRepIdx_rl_4_BIT_5___d19;
  tUInt8 DEF_IF_caches_1_updRepIdx_lat_0_whas__1_THEN_NOT_c_ETC___d762;
  tUInt8 DEF_NOT_caches_1_flushEn_whas__9___d50;
  tUInt8 DEF_NOT_caches_0_flushEn_whas__0___d21;
 
 /* Local definitions */
 private:
  tUInt8 DEF__0_CONCAT_DONTCARE___d23;
  tUInt8 DEF_caches_1_validVec_23__h30181;
  tUInt8 DEF_caches_1_validVec_22__h30048;
  tUInt8 DEF_caches_1_validVec_21__h29915;
  tUInt8 DEF_caches_1_validVec_20__h29782;
  tUInt8 DEF_caches_1_validVec_19__h29649;
  tUInt8 DEF_caches_1_validVec_18__h29516;
  tUInt8 DEF_caches_1_validVec_17__h29383;
  tUInt8 DEF_caches_1_validVec_16__h29250;
  tUInt8 DEF_caches_1_validVec_15__h29117;
  tUInt8 DEF_caches_1_validVec_14__h28984;
  tUInt8 DEF_caches_1_validVec_13__h28851;
  tUInt8 DEF_caches_1_validVec_12__h28718;
  tUInt8 DEF_caches_1_validVec_11__h28585;
  tUInt8 DEF_caches_1_validVec_10__h28452;
  tUInt8 DEF_caches_1_validVec_9__h28319;
  tUInt8 DEF_caches_1_validVec_8__h28186;
  tUInt8 DEF_caches_1_validVec_7__h28053;
  tUInt8 DEF_caches_1_validVec_6__h27920;
  tUInt8 DEF_caches_1_validVec_5__h27787;
  tUInt8 DEF_caches_1_validVec_4__h27654;
  tUInt8 DEF_caches_1_validVec_3__h27521;
  tUInt8 DEF_caches_1_validVec_2__h27388;
  tUInt8 DEF_caches_1_validVec_0__h25790;
  tUInt8 DEF_caches_1_validVec_1__h27255;
  tUInt8 DEF_caches_0_validVec_23__h21091;
  tUInt8 DEF_caches_0_validVec_22__h20962;
  tUInt8 DEF_caches_0_validVec_21__h20833;
  tUInt8 DEF_caches_0_validVec_20__h20704;
  tUInt8 DEF_caches_0_validVec_19__h20575;
  tUInt8 DEF_caches_0_validVec_18__h20446;
  tUInt8 DEF_caches_0_validVec_17__h20317;
  tUInt8 DEF_caches_0_validVec_16__h20188;
  tUInt8 DEF_caches_0_validVec_15__h20059;
  tUInt8 DEF_caches_0_validVec_14__h19930;
  tUInt8 DEF_caches_0_validVec_13__h19801;
  tUInt8 DEF_caches_0_validVec_12__h19672;
  tUInt8 DEF_caches_0_validVec_11__h19543;
  tUInt8 DEF_caches_0_validVec_10__h19414;
  tUInt8 DEF_caches_0_validVec_9__h19285;
  tUInt8 DEF_caches_0_validVec_8__h19156;
  tUInt8 DEF_caches_0_validVec_7__h19027;
  tUInt8 DEF_caches_0_validVec_6__h18898;
  tUInt8 DEF_caches_0_validVec_5__h18769;
  tUInt8 DEF_caches_0_validVec_4__h18640;
  tUInt8 DEF_caches_0_validVec_3__h18511;
  tUInt8 DEF_caches_0_validVec_2__h18382;
  tUInt8 DEF_caches_0_validVec_0__h16791;
  tUInt8 DEF_caches_0_validVec_1__h18253;
  tUInt8 DEF_addIdx__h71847;
  tUInt8 DEF_addIdx__h55868;
  tUInt8 DEF_NOT_caches_1_validVec_0_59___d360;
  tUInt8 DEF_NOT_caches_0_validVec_0_8___d79;
  tUInt8 DEF_NOT_caches_0_validVec_23_62___d689;
  tUInt8 DEF_NOT_caches_1_validVec_22_35___d536;
  tUInt8 DEF_NOT_caches_1_validVec_21_27___d528;
  tUInt8 DEF_NOT_caches_1_validVec_20_19___d520;
  tUInt8 DEF_NOT_caches_1_validVec_19_11___d512;
  tUInt8 DEF_NOT_caches_1_validVec_18_03___d504;
  tUInt8 DEF_NOT_caches_1_validVec_17_95___d496;
  tUInt8 DEF_NOT_caches_1_validVec_16_87___d488;
  tUInt8 DEF_NOT_caches_1_validVec_15_79___d480;
  tUInt8 DEF_NOT_caches_1_validVec_14_71___d472;
  tUInt8 DEF_NOT_caches_1_validVec_13_63___d464;
  tUInt8 DEF_NOT_caches_1_validVec_12_55___d456;
  tUInt8 DEF_NOT_caches_1_validVec_11_47___d448;
  tUInt8 DEF_NOT_caches_1_validVec_10_39___d440;
  tUInt8 DEF_NOT_caches_1_validVec_9_31___d432;
  tUInt8 DEF_NOT_caches_1_validVec_8_23___d424;
  tUInt8 DEF_NOT_caches_1_validVec_7_15___d416;
  tUInt8 DEF_NOT_caches_1_validVec_6_07___d408;
  tUInt8 DEF_NOT_caches_1_validVec_5_99___d400;
  tUInt8 DEF_NOT_caches_1_validVec_4_91___d392;
  tUInt8 DEF_NOT_caches_1_validVec_3_83___d384;
  tUInt8 DEF_NOT_caches_1_validVec_2_75___d376;
  tUInt8 DEF_NOT_caches_1_validVec_1_67___d368;
  tUInt8 DEF_NOT_caches_0_validVec_22_54___d255;
  tUInt8 DEF_NOT_caches_0_validVec_21_46___d247;
  tUInt8 DEF_NOT_caches_0_validVec_20_38___d239;
  tUInt8 DEF_NOT_caches_0_validVec_19_30___d231;
  tUInt8 DEF_NOT_caches_0_validVec_18_22___d223;
  tUInt8 DEF_NOT_caches_0_validVec_17_14___d215;
  tUInt8 DEF_NOT_caches_0_validVec_16_06___d207;
  tUInt8 DEF_NOT_caches_0_validVec_15_98___d199;
  tUInt8 DEF_NOT_caches_0_validVec_14_90___d191;
  tUInt8 DEF_NOT_caches_0_validVec_13_82___d183;
  tUInt8 DEF_NOT_caches_0_validVec_12_74___d175;
  tUInt8 DEF_NOT_caches_0_validVec_11_66___d167;
  tUInt8 DEF_NOT_caches_0_validVec_10_58___d159;
  tUInt8 DEF_NOT_caches_0_validVec_9_50___d151;
  tUInt8 DEF_NOT_caches_0_validVec_8_42___d143;
  tUInt8 DEF_NOT_caches_0_validVec_7_34___d135;
  tUInt8 DEF_NOT_caches_0_validVec_6_26___d127;
  tUInt8 DEF_NOT_caches_0_validVec_5_18___d119;
  tUInt8 DEF_NOT_caches_0_validVec_4_10___d111;
  tUInt8 DEF_NOT_caches_0_validVec_3_02___d103;
  tUInt8 DEF_NOT_caches_0_validVec_2_4___d95;
  tUInt8 DEF_NOT_caches_0_validVec_1_6___d87;
  tUInt32 DEF_upd__h64550;
  tUInt32 DEF_x_wget__h12065;
  tUInt32 DEF_upd__h48571;
  tUInt32 DEF_x_wget__h5423;
  tUInt32 DEF_caches_0_vpnVec_23_BITS_26_TO_9___h79335;
  tUInt32 DEF_caches_0_vpnVec_22_BITS_26_TO_9___h79216;
  tUInt32 DEF_caches_0_vpnVec_21_BITS_26_TO_9___h79097;
  tUInt32 DEF_caches_0_vpnVec_20_BITS_26_TO_9___h78978;
  tUInt32 DEF_caches_0_vpnVec_19_BITS_26_TO_9___h78859;
  tUInt32 DEF_caches_0_vpnVec_18_BITS_26_TO_9___h78740;
  tUInt32 DEF_caches_0_vpnVec_17_BITS_26_TO_9___h78621;
  tUInt32 DEF_caches_0_vpnVec_16_BITS_26_TO_9___h78502;
  tUInt32 DEF_caches_0_vpnVec_15_BITS_26_TO_9___h78383;
  tUInt32 DEF_caches_0_vpnVec_14_BITS_26_TO_9___h78264;
  tUInt32 DEF_caches_0_vpnVec_13_BITS_26_TO_9___h78145;
  tUInt32 DEF_caches_0_vpnVec_12_BITS_26_TO_9___h78026;
  tUInt32 DEF_caches_0_vpnVec_11_BITS_26_TO_9___h77907;
  tUInt32 DEF_caches_0_vpnVec_10_BITS_26_TO_9___h77788;
  tUInt32 DEF_caches_0_vpnVec_9_BITS_26_TO_9___h77669;
  tUInt32 DEF_caches_0_vpnVec_8_BITS_26_TO_9___h77550;
  tUInt32 DEF_caches_0_vpnVec_7_BITS_26_TO_9___h77431;
  tUInt32 DEF_caches_0_vpnVec_6_BITS_26_TO_9___h77312;
  tUInt32 DEF_caches_0_vpnVec_5_BITS_26_TO_9___h77193;
  tUInt32 DEF_caches_0_vpnVec_4_BITS_26_TO_9___h77074;
  tUInt32 DEF_caches_0_vpnVec_3_BITS_26_TO_9___h76955;
  tUInt32 DEF_caches_0_vpnVec_2_BITS_26_TO_9___h76836;
  tUInt32 DEF_caches_0_vpnVec_1_BITS_26_TO_9___h76717;
  tUInt32 DEF_caches_0_vpnVec_0_BITS_26_TO_9___h76599;
  tUInt32 DEF_caches_1_vpnVec_23_BITS_26_TO_18___h84089;
  tUInt32 DEF_caches_1_vpnVec_22_BITS_26_TO_18___h83966;
  tUInt32 DEF_caches_1_vpnVec_21_BITS_26_TO_18___h83843;
  tUInt32 DEF_caches_1_vpnVec_20_BITS_26_TO_18___h83720;
  tUInt32 DEF_caches_1_vpnVec_19_BITS_26_TO_18___h83597;
  tUInt32 DEF_caches_1_vpnVec_18_BITS_26_TO_18___h83474;
  tUInt32 DEF_caches_1_vpnVec_17_BITS_26_TO_18___h83351;
  tUInt32 DEF_caches_1_vpnVec_16_BITS_26_TO_18___h83228;
  tUInt32 DEF_caches_1_vpnVec_15_BITS_26_TO_18___h83105;
  tUInt32 DEF_caches_1_vpnVec_14_BITS_26_TO_18___h82982;
  tUInt32 DEF_caches_1_vpnVec_13_BITS_26_TO_18___h82859;
  tUInt32 DEF_caches_1_vpnVec_12_BITS_26_TO_18___h82736;
  tUInt32 DEF_caches_1_vpnVec_11_BITS_26_TO_18___h82613;
  tUInt32 DEF_caches_1_vpnVec_10_BITS_26_TO_18___h82490;
  tUInt32 DEF_caches_1_vpnVec_9_BITS_26_TO_18___h82367;
  tUInt32 DEF_caches_1_vpnVec_8_BITS_26_TO_18___h82244;
  tUInt32 DEF_caches_1_vpnVec_7_BITS_26_TO_18___h82121;
  tUInt32 DEF_caches_1_vpnVec_6_BITS_26_TO_18___h81998;
  tUInt32 DEF_caches_1_vpnVec_5_BITS_26_TO_18___h81875;
  tUInt32 DEF_caches_1_vpnVec_4_BITS_26_TO_18___h81752;
  tUInt32 DEF_caches_1_vpnVec_3_BITS_26_TO_18___h81629;
  tUInt32 DEF_caches_1_vpnVec_2_BITS_26_TO_18___h81506;
  tUInt32 DEF_caches_1_vpnVec_1_BITS_26_TO_18___h81383;
  tUInt32 DEF_caches_1_vpnVec_0_BITS_26_TO_18___h81261;
  tUInt32 DEF_IF_caches_1_lruBit_lat_0_whas__3_THEN_IF_cache_ETC___d37;
  tUInt32 DEF_upd__h12329;
  tUInt32 DEF_IF_caches_0_lruBit_lat_0_whas_THEN_IF_caches_0_ETC___d8;
  tUInt32 DEF_upd__h5687;
 
 /* Rules */
 public:
  void RL_caches_0_lruBit_canon();
  void RL_caches_0_updRepIdx_canon();
  void RL_caches_0_incRandIdx();
  void RL_caches_0_doUpdateRep();
  void RL_caches_1_lruBit_canon();
  void RL_caches_1_updRepIdx_canon();
  void RL_caches_1_incRandIdx();
  void RL_caches_1_doUpdateRep();
  void RL_respQ_empty_canon();
  void RL_respQ_full_canon();
 
 /* Methods */
 public:
  tUInt8 METH_flush_done();
  tUInt8 METH_RDY_flush_done();
  void METH_req(tUInt32 ARG_req_vpn, tUInt8 ARG_req_asid);
  tUInt8 METH_RDY_req();
  tUInt64 METH_resp();
  tUInt8 METH_RDY_resp();
  void METH_deqResp();
  tUInt8 METH_RDY_deqResp();
  void METH_addEntry(tUInt32 ARG_addEntry_vpn,
		     tUInt8 ARG_addEntry_level,
		     tUInt64 ARG_addEntry_ppn,
		     tUInt8 ARG_addEntry_asid);
  tUInt8 METH_RDY_addEntry();
  void METH_flush();
  tUInt8 METH_RDY_flush();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSplitTransCache &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkSplitTransCache &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkSplitTransCache &backing);
};

#endif /* ifndef __mkSplitTransCache_h__ */
