/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkTourPred_h__
#define __mkTourPred_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkTourGHistReg.h"


/* Class declaration for the mkTourPred module */
class MOD_mkTourPred : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_RegFile<tUInt32,tUInt8> INST_choiceBht;
  MOD_mkTourGHistReg INST_gHistReg;
  MOD_RegFile<tUInt32,tUInt8> INST_globalBht;
  MOD_Reg<tUInt8> INST_globalTakenVec;
  MOD_RegFile<tUInt32,tUInt8> INST_localBht;
  MOD_RegFile<tUInt32,tUInt32> INST_localHistTab;
  MOD_Reg<tUInt32> INST_pcIndex;
  MOD_Reg<tUInt64> INST_pc_reg;
  MOD_Wire<tUInt8> INST_predCnt_lat_0;
  MOD_Wire<tUInt8> INST_predCnt_lat_1;
  MOD_Wire<tUInt8> INST_predCnt_lat_2;
  MOD_Reg<tUInt8> INST_predCnt_rl;
  MOD_Wire<tUInt8> INST_predRes_lat_0;
  MOD_Wire<tUInt8> INST_predRes_lat_1;
  MOD_Wire<tUInt8> INST_predRes_lat_2;
  MOD_Reg<tUInt8> INST_predRes_rl;
  MOD_Reg<tUInt32> INST_prevGHist;
  MOD_Reg<tUInt8> INST_useLocalVec;
 
 /* Constructor */
 public:
  MOD_mkTourPred(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt8 DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11;
  tUInt8 DEF_upd__h4191;
  tUInt32 DEF_pcIndex__h4346;
  tUInt32 DEF__read__h1949;
  tUInt8 DEF_upd__h4403;
  tUInt8 DEF_x_wget__h1551;
  tUInt8 DEF_x_wget__h1502;
  tUInt8 DEF_x_wget__h955;
  tUInt8 DEF_x_wget__h906;
  tUInt8 DEF_useLocalVec__h3767;
  tUInt8 DEF_globalTakenVec__h3987;
  tUInt8 DEF_globalTakenVec_BIT_1___h3988;
  tUInt8 DEF_globalTakenVec_BIT_0___h3965;
  tUInt8 DEF_useLocalVec_BIT_1___h3768;
  tUInt8 DEF_useLocalVec_BIT_0___h3745;
  tUInt8 DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24;
  tUInt8 DEF_upd__h1878;
  tUInt8 DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25;
  tUInt8 DEF_upd__h1851;
  tUInt8 DEF_upd__h1286;
  tUInt8 DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12;
  tUInt8 DEF_upd__h1259;
 
 /* Rules */
 public:
  void RL_predCnt_canon();
  void RL_predRes_canon();
  void RL_canonGlobalHist();
 
 /* Methods */
 public:
  tUInt8 METH_flush_done();
  tUInt8 METH_RDY_flush_done();
  void METH_nextPc(tUInt64 ARG_nextPc_nextPc);
  tUInt8 METH_RDY_nextPc();
  tUInt64 METH_pred_0_pred();
  tUInt8 METH_RDY_pred_0_pred();
  tUInt64 METH_pred_1_pred();
  tUInt8 METH_RDY_pred_1_pred();
  void METH_update(tUInt8 ARG_update_taken, tUInt64 ARG_update_train, tUInt8 ARG_update_mispred);
  tUInt8 METH_RDY_update();
  void METH_flush();
  tUInt8 METH_RDY_flush();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTourPred &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTourPred &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTourPred &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTourPred &backing);
};

#endif /* ifndef __mkTourPred_h__ */
