/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "mkTourPred.h"


/* Constructor */
MOD_mkTourPred::MOD_mkTourPred(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_choiceBht(simHdl, "choiceBht", this, 12u, 2u, 0u, 4095u),
    INST_gHistReg(simHdl, "gHistReg", this),
    INST_globalBht(simHdl, "globalBht", this, 12u, 2u, 0u, 4095u),
    INST_globalTakenVec(simHdl, "globalTakenVec", this, 2u),
    INST_localBht(simHdl, "localBht", this, 10u, 3u, 0u, 1023u),
    INST_localHistTab(simHdl, "localHistTab", this, 10u, 10u, 0u, 1023u),
    INST_pcIndex(simHdl, "pcIndex", this, 20u),
    INST_pc_reg(simHdl, "pc_reg", this, 64u),
    INST_predCnt_lat_0(simHdl, "predCnt_lat_0", this, 2u, (tUInt8)0u),
    INST_predCnt_lat_1(simHdl, "predCnt_lat_1", this, 2u, (tUInt8)0u),
    INST_predCnt_lat_2(simHdl, "predCnt_lat_2", this, 2u, (tUInt8)0u),
    INST_predCnt_rl(simHdl, "predCnt_rl", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_predRes_lat_0(simHdl, "predRes_lat_0", this, 2u, (tUInt8)0u),
    INST_predRes_lat_1(simHdl, "predRes_lat_1", this, 2u, (tUInt8)0u),
    INST_predRes_lat_2(simHdl, "predRes_lat_2", this, 2u, (tUInt8)0u),
    INST_predRes_rl(simHdl, "predRes_rl", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_prevGHist(simHdl, "prevGHist", this, 12u),
    INST_useLocalVec(simHdl, "useLocalVec", this, 2u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 21u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTourPred::init_symbols_0()
{
  init_symbol(&symbols[0u], "choiceBht", SYM_MODULE, &INST_choiceBht);
  init_symbol(&symbols[1u], "gHistReg", SYM_MODULE, &INST_gHistReg);
  init_symbol(&symbols[2u], "globalBht", SYM_MODULE, &INST_globalBht);
  init_symbol(&symbols[3u], "globalTakenVec", SYM_MODULE, &INST_globalTakenVec);
  init_symbol(&symbols[4u], "localBht", SYM_MODULE, &INST_localBht);
  init_symbol(&symbols[5u], "localHistTab", SYM_MODULE, &INST_localHistTab);
  init_symbol(&symbols[6u], "pc_reg", SYM_MODULE, &INST_pc_reg);
  init_symbol(&symbols[7u], "pcIndex", SYM_MODULE, &INST_pcIndex);
  init_symbol(&symbols[8u], "predCnt_lat_0", SYM_MODULE, &INST_predCnt_lat_0);
  init_symbol(&symbols[9u], "predCnt_lat_1", SYM_MODULE, &INST_predCnt_lat_1);
  init_symbol(&symbols[10u], "predCnt_lat_2", SYM_MODULE, &INST_predCnt_lat_2);
  init_symbol(&symbols[11u], "predCnt_rl", SYM_MODULE, &INST_predCnt_rl);
  init_symbol(&symbols[12u], "predRes_lat_0", SYM_MODULE, &INST_predRes_lat_0);
  init_symbol(&symbols[13u], "predRes_lat_1", SYM_MODULE, &INST_predRes_lat_1);
  init_symbol(&symbols[14u], "predRes_lat_2", SYM_MODULE, &INST_predRes_lat_2);
  init_symbol(&symbols[15u], "predRes_rl", SYM_MODULE, &INST_predRes_rl);
  init_symbol(&symbols[16u], "prevGHist", SYM_MODULE, &INST_prevGHist);
  init_symbol(&symbols[17u], "RL_canonGlobalHist", SYM_RULE);
  init_symbol(&symbols[18u], "RL_predCnt_canon", SYM_RULE);
  init_symbol(&symbols[19u], "RL_predRes_canon", SYM_RULE);
  init_symbol(&symbols[20u], "useLocalVec", SYM_MODULE, &INST_useLocalVec);
}


/* Rule actions */

void MOD_mkTourPred::RL_predCnt_canon()
{
  tUInt8 DEF_upd__h1232;
  tUInt8 DEF_x__h1083;
  tUInt8 DEF_x_wget__h1004;
  DEF_upd__h4191 = INST_predCnt_rl.METH_read();
  DEF_x_wget__h1004 = INST_predCnt_lat_2.METH_wget();
  DEF_x_wget__h955 = INST_predCnt_lat_1.METH_wget();
  DEF_x_wget__h906 = INST_predCnt_lat_0.METH_wget();
  DEF_upd__h1286 = DEF_x_wget__h906;
  DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 = INST_predCnt_lat_0.METH_whas() ? DEF_upd__h1286 : DEF_upd__h4191;
  DEF_upd__h1232 = DEF_x_wget__h1004;
  DEF_upd__h1259 = DEF_x_wget__h955;
  DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12 = INST_predCnt_lat_1.METH_whas() ? DEF_upd__h1259 : DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11;
  DEF_x__h1083 = INST_predCnt_lat_2.METH_whas() ? DEF_upd__h1232 : DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12;
  INST_predCnt_rl.METH_write(DEF_x__h1083);
}

void MOD_mkTourPred::RL_predRes_canon()
{
  tUInt8 DEF_upd__h1824;
  tUInt8 DEF_x__h1675;
  tUInt8 DEF_x_wget__h1600;
  DEF_upd__h4403 = INST_predRes_rl.METH_read();
  DEF_x_wget__h1600 = INST_predRes_lat_2.METH_wget();
  DEF_x_wget__h1551 = INST_predRes_lat_1.METH_wget();
  DEF_x_wget__h1502 = INST_predRes_lat_0.METH_wget();
  DEF_upd__h1878 = DEF_x_wget__h1502;
  DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 = INST_predRes_lat_0.METH_whas() ? DEF_upd__h1878 : DEF_upd__h4403;
  DEF_upd__h1851 = DEF_x_wget__h1551;
  DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25 = INST_predRes_lat_1.METH_whas() ? DEF_upd__h1851 : DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24;
  DEF_upd__h1824 = DEF_x_wget__h1600;
  DEF_x__h1675 = INST_predRes_lat_2.METH_whas() ? DEF_upd__h1824 : DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25;
  INST_predRes_rl.METH_write(DEF_x__h1675);
}

void MOD_mkTourPred::RL_canonGlobalHist()
{
  tUInt8 DEF_choiceBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d42;
  tUInt8 DEF_globalBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d37;
  tUInt32 DEF_x_BITS_11_TO_1___h2559;
  tUInt32 DEF_x__h2510;
  tUInt32 DEF_nHist__h2285;
  tUInt32 DEF_i__h2503;
  tUInt32 DEF_curGHist__h1925;
  DEF_upd__h4191 = INST_predCnt_rl.METH_read();
  DEF_curGHist__h1925 = INST_gHistReg.METH_history();
  DEF_upd__h4403 = INST_predRes_rl.METH_read();
  DEF_x_wget__h1551 = INST_predRes_lat_1.METH_wget();
  DEF_x_wget__h955 = INST_predCnt_lat_1.METH_wget();
  DEF_x_wget__h1502 = INST_predRes_lat_0.METH_wget();
  DEF_x_wget__h906 = INST_predCnt_lat_0.METH_wget();
  DEF_upd__h1878 = DEF_x_wget__h1502;
  DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 = INST_predRes_lat_0.METH_whas() ? DEF_upd__h1878 : DEF_upd__h4403;
  DEF_upd__h1851 = DEF_x_wget__h1551;
  DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25 = INST_predRes_lat_1.METH_whas() ? DEF_upd__h1851 : DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24;
  DEF_upd__h1286 = DEF_x_wget__h906;
  DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 = INST_predCnt_lat_0.METH_whas() ? DEF_upd__h1286 : DEF_upd__h4191;
  DEF_upd__h1259 = DEF_x_wget__h955;
  DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12 = INST_predCnt_lat_1.METH_whas() ? DEF_upd__h1259 : DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11;
  DEF_x__h2510 = primShiftR32(14u,
			      14u,
			      (tUInt32)(16383u & ((((tUInt32)(DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25)) << 12u) | DEF_curGHist__h1925)),
			      2u,
			      (tUInt8)(DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12));
  DEF_nHist__h2285 = (tUInt32)(4095u & DEF_x__h2510);
  DEF_x_BITS_11_TO_1___h2559 = (tUInt32)(2047u & (DEF_x__h2510 >> 1u));
  DEF_i__h2503 = 4095u & ((((tUInt32)((tUInt8)0u)) << 11u) | DEF_x_BITS_11_TO_1___h2559);
  DEF_globalBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d37 = (tUInt8)3u & ((((tUInt8)(INST_globalBht.METH_sub(DEF_i__h2503) >> 1u)) << 1u) | (tUInt8)(INST_globalBht.METH_sub(DEF_nHist__h2285) >> 1u));
  DEF_choiceBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d42 = (tUInt8)3u & ((((tUInt8)(INST_choiceBht.METH_sub(DEF_i__h2503) >> 1u)) << 1u) | (tUInt8)(INST_choiceBht.METH_sub(DEF_nHist__h2285) >> 1u));
  INST_gHistReg.METH_addHistory(DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25,
				DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12);
  INST_globalTakenVec.METH_write(DEF_globalBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d37);
  INST_useLocalVec.METH_write(DEF_choiceBht_sub_0_CONCAT_IF_predRes_lat_1_whas___ETC___d42);
  INST_predRes_lat_2.METH_wset((tUInt8)0u);
  INST_prevGHist.METH_write(DEF_nHist__h2285);
  INST_predCnt_lat_2.METH_wset((tUInt8)0u);
}


/* Methods */

tUInt8 MOD_mkTourPred::METH_flush_done()
{
  tUInt8 PORT_flush_done;
  PORT_flush_done = (tUInt8)1u;
  return PORT_flush_done;
}

tUInt8 MOD_mkTourPred::METH_RDY_flush_done()
{
  tUInt8 DEF_CAN_FIRE_flush_done;
  tUInt8 PORT_RDY_flush_done;
  DEF_CAN_FIRE_flush_done = (tUInt8)1u;
  PORT_RDY_flush_done = DEF_CAN_FIRE_flush_done;
  return PORT_RDY_flush_done;
}

void MOD_mkTourPred::METH_nextPc(tUInt64 ARG_nextPc_nextPc)
{
  tUInt32 DEF_nextPc_nextPc_BITS_10_TO_8_3_CONCAT_nextPc_nex_ETC___d48;
  tUInt8 DEF_x__h3256;
  DEF_x__h3256 = (tUInt8)((tUInt8)255u & ARG_nextPc_nextPc);
  DEF_nextPc_nextPc_BITS_10_TO_8_3_CONCAT_nextPc_nex_ETC___d48 = 1048575u & (((((tUInt32)((tUInt8)((tUInt8)7u & (ARG_nextPc_nextPc >> 8u)))) << 17u) | (((tUInt32)((tUInt8)(((tUInt8)255u & (DEF_x__h3256 + (tUInt8)4u)) >> 1u))) << 10u)) | (tUInt32)(1023u & (ARG_nextPc_nextPc >> 1u)));
  INST_pc_reg.METH_write(ARG_nextPc_nextPc);
  INST_pcIndex.METH_write(DEF_nextPc_nextPc_BITS_10_TO_8_3_CONCAT_nextPc_nex_ETC___d48);
}

tUInt8 MOD_mkTourPred::METH_RDY_nextPc()
{
  tUInt8 DEF_CAN_FIRE_nextPc;
  tUInt8 PORT_RDY_nextPc;
  DEF_CAN_FIRE_nextPc = (tUInt8)1u;
  PORT_RDY_nextPc = DEF_CAN_FIRE_nextPc;
  return PORT_RDY_nextPc;
}

tUInt64 MOD_mkTourPred::METH_pred_0_pred()
{
  tUInt32 DEF_localHistTab_sub_pcIndex_5_BITS_9_TO_0_6_7_CON_ETC___d74;
  tUInt8 DEF_x__h3553;
  tUInt32 DEF_y_avValue_train_globalHist__h4069;
  tUInt8 DEF_x__h3630;
  tUInt8 DEF_y__h4054;
  tUInt8 DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65;
  tUInt8 DEF_x__h3611;
  tUInt8 DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64;
  tUInt8 DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d54;
  tUInt8 DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_9_ETC___d59;
  tUInt32 DEF_x__h4107;
  tUInt32 DEF_x__h4105;
  tUInt64 PORT_pred_0_pred;
  DEF_upd__h4191 = INST_predCnt_rl.METH_read();
  DEF_pcIndex__h4346 = INST_pcIndex.METH_read();
  DEF__read__h1949 = INST_prevGHist.METH_read();
  DEF_x__h4107 = (tUInt32)(1023u & DEF_pcIndex__h4346);
  DEF_x__h4105 = INST_localHistTab.METH_sub(DEF_x__h4107);
  DEF_upd__h4403 = INST_predRes_rl.METH_read();
  DEF_useLocalVec__h3767 = INST_useLocalVec.METH_read();
  DEF_globalTakenVec__h3987 = INST_globalTakenVec.METH_read();
  DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_9_ETC___d59 = (tUInt8)(INST_localBht.METH_sub(DEF_x__h4105) >> 2u);
  DEF_globalTakenVec_BIT_1___h3988 = (tUInt8)(DEF_globalTakenVec__h3987 >> 1u);
  DEF_globalTakenVec_BIT_0___h3965 = (tUInt8)((tUInt8)1u & DEF_globalTakenVec__h3987);
  DEF_useLocalVec_BIT_1___h3768 = (tUInt8)(DEF_useLocalVec__h3767 >> 1u);
  DEF_useLocalVec_BIT_0___h3745 = (tUInt8)((tUInt8)1u & DEF_useLocalVec__h3767);
  switch (DEF_upd__h4191) {
  case (tUInt8)0u:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d54 = DEF_useLocalVec_BIT_0___h3745;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d54 = DEF_useLocalVec_BIT_1___h3768;
    break;
  default:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d54 = (tUInt8)0u;
  }
  switch (DEF_upd__h4191) {
  case (tUInt8)0u:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 = DEF_globalTakenVec_BIT_0___h3965;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 = DEF_globalTakenVec_BIT_1___h3988;
    break;
  default:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 = (tUInt8)0u;
  }
  DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65 = DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d54 ? DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_9_ETC___d59 : DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64;
  DEF_x__h3630 = primShiftL8(2u, 2u, (tUInt8)1u, 2u, (tUInt8)(DEF_upd__h4191));
  DEF_y__h4054 = (tUInt8)3u & ~DEF_x__h3630;
  DEF_x__h3611 = DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65 ? DEF_upd__h4403 | DEF_x__h3630 : DEF_upd__h4403 & DEF_y__h4054;
  DEF_y_avValue_train_globalHist__h4069 = primShiftR32(12u,
						       12u,
						       (tUInt32)(DEF__read__h1949),
						       2u,
						       (tUInt8)(DEF_upd__h4191));
  DEF_x__h3553 = (tUInt8)3u & (DEF_upd__h4191 + (tUInt8)1u);
  DEF_localHistTab_sub_pcIndex_5_BITS_9_TO_0_6_7_CON_ETC___d74 = 4194303u & ((((DEF_x__h4105 << 12u) | (((tUInt32)(DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64)) << 11u)) | (((tUInt32)(DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_9_ETC___d59)) << 10u)) | DEF_x__h4107);
  PORT_pred_0_pred = 34359738367llu & (((((tUInt64)(DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65)) << 34u) | (((tUInt64)(DEF_y_avValue_train_globalHist__h4069)) << 22u)) | (tUInt64)(DEF_localHistTab_sub_pcIndex_5_BITS_9_TO_0_6_7_CON_ETC___d74));
  INST_predCnt_lat_0.METH_wset(DEF_x__h3553);
  INST_predRes_lat_0.METH_wset(DEF_x__h3611);
  return PORT_pred_0_pred;
}

tUInt8 MOD_mkTourPred::METH_RDY_pred_0_pred()
{
  tUInt8 DEF_CAN_FIRE_pred_0_pred;
  tUInt8 PORT_RDY_pred_0_pred;
  DEF_CAN_FIRE_pred_0_pred = (tUInt8)1u;
  PORT_RDY_pred_0_pred = DEF_CAN_FIRE_pred_0_pred;
  return PORT_RDY_pred_0_pred;
}

tUInt64 MOD_mkTourPred::METH_pred_1_pred()
{
  tUInt32 DEF_localHistTab_sub_pcIndex_5_BITS_19_TO_10_7_8_C_ETC___d90;
  tUInt8 DEF_x__h4167;
  tUInt32 DEF_y_avValue_train_globalHist__h4474;
  tUInt8 DEF_x__h4272;
  tUInt8 DEF_y__h4462;
  tUInt8 DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82;
  tUInt8 DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81;
  tUInt8 DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d76;
  tUInt8 DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_1_ETC___d80;
  tUInt32 DEF_x__h4509;
  tUInt32 DEF_x__h4507;
  tUInt64 PORT_pred_1_pred;
  tUInt8 DEF_x__h4253;
  DEF_upd__h4191 = INST_predCnt_rl.METH_read();
  DEF_pcIndex__h4346 = INST_pcIndex.METH_read();
  DEF__read__h1949 = INST_prevGHist.METH_read();
  DEF_x__h4509 = (tUInt32)(DEF_pcIndex__h4346 >> 10u);
  DEF_x__h4507 = INST_localHistTab.METH_sub(DEF_x__h4509);
  DEF_upd__h4403 = INST_predRes_rl.METH_read();
  DEF_x_wget__h1502 = INST_predRes_lat_0.METH_wget();
  DEF_x_wget__h906 = INST_predCnt_lat_0.METH_wget();
  DEF_useLocalVec__h3767 = INST_useLocalVec.METH_read();
  DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_1_ETC___d80 = (tUInt8)(INST_localBht.METH_sub(DEF_x__h4507) >> 2u);
  DEF_globalTakenVec__h3987 = INST_globalTakenVec.METH_read();
  DEF_globalTakenVec_BIT_1___h3988 = (tUInt8)(DEF_globalTakenVec__h3987 >> 1u);
  DEF_globalTakenVec_BIT_0___h3965 = (tUInt8)((tUInt8)1u & DEF_globalTakenVec__h3987);
  DEF_useLocalVec_BIT_1___h3768 = (tUInt8)(DEF_useLocalVec__h3767 >> 1u);
  DEF_useLocalVec_BIT_0___h3745 = (tUInt8)((tUInt8)1u & DEF_useLocalVec__h3767);
  DEF_upd__h1878 = DEF_x_wget__h1502;
  DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 = INST_predRes_lat_0.METH_whas() ? DEF_upd__h1878 : DEF_upd__h4403;
  DEF_upd__h1286 = DEF_x_wget__h906;
  DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 = INST_predCnt_lat_0.METH_whas() ? DEF_upd__h1286 : DEF_upd__h4191;
  switch (DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11) {
  case (tUInt8)0u:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d76 = DEF_useLocalVec_BIT_0___h3745;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d76 = DEF_useLocalVec_BIT_1___h3768;
    break;
  default:
    DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d76 = (tUInt8)0u;
  }
  switch (DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11) {
  case (tUInt8)0u:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 = DEF_globalTakenVec_BIT_0___h3965;
    break;
  case (tUInt8)1u:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 = DEF_globalTakenVec_BIT_1___h3988;
    break;
  default:
    DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 = (tUInt8)0u;
  }
  DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82 = DEF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_BI_ETC___d76 ? DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_1_ETC___d80 : DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81;
  DEF_x__h4272 = primShiftL8(2u,
			     2u,
			     (tUInt8)1u,
			     2u,
			     (tUInt8)(DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11));
  DEF_y__h4462 = (tUInt8)3u & ~DEF_x__h4272;
  DEF_x__h4253 = DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82 ? DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 | DEF_x__h4272 : DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 & DEF_y__h4462;
  DEF_y_avValue_train_globalHist__h4474 = primShiftR32(12u,
						       12u,
						       (tUInt32)(DEF__read__h1949),
						       2u,
						       (tUInt8)(DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11));
  DEF_x__h4167 = (tUInt8)3u & (DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 + (tUInt8)1u);
  DEF_localHistTab_sub_pcIndex_5_BITS_19_TO_10_7_8_C_ETC___d90 = 4194303u & ((((DEF_x__h4507 << 12u) | (((tUInt32)(DEF_SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81)) << 11u)) | (((tUInt32)(DEF_localBht_sub_localHistTab_sub_pcIndex_5_BITS_1_ETC___d80)) << 10u)) | DEF_x__h4509);
  PORT_pred_1_pred = 34359738367llu & (((((tUInt64)(DEF_IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82)) << 34u) | (((tUInt64)(DEF_y_avValue_train_globalHist__h4474)) << 22u)) | (tUInt64)(DEF_localHistTab_sub_pcIndex_5_BITS_19_TO_10_7_8_C_ETC___d90));
  INST_predCnt_lat_1.METH_wset(DEF_x__h4167);
  INST_predRes_lat_1.METH_wset(DEF_x__h4253);
  return PORT_pred_1_pred;
}

tUInt8 MOD_mkTourPred::METH_RDY_pred_1_pred()
{
  tUInt8 DEF_CAN_FIRE_pred_1_pred;
  tUInt8 PORT_RDY_pred_1_pred;
  DEF_CAN_FIRE_pred_1_pred = (tUInt8)1u;
  PORT_RDY_pred_1_pred = DEF_CAN_FIRE_pred_1_pred;
  return PORT_RDY_pred_1_pred;
}

void MOD_mkTourPred::METH_update(tUInt8 ARG_update_taken,
				 tUInt64 ARG_update_train,
				 tUInt8 ARG_update_mispred)
{
  tUInt32 DEF_x__h4620;
  tUInt32 DEF_newHist__h4560;
  tUInt8 DEF_NOT_update_train_BIT_11_28_EQ_update_train_BIT_ETC___d131;
  tUInt8 DEF_IF_NOT_globalBht_sub_update_train_BITS_33_TO_2_ETC___d127;
  tUInt8 DEF_IF_NOT_choiceBht_sub_update_train_BITS_33_TO_2_ETC___d147;
  tUInt8 DEF_IF_NOT_localBht_sub_update_train_BITS_21_TO_12_ETC___d111;
  tUInt8 DEF_update_train_BIT_10___d129;
  tUInt8 DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d114;
  tUInt8 DEF_IF_update_taken_THEN_3_ELSE_1___d116;
  tUInt8 DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120;
  tUInt8 DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d121;
  tUInt8 DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d133;
  tUInt8 DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136;
  tUInt8 DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140;
  tUInt8 DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d141;
  tUInt8 DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_BIT_2___d98;
  tUInt8 DEF_IF_update_taken_THEN_7_ELSE_1___d100;
  tUInt8 DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104;
  tUInt8 DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d105;
  tUInt32 DEF_train_localHist_BITS_9_TO_1___h4648;
  tUInt32 DEF_i__h4619;
  tUInt32 DEF_train_globalHist_BITS_11_TO_1___h4592;
  tUInt8 DEF_b__h5222;
  tUInt32 DEF_i__h5622;
  tUInt8 DEF_b__h5623;
  tUInt32 DEF_i__h4782;
  tUInt8 DEF_b__h4783;
  tUInt8 DEF_IF_update_taken_THEN_7_ELSE_1_00_BIT_2___d101;
  tUInt8 DEF_IF_update_taken_THEN_3_ELSE_1_16_BIT_1___d117;
  tUInt8 DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d137;
  DEF_i__h4782 = (tUInt32)(1023u & (ARG_update_train >> 12u));
  DEF_b__h4783 = INST_localBht.METH_sub(DEF_i__h4782);
  DEF_i__h5622 = (tUInt32)(ARG_update_train >> 22u);
  DEF_b__h5623 = INST_choiceBht.METH_sub(DEF_i__h5622);
  DEF_b__h5222 = INST_globalBht.METH_sub(DEF_i__h5622);
  DEF_train_globalHist_BITS_11_TO_1___h4592 = (tUInt32)(ARG_update_train >> 23u);
  DEF_i__h4619 = (tUInt32)(1023u & ARG_update_train);
  DEF_train_localHist_BITS_9_TO_1___h4648 = (tUInt32)(511u & (ARG_update_train >> 13u));
  DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_BIT_2___d98 = (tUInt8)(DEF_b__h4783 >> 2u);
  DEF_IF_update_taken_THEN_7_ELSE_1___d100 = ARG_update_taken ? (tUInt8)7u : (tUInt8)1u;
  DEF_IF_update_taken_THEN_7_ELSE_1_00_BIT_2___d101 = (tUInt8)(DEF_IF_update_taken_THEN_7_ELSE_1___d100 >> 2u);
  DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104 = (tUInt8)7u & (DEF_b__h4783 + DEF_IF_update_taken_THEN_7_ELSE_1___d100);
  DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d105 = (tUInt8)(DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104 >> 2u);
  DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d133 = (tUInt8)(DEF_b__h5623 >> 1u);
  DEF_IF_update_taken_THEN_3_ELSE_1___d116 = ARG_update_taken ? (tUInt8)3u : (tUInt8)1u;
  DEF_IF_update_taken_THEN_3_ELSE_1_16_BIT_1___d117 = (tUInt8)(DEF_IF_update_taken_THEN_3_ELSE_1___d116 >> 1u);
  DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120 = (tUInt8)3u & (DEF_b__h5222 + DEF_IF_update_taken_THEN_3_ELSE_1___d116);
  DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d121 = (tUInt8)(DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120 >> 1u);
  DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d114 = (tUInt8)(DEF_b__h5222 >> 1u);
  DEF_update_train_BIT_10___d129 = (tUInt8)((tUInt8)1u & (ARG_update_train >> 10u));
  DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136 = DEF_update_train_BIT_10___d129 == ARG_update_taken ? (tUInt8)3u : (tUInt8)1u;
  DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d137 = (tUInt8)(DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136 >> 1u);
  DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140 = (tUInt8)3u & (DEF_b__h5623 + DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136);
  DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d141 = (tUInt8)(DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140 >> 1u);
  DEF_IF_NOT_localBht_sub_update_train_BITS_21_TO_12_ETC___d111 = (!DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_BIT_2___d98 && !DEF_IF_update_taken_THEN_7_ELSE_1_00_BIT_2___d101) && DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d105 ? (tUInt8)3u : ((DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_BIT_2___d98 && DEF_IF_update_taken_THEN_7_ELSE_1_00_BIT_2___d101) && !DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d105 ? (tUInt8)4u : DEF_localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104);
  DEF_IF_NOT_choiceBht_sub_update_train_BITS_33_TO_2_ETC___d147 = (!DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d133 && !DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d137) && DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d141 ? (tUInt8)1u : ((DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d133 && DEF_IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d137) && !DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d141 ? (tUInt8)2u : DEF_choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140);
  DEF_IF_NOT_globalBht_sub_update_train_BITS_33_TO_2_ETC___d127 = (!DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d114 && !DEF_IF_update_taken_THEN_3_ELSE_1_16_BIT_1___d117) && DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d121 ? (tUInt8)1u : ((DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d114 && DEF_IF_update_taken_THEN_3_ELSE_1_16_BIT_1___d117) && !DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d121 ? (tUInt8)2u : DEF_globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120);
  DEF_NOT_update_train_BIT_11_28_EQ_update_train_BIT_ETC___d131 = !(((tUInt8)((tUInt8)1u & (ARG_update_train >> 11u))) == DEF_update_train_BIT_10___d129);
  DEF_newHist__h4560 = 4095u & ((((tUInt32)(ARG_update_taken)) << 11u) | DEF_train_globalHist_BITS_11_TO_1___h4592);
  DEF_x__h4620 = 1023u & ((((tUInt32)(ARG_update_taken)) << 9u) | DEF_train_localHist_BITS_9_TO_1___h4648);
  if (ARG_update_mispred)
    INST_gHistReg.METH_redirect(DEF_newHist__h4560);
  INST_localHistTab.METH_upd(DEF_i__h4619, DEF_x__h4620);
  INST_localBht.METH_upd(DEF_i__h4782, DEF_IF_NOT_localBht_sub_update_train_BITS_21_TO_12_ETC___d111);
  INST_globalBht.METH_upd(DEF_i__h5622,
			  DEF_IF_NOT_globalBht_sub_update_train_BITS_33_TO_2_ETC___d127);
  if (DEF_NOT_update_train_BIT_11_28_EQ_update_train_BIT_ETC___d131)
    INST_choiceBht.METH_upd(DEF_i__h5622,
			    DEF_IF_NOT_choiceBht_sub_update_train_BITS_33_TO_2_ETC___d147);
}

tUInt8 MOD_mkTourPred::METH_RDY_update()
{
  tUInt8 DEF_CAN_FIRE_update;
  tUInt8 PORT_RDY_update;
  DEF_CAN_FIRE_update = (tUInt8)1u;
  PORT_RDY_update = DEF_CAN_FIRE_update;
  return PORT_RDY_update;
}

void MOD_mkTourPred::METH_flush()
{
}

tUInt8 MOD_mkTourPred::METH_RDY_flush()
{
  tUInt8 DEF_CAN_FIRE_flush;
  tUInt8 PORT_RDY_flush;
  DEF_CAN_FIRE_flush = (tUInt8)1u;
  PORT_RDY_flush = DEF_CAN_FIRE_flush;
  return PORT_RDY_flush;
}


/* Reset routines */

void MOD_mkTourPred::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_predRes_rl.reset_RST(ARG_rst_in);
  INST_predCnt_rl.reset_RST(ARG_rst_in);
  INST_gHistReg.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTourPred::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTourPred::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_choiceBht.dump_state(indent + 2u);
  INST_gHistReg.dump_state(indent + 2u);
  INST_globalBht.dump_state(indent + 2u);
  INST_globalTakenVec.dump_state(indent + 2u);
  INST_localBht.dump_state(indent + 2u);
  INST_localHistTab.dump_state(indent + 2u);
  INST_pcIndex.dump_state(indent + 2u);
  INST_pc_reg.dump_state(indent + 2u);
  INST_predCnt_lat_0.dump_state(indent + 2u);
  INST_predCnt_lat_1.dump_state(indent + 2u);
  INST_predCnt_lat_2.dump_state(indent + 2u);
  INST_predCnt_rl.dump_state(indent + 2u);
  INST_predRes_lat_0.dump_state(indent + 2u);
  INST_predRes_lat_1.dump_state(indent + 2u);
  INST_predRes_lat_2.dump_state(indent + 2u);
  INST_predRes_rl.dump_state(indent + 2u);
  INST_prevGHist.dump_state(indent + 2u);
  INST_useLocalVec.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTourPred::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 40u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25", 2u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h1949", 12u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "globalTakenVec_BIT_0___h3965", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "globalTakenVec_BIT_1___h3988", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "globalTakenVec__h3987", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "pcIndex__h4346", 20u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h1259", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h1286", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h1851", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h1878", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h4191", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "upd__h4403", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "useLocalVec_BIT_0___h3745", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "useLocalVec_BIT_1___h3768", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "useLocalVec__h3767", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1502", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h1551", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h906", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_wget__h955", 2u);
  num = INST_choiceBht.dump_VCD_defs(num);
  num = INST_globalBht.dump_VCD_defs(num);
  num = INST_globalTakenVec.dump_VCD_defs(num);
  num = INST_localBht.dump_VCD_defs(num);
  num = INST_localHistTab.dump_VCD_defs(num);
  num = INST_pcIndex.dump_VCD_defs(num);
  num = INST_pc_reg.dump_VCD_defs(num);
  num = INST_predCnt_lat_0.dump_VCD_defs(num);
  num = INST_predCnt_lat_1.dump_VCD_defs(num);
  num = INST_predCnt_lat_2.dump_VCD_defs(num);
  num = INST_predCnt_rl.dump_VCD_defs(num);
  num = INST_predRes_lat_0.dump_VCD_defs(num);
  num = INST_predRes_lat_1.dump_VCD_defs(num);
  num = INST_predRes_lat_2.dump_VCD_defs(num);
  num = INST_predRes_rl.dump_VCD_defs(num);
  num = INST_prevGHist.dump_VCD_defs(num);
  num = INST_useLocalVec.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_gHistReg.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTourPred::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTourPred &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkTourPred::vcd_defs(tVCDDumpType dt, MOD_mkTourPred &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 12u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 20u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 2u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11) != DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11, 2u);
	backing.DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 = DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11;
      }
      ++num;
      if ((backing.DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12) != DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12, 2u);
	backing.DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12 = DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12;
      }
      ++num;
      if ((backing.DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24) != DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24, 2u);
	backing.DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 = DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24;
      }
      ++num;
      if ((backing.DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25) != DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25, 2u);
	backing.DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25 = DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25;
      }
      ++num;
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__read__h1949) != DEF__read__h1949)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h1949, 12u);
	backing.DEF__read__h1949 = DEF__read__h1949;
      }
      ++num;
      if ((backing.DEF_globalTakenVec_BIT_0___h3965) != DEF_globalTakenVec_BIT_0___h3965)
      {
	vcd_write_val(sim_hdl, num, DEF_globalTakenVec_BIT_0___h3965, 1u);
	backing.DEF_globalTakenVec_BIT_0___h3965 = DEF_globalTakenVec_BIT_0___h3965;
      }
      ++num;
      if ((backing.DEF_globalTakenVec_BIT_1___h3988) != DEF_globalTakenVec_BIT_1___h3988)
      {
	vcd_write_val(sim_hdl, num, DEF_globalTakenVec_BIT_1___h3988, 1u);
	backing.DEF_globalTakenVec_BIT_1___h3988 = DEF_globalTakenVec_BIT_1___h3988;
      }
      ++num;
      if ((backing.DEF_globalTakenVec__h3987) != DEF_globalTakenVec__h3987)
      {
	vcd_write_val(sim_hdl, num, DEF_globalTakenVec__h3987, 2u);
	backing.DEF_globalTakenVec__h3987 = DEF_globalTakenVec__h3987;
      }
      ++num;
      if ((backing.DEF_pcIndex__h4346) != DEF_pcIndex__h4346)
      {
	vcd_write_val(sim_hdl, num, DEF_pcIndex__h4346, 20u);
	backing.DEF_pcIndex__h4346 = DEF_pcIndex__h4346;
      }
      ++num;
      if ((backing.DEF_upd__h1259) != DEF_upd__h1259)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h1259, 2u);
	backing.DEF_upd__h1259 = DEF_upd__h1259;
      }
      ++num;
      if ((backing.DEF_upd__h1286) != DEF_upd__h1286)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h1286, 2u);
	backing.DEF_upd__h1286 = DEF_upd__h1286;
      }
      ++num;
      if ((backing.DEF_upd__h1851) != DEF_upd__h1851)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h1851, 2u);
	backing.DEF_upd__h1851 = DEF_upd__h1851;
      }
      ++num;
      if ((backing.DEF_upd__h1878) != DEF_upd__h1878)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h1878, 2u);
	backing.DEF_upd__h1878 = DEF_upd__h1878;
      }
      ++num;
      if ((backing.DEF_upd__h4191) != DEF_upd__h4191)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h4191, 2u);
	backing.DEF_upd__h4191 = DEF_upd__h4191;
      }
      ++num;
      if ((backing.DEF_upd__h4403) != DEF_upd__h4403)
      {
	vcd_write_val(sim_hdl, num, DEF_upd__h4403, 2u);
	backing.DEF_upd__h4403 = DEF_upd__h4403;
      }
      ++num;
      if ((backing.DEF_useLocalVec_BIT_0___h3745) != DEF_useLocalVec_BIT_0___h3745)
      {
	vcd_write_val(sim_hdl, num, DEF_useLocalVec_BIT_0___h3745, 1u);
	backing.DEF_useLocalVec_BIT_0___h3745 = DEF_useLocalVec_BIT_0___h3745;
      }
      ++num;
      if ((backing.DEF_useLocalVec_BIT_1___h3768) != DEF_useLocalVec_BIT_1___h3768)
      {
	vcd_write_val(sim_hdl, num, DEF_useLocalVec_BIT_1___h3768, 1u);
	backing.DEF_useLocalVec_BIT_1___h3768 = DEF_useLocalVec_BIT_1___h3768;
      }
      ++num;
      if ((backing.DEF_useLocalVec__h3767) != DEF_useLocalVec__h3767)
      {
	vcd_write_val(sim_hdl, num, DEF_useLocalVec__h3767, 2u);
	backing.DEF_useLocalVec__h3767 = DEF_useLocalVec__h3767;
      }
      ++num;
      if ((backing.DEF_x_wget__h1502) != DEF_x_wget__h1502)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1502, 2u);
	backing.DEF_x_wget__h1502 = DEF_x_wget__h1502;
      }
      ++num;
      if ((backing.DEF_x_wget__h1551) != DEF_x_wget__h1551)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h1551, 2u);
	backing.DEF_x_wget__h1551 = DEF_x_wget__h1551;
      }
      ++num;
      if ((backing.DEF_x_wget__h906) != DEF_x_wget__h906)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h906, 2u);
	backing.DEF_x_wget__h906 = DEF_x_wget__h906;
      }
      ++num;
      if ((backing.DEF_x_wget__h955) != DEF_x_wget__h955)
      {
	vcd_write_val(sim_hdl, num, DEF_x_wget__h955, 2u);
	backing.DEF_x_wget__h955 = DEF_x_wget__h955;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11, 2u);
      backing.DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 = DEF_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11;
      vcd_write_val(sim_hdl, num++, DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12, 2u);
      backing.DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12 = DEF_IF_predCnt_lat_1_whas_THEN_IF_predCnt_lat_1_wh_ETC___d12;
      vcd_write_val(sim_hdl, num++, DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24, 2u);
      backing.DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 = DEF_IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24;
      vcd_write_val(sim_hdl, num++, DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25, 2u);
      backing.DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25 = DEF_IF_predRes_lat_1_whas__7_THEN_IF_predRes_lat_1_ETC___d25;
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__read__h1949, 12u);
      backing.DEF__read__h1949 = DEF__read__h1949;
      vcd_write_val(sim_hdl, num++, DEF_globalTakenVec_BIT_0___h3965, 1u);
      backing.DEF_globalTakenVec_BIT_0___h3965 = DEF_globalTakenVec_BIT_0___h3965;
      vcd_write_val(sim_hdl, num++, DEF_globalTakenVec_BIT_1___h3988, 1u);
      backing.DEF_globalTakenVec_BIT_1___h3988 = DEF_globalTakenVec_BIT_1___h3988;
      vcd_write_val(sim_hdl, num++, DEF_globalTakenVec__h3987, 2u);
      backing.DEF_globalTakenVec__h3987 = DEF_globalTakenVec__h3987;
      vcd_write_val(sim_hdl, num++, DEF_pcIndex__h4346, 20u);
      backing.DEF_pcIndex__h4346 = DEF_pcIndex__h4346;
      vcd_write_val(sim_hdl, num++, DEF_upd__h1259, 2u);
      backing.DEF_upd__h1259 = DEF_upd__h1259;
      vcd_write_val(sim_hdl, num++, DEF_upd__h1286, 2u);
      backing.DEF_upd__h1286 = DEF_upd__h1286;
      vcd_write_val(sim_hdl, num++, DEF_upd__h1851, 2u);
      backing.DEF_upd__h1851 = DEF_upd__h1851;
      vcd_write_val(sim_hdl, num++, DEF_upd__h1878, 2u);
      backing.DEF_upd__h1878 = DEF_upd__h1878;
      vcd_write_val(sim_hdl, num++, DEF_upd__h4191, 2u);
      backing.DEF_upd__h4191 = DEF_upd__h4191;
      vcd_write_val(sim_hdl, num++, DEF_upd__h4403, 2u);
      backing.DEF_upd__h4403 = DEF_upd__h4403;
      vcd_write_val(sim_hdl, num++, DEF_useLocalVec_BIT_0___h3745, 1u);
      backing.DEF_useLocalVec_BIT_0___h3745 = DEF_useLocalVec_BIT_0___h3745;
      vcd_write_val(sim_hdl, num++, DEF_useLocalVec_BIT_1___h3768, 1u);
      backing.DEF_useLocalVec_BIT_1___h3768 = DEF_useLocalVec_BIT_1___h3768;
      vcd_write_val(sim_hdl, num++, DEF_useLocalVec__h3767, 2u);
      backing.DEF_useLocalVec__h3767 = DEF_useLocalVec__h3767;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1502, 2u);
      backing.DEF_x_wget__h1502 = DEF_x_wget__h1502;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h1551, 2u);
      backing.DEF_x_wget__h1551 = DEF_x_wget__h1551;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h906, 2u);
      backing.DEF_x_wget__h906 = DEF_x_wget__h906;
      vcd_write_val(sim_hdl, num++, DEF_x_wget__h955, 2u);
      backing.DEF_x_wget__h955 = DEF_x_wget__h955;
    }
}

void MOD_mkTourPred::vcd_prims(tVCDDumpType dt, MOD_mkTourPred &backing)
{
  INST_choiceBht.dump_VCD(dt, backing.INST_choiceBht);
  INST_globalBht.dump_VCD(dt, backing.INST_globalBht);
  INST_globalTakenVec.dump_VCD(dt, backing.INST_globalTakenVec);
  INST_localBht.dump_VCD(dt, backing.INST_localBht);
  INST_localHistTab.dump_VCD(dt, backing.INST_localHistTab);
  INST_pcIndex.dump_VCD(dt, backing.INST_pcIndex);
  INST_pc_reg.dump_VCD(dt, backing.INST_pc_reg);
  INST_predCnt_lat_0.dump_VCD(dt, backing.INST_predCnt_lat_0);
  INST_predCnt_lat_1.dump_VCD(dt, backing.INST_predCnt_lat_1);
  INST_predCnt_lat_2.dump_VCD(dt, backing.INST_predCnt_lat_2);
  INST_predCnt_rl.dump_VCD(dt, backing.INST_predCnt_rl);
  INST_predRes_lat_0.dump_VCD(dt, backing.INST_predRes_lat_0);
  INST_predRes_lat_1.dump_VCD(dt, backing.INST_predRes_lat_1);
  INST_predRes_lat_2.dump_VCD(dt, backing.INST_predRes_lat_2);
  INST_predRes_rl.dump_VCD(dt, backing.INST_predRes_rl);
  INST_prevGHist.dump_VCD(dt, backing.INST_prevGHist);
  INST_useLocalVec.dump_VCD(dt, backing.INST_useLocalVec);
}

void MOD_mkTourPred::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTourPred &backing)
{
  INST_gHistReg.dump_VCD(dt, levels, backing.INST_gHistReg);
}
