/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __module_prepareBoundsCheck_h__
#define __module_prepareBoundsCheck_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the module_prepareBoundsCheck module */
class MOD_module_prepareBoundsCheck : public Module {
 
 /* Clock handles */
 private:
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_module_prepareBoundsCheck(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
 
 /* Port definitions */
 public:
  tUWide PORT_prepareBoundsCheck_a;
  tUWide PORT_prepareBoundsCheck_b;
  tUWide PORT_prepareBoundsCheck_pcc;
  tUWide PORT_prepareBoundsCheck_ddc;
  tUWide PORT_prepareBoundsCheck;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_ret__h1242;
  tUWide DEF_ret__h3075;
  tUWide DEF_x__h2870;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
  tUWide DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
  tUWide DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
  tUWide DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
  tUWide DEF_x__h1228;
  tUWide DEF_result__h1833;
  tUWide DEF_result__h3609;
  tUWide DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67;
  tUWide DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132;
  tUWide DEF_addTop__h1240;
  tUWide DEF_addTop__h3073;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161;
  tUWide DEF__0_CONCAT_prepareBoundsCheck_size___d162;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158;
  tUWide DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50;
  tUWide DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131;
  tUWide DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172;
  tUWide DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUWide METH_prepareBoundsCheck(tUWide ARG_prepareBoundsCheck_a,
				 tUWide ARG_prepareBoundsCheck_b,
				 tUWide ARG_prepareBoundsCheck_pcc,
				 tUWide ARG_prepareBoundsCheck_ddc,
				 tUInt64 ARG_prepareBoundsCheck_vaddr,
				 tUInt8 ARG_prepareBoundsCheck_size,
				 tUInt64 ARG_prepareBoundsCheck_toCheck);
  tUInt8 METH_RDY_prepareBoundsCheck();
 
 /* Reset routines */
 public:
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_prepareBoundsCheck &backing);
  void vcd_defs(tVCDDumpType dt, MOD_module_prepareBoundsCheck &backing);
};

#endif /* ifndef __module_prepareBoundsCheck_h__ */
