/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __module_specialRWALU_h__
#define __module_specialRWALU_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the module_specialRWALU module */
class MOD_module_specialRWALU : public Module {
 
 /* Clock handles */
 private:
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_module_specialRWALU(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
 
 /* Port definitions */
 public:
  tUWide PORT_specialRWALU_cap;
  tUWide PORT_specialRWALU_oldCap;
  tUWide PORT_specialRWALU;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_specialRWALU_oldCap_BITS_81_TO_10___d122;
  tUWide DEF_specialRWALU_cap_BITS_81_TO_10___d123;
  tUWide DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124;
  tUWide DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUWide METH_specialRWALU(tUWide ARG_specialRWALU_cap,
			   tUWide ARG_specialRWALU_oldCap,
			   tUInt8 ARG_specialRWALU_scrType);
  tUInt8 METH_RDY_specialRWALU();
 
 /* Reset routines */
 public:
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_specialRWALU &backing);
  void vcd_defs(tVCDDumpType dt, MOD_module_specialRWALU &backing);
};

#endif /* ifndef __module_specialRWALU_h__ */
