/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */

/* Generation options: */
#ifndef __module_execFpuSimple_h__
#define __module_execFpuSimple_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the module_execFpuSimple module */
class MOD_module_execFpuSimple : public Module {
 
 /* Clock handles */
 private:
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
 
 /* Constructor */
 public:
  MOD_module_execFpuSimple(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
 
 /* Port definitions */
 public:
  tUWide PORT_execFpuSimple;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_int_val_BITS_117_TO_2___h105073;
  tUWide DEF_int_val__h104757;
  tUWide DEF_int_val_BITS_88_TO_2___h6032;
  tUWide DEF_int_val__h5744;
  tUWide DEF_IF_1075_MINUS_0_CONCAT_execFpuSimple_rVal1_BIT_ETC___d172;
  tUWide DEF_int_val_rnd__h104761;
  tUWide DEF_int_val_rnd__h5748;
  tUWide DEF_IF_1075_MINUS_0_CONCAT_execFpuSimple_rVal1_BIT_ETC___d137;
  tUWide DEF_IF_1075_MINUS_0_CONCAT_execFpuSimple_rVal1_BIT_ETC___d139;
  tUWide DEF_shifted__h104789;
  tUWide DEF__0b1_CONCAT_execFpuSimple_rVal1_BITS_51_TO_0_3__ETC___d125;
  tUWide DEF__0b1_CONCAT_execFpuSimple_rVal1_BITS_51_TO_0_3__ETC___d126;
  tUWide DEF_shifted_out_mask__h106649;
  tUWide DEF_INV_332306998946228968225951765070086143_SRL_I_ETC___d129;
  tUWide DEF_INV_332306998946228968225951765070086143_SL_IF_ETC___d131;
  tUWide DEF_IF_NOT_IF_1075_MINUS_0_CONCAT_execFpuSimple_rV_ETC___d170;
  tUWide DEF_IF_150_MINUS_0_CONCAT_IF_execFpuSimple_rVal1_B_ETC___d2769;
  tUWide DEF_IF_150_MINUS_0_CONCAT_IF_execFpuSimple_rVal1_B_ETC___d2771;
  tUWide DEF_shifted__h5776;
  tUWide DEF__0b1_CONCAT_IF_execFpuSimple_rVal1_BITS_63_TO_3_ETC___d2757;
  tUWide DEF__0b1_CONCAT_IF_execFpuSimple_rVal1_BITS_63_TO_3_ETC___d2758;
  tUWide DEF_shifted_out_mask__h5777;
  tUWide DEF_INV_618970019642690137449562111_SRL_IF_150_MIN_ETC___d2761;
  tUWide DEF_INV_618970019642690137449562111_SL_IF_150_MINU_ETC___d2763;
  tUWide DEF_IF_NOT_IF_150_MINUS_0_CONCAT_IF_execFpuSimple__ETC___d2788;
  tUWide DEF_x__h105022;
  tUWide DEF_x__h5981;
  tUWide DEF_x__h106894;
  tUWide DEF_x__h106917;
  tUWide DEF_x__h5994;
  tUWide DEF_x__h6017;
  tUWide DEF_int_val__h104756;
  tUWide DEF_int_val__h5743;
  tUWide DEF_y__h104976;
  tUWide DEF_y__h105071;
  tUWide DEF_y__h5935;
  tUWide DEF_y__h6030;
  tUWide DEF_IF_execFpuSimple_fpu_inst_BITS_8_TO_4_EQ_8_OR__ETC___d2603;
  tUWide DEF_IF_execFpuSimple_fpu_inst_BITS_8_TO_4_EQ_8_OR__ETC___d4940;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUWide METH_execFpuSimple(tUInt32 ARG_execFpuSimple_fpu_inst,
			    tUInt64 ARG_execFpuSimple_rVal1,
			    tUInt64 ARG_execFpuSimple_rVal2);
  tUInt8 METH_RDY_execFpuSimple();
 
 /* Reset routines */
 public:
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_execFpuSimple &backing);
  void vcd_defs(tVCDDumpType dt, MOD_module_execFpuSimple &backing);
};

#endif /* ifndef __module_execFpuSimple_h__ */
