/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_brAddrCalc.h"


/* Constructor */
MOD_module_brAddrCalc::MOD_module_brAddrCalc(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231(161u),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209(150u),
    DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166(161u),
    DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142(150u),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208(72u),
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141(72u)
{
  PORT_brAddrCalc_pc.setSize(161u);
  PORT_brAddrCalc_pc.clear();
  PORT_brAddrCalc_val.setSize(161u);
  PORT_brAddrCalc_val.clear();
  PORT_brAddrCalc.setSize(161u);
  PORT_brAddrCalc.clear();
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_brAddrCalc::init_symbols_0()
{
  init_symbol(&symbols[0u], "brAddrCalc", SYM_PORT, &PORT_brAddrCalc, 161u);
  init_symbol(&symbols[1u], "brAddrCalc_pc", SYM_PORT, &PORT_brAddrCalc_pc, 161u);
  init_symbol(&symbols[2u], "brAddrCalc_val", SYM_PORT, &PORT_brAddrCalc_val, 161u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_brAddrCalc::METH_brAddrCalc(tUWide ARG_brAddrCalc_pc,
					      tUWide ARG_brAddrCalc_val,
					      tUInt8 ARG_brAddrCalc_iType,
					      tUInt64 ARG_brAddrCalc_imm,
					      tUInt8 ARG_brAddrCalc_taken,
					      tUInt32 ARG_brAddrCalc_orig_inst,
					      tUInt8 ARG_brAddrCalc_cap)
{
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92;
  tUInt64 DEF_x__h343;
  tUInt64 DEF_highBitsfilter__h315;
  tUInt64 DEF_addBase__h2098;
  tUInt8 DEF_repBound__h2680;
  tUInt8 DEF_repBound__h2690;
  tUInt64 DEF_signBits__h313;
  tUInt8 DEF_x__h1603;
  tUInt8 DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155;
  tUInt8 DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d218;
  tUInt8 DEF_brAddrCalc_iType_EQ_9___d4;
  tUInt8 DEF_brAddrCalc_iType_EQ_11___d6;
  tUInt8 DEF_brAddrCalc_iType_EQ_13___d8;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150;
  tUInt8 DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151;
  tUInt8 DEF_brAddrCalc_pc_BITS_37_TO_35_12_ULT_brAddrCalc__ETC___d213;
  tUInt8 DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216;
  tUInt8 DEF_brAddrCalc_pc_BITS_23_TO_21_10_ULT_brAddrCalc__ETC___d214;
  tUInt32 DEF_repBoundBits__h322;
  tUInt64 DEF_highOffsetBits__h316;
  tUInt64 DEF_deltaAddrUpper__h1597;
  tUInt64 DEF_deltaAddrHi__h1595;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74;
  tUInt8 DEF__theResult___fst_capFat_flags__h890;
  tUInt8 DEF__theResult___fst_capFat_reserved__h891;
  tUInt8 DEF_x__h2029;
  tUInt8 DEF__theResult___fst_capFat_poison__h892;
  tUInt8 DEF_x__h2030;
  tUInt8 DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96;
  tUInt8 DEF__theResult___fst_tempFields_repBoundTopBits__h1510;
  tUInt8 DEF__theResult___fst_tempFields_repBoundTopBits__h1516;
  tUInt8 DEF__theResult___fst_capFat_perms_soft__h1895;
  tUInt8 DEF__theResult___fst_capFat_perms_soft__h1898;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29;
  tUInt8 DEF__theResult___fst_capFat_pver__h893;
  tUInt8 DEF_thin_pver__h1883;
  tUInt32 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165;
  tUInt32 DEF_brAddrCalc_pc_BITS_23_TO_21_10_MINUS_0b1_11_CO_ETC___d228;
  tUInt32 DEF_inc__h125;
  tUInt32 DEF__theResult___fst_capFat_addrBits__h888;
  tUInt32 DEF__theResult___fst_capFat_addrBits__h899;
  tUInt32 DEF__theResult___fst_capFat_bounds_baseBits__h916;
  tUInt32 DEF__theResult___fst_capFat_bounds_topBits__h915;
  tUInt32 DEF_toBounds_B__h323;
  tUInt32 DEF_toBounds_A__h320;
  tUInt32 DEF_toBounds__h325;
  tUInt32 DEF_toBoundsM1_B__h324;
  tUInt32 DEF_toBoundsM1_A__h321;
  tUInt32 DEF_toBoundsM1__h326;
  tUInt32 DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  tUInt32 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102;
  tUInt32 DEF_x__h2149;
  tUInt32 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117;
  tUInt32 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118;
  tUInt64 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137;
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138;
  tUInt64 DEF_targetAddr_capFat_address__h187;
  tUInt64 DEF_offset___1__h289;
  tUInt64 DEF__theResult___snd_fst__h280;
  tUInt64 DEF__theResult___fst_capFat_address__h887;
  tUInt64 DEF_pointer__h309;
  tUInt64 DEF_ret___1_address__h1784;
  tUInt8 DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36;
  tUInt64 DEF_result_d_address__h1578;
  tUInt8 DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15;
  tUInt64 DEF_address__h126;
  tUInt8 DEF_brAddrCalc_iType_EQ_10___d167;
  tUInt8 DEF_brAddrCalc_pc_BIT_4___d80;
  tUInt8 DEF_x__h2337;
  tUInt8 DEF_x__h2339;
  tUInt8 DEF_brAddrCalc_pc_BIT_160___d72;
  tUInt8 DEF_x__h589;
  tUInt8 DEF_x__h584;
  tUInt8 DEF_x__h592;
  tUInt8 DEF_x__h816;
  tUInt8 DEF_pc_tempFields_repBoundTopBits__h1504;
  tUInt8 DEF_bb__h2688;
  tUInt8 DEF_tb__h2687;
  tUInt8 DEF_pc_capFat_perms_soft__h1892;
  tUInt8 DEF_val_tempFields_repBoundTopBits__h1492;
  tUInt8 DEF_val_capFat_perms_soft__h497;
  tUInt8 DEF_bb__h2678;
  tUInt32 DEF__theResult___fst_capFat_bounds_topBits__h918;
  tUInt8 DEF_tb__h2677;
  tUInt8 DEF_x_BITS_13_TO_11___h1661;
  tUInt8 DEF_ab__h2679;
  tUInt8 DEF_ab__h2689;
  tUInt8 DEF_x__h2546;
  tUInt8 DEF_thin_pver__h2316;
  tUInt8 DEF_val_capFat_pver__h480;
  tUInt32 DEF_thin_otype__h2317;
  tUInt32 DEF__theResult___fst_capFat_bounds_baseBits__h919;
  tUInt32 DEF_x_BITS_10_TO_0___h1484;
  tUInt32 DEF_pc_capFat_bounds_baseBits__h913;
  tUInt32 DEF_pc_capFat_bounds_topBits__h912;
  tUInt32 DEF_pc_capFat_addrBits__h877;
  tUInt32 DEF_val_capFat_bounds_baseBits__h624;
  tUInt32 DEF_val_capFat_bounds_topBits__h623;
  tUInt32 DEF_val_capFat_addrBits__h475;
  tUInt64 DEF_x__h1451;
  tUInt32 DEF_offsetBits__h319;
  tUInt64 DEF_x__h2487;
  tUInt32 DEF_targetAddr_capFat_addrBits__h188;
  tUInt64 DEF_x__h2518;
  tUInt32 DEF_cap_capFat_addrBits__h203;
  tUInt32 DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  tUInt64 DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  tUInt64 DEF_highOffsetBits__h314;
  tUInt64 DEF__theResult___fst_capFat_address__h898;
  tUInt64 DEF_x__h1752;
  tUInt64 DEF_thin_address__h1886;
  tUInt64 DEF_cap_address__h2279;
  tUInt64 DEF_cap_address__h415;
  tUInt8 DEF_x__h2031;
  tUInt8 DEF_x__h2338;
  PORT_brAddrCalc_pc = ARG_brAddrCalc_pc;
  PORT_brAddrCalc_val = ARG_brAddrCalc_val;
  DEF_x__h2338 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 31u, 1u);
  DEF_cap_address__h415 = primExtract64(64u, 161u, ARG_brAddrCalc_val, 32u, 159u, 32u, 96u);
  DEF_cap_address__h2279 = primExtract64(64u, 161u, ARG_brAddrCalc_pc, 32u, 159u, 32u, 96u);
  DEF_brAddrCalc_pc_BITS_44_TO_10___d136 = primExtract64(35u,
							 161u,
							 ARG_brAddrCalc_pc,
							 32u,
							 44u,
							 32u,
							 10u);
  DEF_brAddrCalc_pc_BITS_81_TO_66___d116 = ARG_brAddrCalc_pc.get_bits_in_word32(2u, 2u, 16u);
  DEF_val_capFat_addrBits__h475 = ARG_brAddrCalc_val.get_bits_in_word32(2u, 18u, 14u);
  DEF_val_capFat_bounds_topBits__h623 = primExtract32(14u,
						      161u,
						      ARG_brAddrCalc_val,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_val_capFat_bounds_baseBits__h624 = ARG_brAddrCalc_val.get_bits_in_word32(0u, 10u, 14u);
  DEF_pc_capFat_bounds_topBits__h912 = primExtract32(14u,
						     161u,
						     ARG_brAddrCalc_pc,
						     32u,
						     37u,
						     32u,
						     24u);
  DEF_pc_capFat_addrBits__h877 = ARG_brAddrCalc_pc.get_bits_in_word32(2u, 18u, 14u);
  DEF_pc_capFat_bounds_baseBits__h913 = ARG_brAddrCalc_pc.get_bits_in_word32(0u, 10u, 14u);
  DEF_thin_otype__h2317 = ARG_brAddrCalc_pc.get_bits_in_word32(1u, 13u, 10u);
  DEF_val_capFat_pver__h480 = ARG_brAddrCalc_val.get_bits_in_word8(1u, 23u, 8u);
  DEF_thin_pver__h2316 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 23u, 8u);
  DEF_x__h2546 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 6u, 6u);
  DEF_val_capFat_perms_soft__h497 = ARG_brAddrCalc_val.get_bits_in_word8(2u, 14u, 3u);
  DEF_val_tempFields_repBoundTopBits__h1492 = ARG_brAddrCalc_val.get_bits_in_word8(0u, 7u, 3u);
  DEF_pc_capFat_perms_soft__h1892 = ARG_brAddrCalc_pc.get_bits_in_word8(2u, 14u, 3u);
  DEF_tb__h2687 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 3u, 3u);
  DEF_bb__h2688 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 21u, 3u);
  DEF_pc_tempFields_repBoundTopBits__h1504 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 7u, 3u);
  DEF_x__h584 = ARG_brAddrCalc_val.get_bits_in_word8(2u, 0u, 1u);
  DEF_x__h592 = ARG_brAddrCalc_val.get_bits_in_word8(2u, 1u, 1u);
  DEF_x__h589 = ARG_brAddrCalc_val.get_bits_in_word8(1u, 31u, 1u);
  DEF_brAddrCalc_pc_BIT_160___d72 = ARG_brAddrCalc_pc.get_bits_in_word8(5u, 0u, 1u);
  DEF_x__h2339 = ARG_brAddrCalc_pc.get_bits_in_word8(2u, 1u, 1u);
  DEF_x__h2337 = ARG_brAddrCalc_pc.get_bits_in_word8(2u, 0u, 1u);
  DEF_brAddrCalc_pc_BIT_4___d80 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 4u, 1u);
  DEF_brAddrCalc_iType_EQ_10___d167 = ARG_brAddrCalc_iType == (tUInt8)10u;
  DEF__theResult___fst_capFat_address__h887 = ARG_brAddrCalc_cap ? DEF_cap_address__h415 : DEF_cap_address__h2279;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_address__h898 = DEF__theResult___fst_capFat_address__h887;
    break;
  default:
    DEF__theResult___fst_capFat_address__h898 = DEF_cap_address__h2279;
  }
  DEF_x__h1752 = (tUInt64)(DEF__theResult___fst_capFat_address__h898 >> 14u);
  DEF_offset___1__h289 = DEF_cap_address__h415 + ARG_brAddrCalc_imm;
  DEF__theResult___snd_fst__h280 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_imm : DEF_offset___1__h289;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 = DEF__theResult___snd_fst__h280;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 = ARG_brAddrCalc_imm;
  }
  DEF_highOffsetBits__h314 = (tUInt64)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 >> 14u);
  DEF_x__h816 = (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 >> 63u);
  DEF_pointer__h309 = DEF__theResult___fst_capFat_address__h898 + DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137 = ARG_brAddrCalc_cap ? primExtract64(35u,
												     161u,
												     ARG_brAddrCalc_val,
												     32u,
												     44u,
												     32u,
												     10u) : DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 = DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word32(2u,
															     2u,
															     16u) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 = DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  }
  DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101 = 65535u & ((((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(0u,
															    0u,
															    2u))) << 14u) | DEF_pc_capFat_bounds_baseBits__h913);
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102 = ARG_brAddrCalc_cap ? 65535u & ((((tUInt32)(ARG_brAddrCalc_val.get_bits_in_word8(0u,
																		  0u,
																		  2u))) << 14u) | DEF_val_capFat_bounds_baseBits__h624) : DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_x__h2149 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102;
    break;
  default:
    DEF_x__h2149 = DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  }
  DEF__theResult___fst_capFat_bounds_topBits__h915 = ARG_brAddrCalc_cap ? DEF_val_capFat_bounds_topBits__h623 : DEF_pc_capFat_bounds_topBits__h912;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_bounds_topBits__h918 = DEF__theResult___fst_capFat_bounds_topBits__h915;
    break;
  default:
    DEF__theResult___fst_capFat_bounds_topBits__h918 = DEF_pc_capFat_bounds_topBits__h912;
  }
  DEF_tb__h2677 = (tUInt8)(DEF__theResult___fst_capFat_bounds_topBits__h918 >> 11u);
  DEF__theResult___fst_capFat_bounds_baseBits__h916 = ARG_brAddrCalc_cap ? DEF_val_capFat_bounds_baseBits__h624 : DEF_pc_capFat_bounds_baseBits__h913;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_bounds_baseBits__h919 = DEF__theResult___fst_capFat_bounds_baseBits__h916;
    break;
  default:
    DEF__theResult___fst_capFat_bounds_baseBits__h919 = DEF_pc_capFat_bounds_baseBits__h913;
  }
  DEF_x_BITS_10_TO_0___h1484 = (tUInt32)(2047u & DEF__theResult___fst_capFat_bounds_baseBits__h919);
  DEF_bb__h2678 = (tUInt8)(DEF__theResult___fst_capFat_bounds_baseBits__h919 >> 11u);
  DEF_toBoundsM1_A__h321 = 16383u & ((((tUInt32)((tUInt8)6u)) << 11u) | (2047u & ~DEF_x_BITS_10_TO_0___h1484));
  DEF_toBounds_A__h320 = 16383u & (14336u - (16383u & ((((tUInt32)((tUInt8)0u)) << 11u) | DEF_x_BITS_10_TO_0___h1484)));
  DEF__theResult___fst_capFat_addrBits__h888 = ARG_brAddrCalc_cap ? DEF_val_capFat_addrBits__h475 : DEF_pc_capFat_addrBits__h877;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_addrBits__h899 = DEF__theResult___fst_capFat_addrBits__h888;
    break;
  default:
    DEF__theResult___fst_capFat_addrBits__h899 = DEF_pc_capFat_addrBits__h877;
  }
  DEF_inc__h125 = ((tUInt8)((tUInt8)3u & ARG_brAddrCalc_orig_inst)) == (tUInt8)3u ? 4u : 2u;
  DEF_address__h126 = DEF_cap_address__h2279 + primSignExt64(64u, 12u, (tUInt32)(DEF_inc__h125));
  DEF_x__h2518 = primShiftR64(64u, 64u, (tUInt64)(DEF_address__h126), 6u, (tUInt8)(DEF_x__h2546));
  DEF_cap_capFat_addrBits__h203 = (tUInt32)(16383u & DEF_x__h2518);
  DEF_ab__h2689 = (tUInt8)((tUInt8)7u & (DEF_x__h2518 >> 11u));
  DEF__theResult___fst_capFat_pver__h893 = ARG_brAddrCalc_cap ? DEF_val_capFat_pver__h480 : DEF_thin_pver__h2316;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_thin_pver__h1883 = DEF__theResult___fst_capFat_pver__h893;
    break;
  default:
    DEF_thin_pver__h1883 = DEF_thin_pver__h2316;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(1u,
															   6u,
															   6u) : DEF_x__h2546;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 = DEF_x__h2546;
  }
  DEF_x__h1451 = primShiftR64(64u,
			      64u,
			      (tUInt64)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21),
			      6u,
			      (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_offsetBits__h319 = (tUInt32)(16383u & DEF_x__h1451);
  DEF_x_BITS_13_TO_11___h1661 = (tUInt8)((tUInt8)7u & (DEF_x__h1451 >> 11u));
  DEF__theResult___fst_capFat_perms_soft__h1895 = ARG_brAddrCalc_cap ? DEF_val_capFat_perms_soft__h497 : DEF_pc_capFat_perms_soft__h1892;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_perms_soft__h1898 = DEF__theResult___fst_capFat_perms_soft__h1895;
    break;
  default:
    DEF__theResult___fst_capFat_perms_soft__h1898 = DEF_pc_capFat_perms_soft__h1892;
  }
  DEF__theResult___fst_tempFields_repBoundTopBits__h1510 = ARG_brAddrCalc_cap ? DEF_val_tempFields_repBoundTopBits__h1492 : DEF_pc_tempFields_repBoundTopBits__h1504;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_tempFields_repBoundTopBits__h1516 = DEF__theResult___fst_tempFields_repBoundTopBits__h1510;
    break;
  default:
    DEF__theResult___fst_tempFields_repBoundTopBits__h1516 = DEF_pc_tempFields_repBoundTopBits__h1504;
  }
  DEF__theResult___fst_capFat_poison__h892 = ARG_brAddrCalc_cap ? DEF_x__h589 : DEF_x__h2338;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_x__h2030 = DEF__theResult___fst_capFat_poison__h892;
    break;
  default:
    DEF_x__h2030 = DEF_x__h2338;
  }
  DEF__theResult___fst_capFat_reserved__h891 = ARG_brAddrCalc_cap ? DEF_x__h584 : DEF_x__h2337;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_x__h2029 = DEF__theResult___fst_capFat_reserved__h891;
    break;
  default:
    DEF_x__h2029 = DEF_x__h2337;
  }
  DEF__theResult___fst_capFat_flags__h890 = ARG_brAddrCalc_cap ? DEF_x__h592 : DEF_x__h2339;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_x__h2031 = DEF__theResult___fst_capFat_flags__h890;
    break;
  default:
    DEF_x__h2031 = DEF_x__h2339;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(5u,
															   0u,
															   1u) : DEF_brAddrCalc_pc_BIT_160___d72;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 = DEF_brAddrCalc_pc_BIT_160___d72;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(0u,
															   4u,
															   1u) : DEF_brAddrCalc_pc_BIT_4___d80;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82 = DEF_brAddrCalc_pc_BIT_4___d80;
  }
  DEF_repBoundBits__h322 = 16383u & (((tUInt32)(DEF__theResult___fst_tempFields_repBoundTopBits__h1516)) << 11u);
  DEF_toBoundsM1_B__h324 = 16383u & (DEF_repBoundBits__h322 + (16383u & ~DEF__theResult___fst_capFat_addrBits__h899));
  DEF_toBounds_B__h323 = 16383u & (DEF_repBoundBits__h322 - DEF__theResult___fst_capFat_addrBits__h899);
  DEF_brAddrCalc_iType_EQ_13___d8 = ARG_brAddrCalc_iType == (tUInt8)13u;
  DEF_brAddrCalc_iType_EQ_11___d6 = ARG_brAddrCalc_iType == (tUInt8)11u;
  DEF_brAddrCalc_iType_EQ_9___d4 = ARG_brAddrCalc_iType == (tUInt8)9u;
  DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 = ((!DEF_brAddrCalc_iType_EQ_9___d4 && !DEF_brAddrCalc_iType_EQ_11___d6) && !DEF_brAddrCalc_iType_EQ_13___d8) || ARG_brAddrCalc_cap;
  DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 = ((DEF_brAddrCalc_iType_EQ_9___d4 || DEF_brAddrCalc_iType_EQ_11___d6) || DEF_brAddrCalc_iType_EQ_13___d8) && !ARG_brAddrCalc_cap;
  DEF_toBoundsM1__h326 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_toBoundsM1_A__h321 : DEF_toBoundsM1_B__h324;
  DEF_toBounds__h325 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_toBounds_A__h320 : DEF_toBounds_B__h323;
  DEF_highBitsfilter__h315 = primShiftL64(50u,
					  50u,
					  1125899906842623llu,
					  6u,
					  (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_x__h1603 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h1661 < DEF__theResult___fst_tempFields_repBoundTopBits__h1516)) - ((tUInt8)3u & DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82));
  DEF_deltaAddrHi__h1595 = primShiftL64(50u,
					50u,
					(tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h1603))),
					6u,
					(tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_signBits__h313 = primSignExt64(50u, 1u, (tUInt8)(DEF_x__h816));
  DEF_repBound__h2690 = (tUInt8)7u & (DEF_bb__h2688 - (tUInt8)1u);
  DEF_brAddrCalc_pc_BITS_23_TO_21_10_ULT_brAddrCalc__ETC___d214 = DEF_bb__h2688 < DEF_repBound__h2690;
  DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216 = DEF_ab__h2689 < DEF_repBound__h2690;
  DEF_brAddrCalc_pc_BITS_37_TO_35_12_ULT_brAddrCalc__ETC___d213 = DEF_tb__h2687 < DEF_repBound__h2690;
  DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d218 = !DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216;
  DEF_brAddrCalc_pc_BITS_23_TO_21_10_MINUS_0b1_11_CO_ETC___d228 = 1023u & ((((((((tUInt32)(DEF_repBound__h2690)) << 7u) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_37_TO_35_12_ULT_brAddrCalc__ETC___d213)) << 6u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_23_TO_21_10_ULT_brAddrCalc__ETC___d214)) << 5u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216)) << 4u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_37_TO_35_12_ULT_brAddrCalc__ETC___d213 == DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216 ? (tUInt8)0u : (DEF_brAddrCalc_pc_BITS_37_TO_35_12_ULT_brAddrCalc__ETC___d213 && DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d218 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_brAddrCalc_pc_BITS_23_TO_21_10_ULT_brAddrCalc__ETC___d214 == DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d216 ? (tUInt8)0u : (DEF_brAddrCalc_pc_BITS_23_TO_21_10_ULT_brAddrCalc__ETC___d214 && DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d218 ? (tUInt8)1u : (tUInt8)3u)));
  DEF_addBase__h2098 = primShiftL64(64u,
				    64u,
				    (tUInt64)(primSignExt64(64u, 16u, (tUInt32)(DEF_x__h2149))),
				    6u,
				    (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_repBound__h2680 = (tUInt8)7u & (DEF_bb__h2678 - (tUInt8)1u);
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 = DEF_bb__h2678 < DEF_repBound__h2680;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 = DEF_tb__h2677 < DEF_repBound__h2680;
  DEF_x__h343 = DEF_highOffsetBits__h314 ^ DEF_signBits__h313;
  DEF_highOffsetBits__h316 = DEF_x__h343 & DEF_highBitsfilter__h315;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 = DEF_x__h1752 & DEF_highBitsfilter__h315;
  DEF_ret___1_address__h1784 = (((DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 << 14u) | (tUInt64)(0u)) + DEF_addBase__h2098) + DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_result_d_address__h1578 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_ret___1_address__h1784 : DEF_pointer__h309;
  DEF_thin_address__h1886 = DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 ? DEF_result_d_address__h1578 : DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_targetAddr_capFat_address__h187 = (((tUInt64)(DEF_thin_address__h1886 >> 1u)) << 1u) | (tUInt64)((tUInt8)0u);
  DEF_x__h2487 = primShiftR64(64u,
			      64u,
			      (tUInt64)(DEF_targetAddr_capFat_address__h187),
			      6u,
			      (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_targetAddr_capFat_addrBits__h188 = (tUInt32)(16383u & DEF_x__h2487);
  DEF_ab__h2679 = (tUInt8)((tUInt8)7u & (DEF_x__h2487 >> 11u));
  DEF_deltaAddrUpper__h1597 = 1125899906842623llu & ((DEF_highOffsetBits__h314 & DEF_highBitsfilter__h315) - DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 = DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 ? ((DEF_highOffsetBits__h316 == 0llu && (DEF_x__h816 ? !(DEF_offsetBits__h319 < DEF_toBounds__h325) && !(DEF_repBoundBits__h322 == DEF__theResult___fst_capFat_addrBits__h899) : DEF_offsetBits__h319 < DEF_toBoundsM1__h326)) || !(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 < (tUInt8)50u)) && DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 : DEF_deltaAddrHi__h1595 == DEF_deltaAddrUpper__h1597 && DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74;
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 = DEF_ab__h2679 < DEF_repBound__h2680;
  DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 = !DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165 = 1023u & ((((((((tUInt32)(DEF_repBound__h2680)) << 7u) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150)) << 6u)) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151)) << 5u)) | (((tUInt32)(DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153)) << 4u)) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 == DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 ? (tUInt8)0u : (DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 && DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 == DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 ? (tUInt8)0u : (DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 && DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 ? (tUInt8)1u : (tUInt8)3u)));
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.set_bits_in_word((tUInt8)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? 65535u & (((((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(2u,
																										  17u,
																										  1u))) << 15u) | (((tUInt32)(DEF__theResult___fst_capFat_perms_soft__h1898)) << 12u)) | ARG_brAddrCalc_pc.get_bits_in_word32(2u,
																																									      2u,
																																									      12u)) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) >> 8u),
										 2u,
										 0u,
										 8u).set_whole_word((((((((((tUInt32)((tUInt8)((tUInt8)255u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? 65535u & (((((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(2u,
																																      17u,
																																      1u))) << 15u) | (((tUInt32)(DEF__theResult___fst_capFat_perms_soft__h1898)) << 12u)) | ARG_brAddrCalc_pc.get_bits_in_word32(2u,
																																																  2u,
																																																  12u)) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116)))) << 24u) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_x__h2031 : DEF_x__h2339) : DEF_x__h2339)) << 23u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_x__h2029 : DEF_x__h2337) : DEF_x__h2337)) << 22u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_x__h2030 : DEF_x__h2338) : DEF_x__h2338)) << 21u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_thin_pver__h1883 : DEF_thin_pver__h2316) : DEF_thin_pver__h2316)) << 13u)) | ((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? 1023u : DEF_thin_otype__h2317) : DEF_thin_otype__h2317) << 3u)) | (((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(1u,
																																																																																																																																																						     12u,
																																																																																																																																																						     1u))) << 2u)) | (tUInt32)((tUInt8)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 : DEF_x__h2546) : DEF_x__h2546) >> 4u)),
												    1u).set_whole_word((((tUInt32)((tUInt8)((tUInt8)15u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 : DEF_x__h2546) : DEF_x__h2546)))) << 28u) | primExtract32(28u,
																																									       161u,
																																									       ARG_brAddrCalc_pc,
																																									       32u,
																																									       37u,
																																									       32u,
																																									       10u),
														       0u);
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209.set_bits_in_word((tUInt32)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h187 : DEF_address__h126) : DEF_address__h126) >> 42u),
										 4u,
										 0u,
										 22u).set_whole_word((tUInt32)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h187 : DEF_address__h126) : DEF_address__h126) >> 10u),
												     3u).set_whole_word(((((tUInt32)(1023u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h187 : DEF_address__h126) : DEF_address__h126))) << 22u) | ((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_addrBits__h188 : DEF_cap_capFat_addrBits__h203) : DEF_cap_capFat_addrBits__h203) << 8u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.get_bits_in_word8(2u,
																																																																					     0u,
																																																																					     8u)),
															2u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.get_whole_word(0u),
																			      0u);
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231.build_concat(8589934591llu & ((((tUInt64)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 : DEF_brAddrCalc_pc_BIT_160___d72) : DEF_brAddrCalc_pc_BIT_160___d72)) << 32u) | (tUInt64)(primExtract32(32u,
																																									    150u,
																																									    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209,
																																									    32u,
																																									    149u,
																																									    32u,
																																									    118u))),
									     128u,
									     33u).set_whole_word(primExtract32(32u,
													       150u,
													       DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209,
													       32u,
													       117u,
													       32u,
													       86u),
												 3u).set_whole_word(primExtract32(32u,
																  150u,
																  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209,
																  32u,
																  85u,
																  32u,
																  54u),
														    2u).set_whole_word(primExtract32(32u,
																		     150u,
																		     DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209,
																		     32u,
																		     53u,
																		     32u,
																		     22u),
																       1u).set_whole_word((DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209.get_bits_in_word32(0u,
																													    0u,
																													    22u) << 10u) | (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165 : DEF_brAddrCalc_pc_BITS_23_TO_21_10_MINUS_0b1_11_CO_ETC___d228) : DEF_brAddrCalc_pc_BITS_23_TO_21_10_MINUS_0b1_11_CO_ETC___d228),
																			  0u);
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.set_bits_in_word((tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 >> 8u),
										 2u,
										 0u,
										 8u).set_whole_word(((((((((tUInt32)((tUInt8)((tUInt8)255u & DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118))) << 24u) | (((tUInt32)(DEF_x__h2031)) << 23u)) | (((tUInt32)(DEF_x__h2029)) << 22u)) | (((tUInt32)(DEF_x__h2030)) << 21u)) | (((tUInt32)(DEF_thin_pver__h1883)) << 13u)) | (1023u << 3u)) | (tUInt32)((tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 >> 32u)),
												    1u).set_whole_word((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138),
														       0u);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142.set_bits_in_word((tUInt32)(DEF_targetAddr_capFat_address__h187 >> 42u),
										 4u,
										 0u,
										 22u).set_whole_word((tUInt32)(DEF_targetAddr_capFat_address__h187 >> 10u),
												     3u).set_whole_word(((((tUInt32)(1023u & DEF_targetAddr_capFat_address__h187)) << 22u) | (DEF_targetAddr_capFat_addrBits__h188 << 8u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_bits_in_word8(2u,
																																								       0u,
																																								       8u)),
															2u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_whole_word(0u),
																			      0u);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166.build_concat(8589934591llu & ((((tUInt64)(DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96)) << 32u) | (tUInt64)(primExtract32(32u,
																									   150u,
																									   DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																									   32u,
																									   149u,
																									   32u,
																									   118u))),
									     128u,
									     33u).set_whole_word(primExtract32(32u,
													       150u,
													       DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
													       32u,
													       117u,
													       32u,
													       86u),
												 3u).set_whole_word(primExtract32(32u,
																  150u,
																  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																  32u,
																  85u,
																  32u,
																  54u),
														    2u).set_whole_word(primExtract32(32u,
																		     150u,
																		     DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																		     32u,
																		     53u,
																		     32u,
																		     22u),
																       1u).set_whole_word((DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142.get_bits_in_word32(0u,
																													    0u,
																													    22u) << 10u) | DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165,
																			  0u);
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)12u:
  case (tUInt8)13u:
    PORT_brAddrCalc = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
    break;
  default:
    PORT_brAddrCalc = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231;
  }
  return PORT_brAddrCalc;
}

tUInt8 MOD_module_brAddrCalc::METH_RDY_brAddrCalc()
{
  tUInt8 PORT_RDY_brAddrCalc;
  tUInt8 DEF_CAN_FIRE_brAddrCalc;
  DEF_CAN_FIRE_brAddrCalc = (tUInt8)1u;
  PORT_RDY_brAddrCalc = DEF_CAN_FIRE_brAddrCalc;
  return PORT_RDY_brAddrCalc;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_brAddrCalc::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_brAddrCalc::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 9u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142", 150u);
  vcd_write_def(sim_hdl, num++, "IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166", 161u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208", 72u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209", 150u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231", 161u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141", 72u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc", 161u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc_pc", 161u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc_val", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_brAddrCalc::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_module_brAddrCalc &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_brAddrCalc::vcd_defs(tVCDDumpType dt, MOD_module_brAddrCalc &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 150u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 150u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142) != DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142, 150u);
	backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142;
      }
      ++num;
      if ((backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166) != DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166, 161u);
	backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208, 72u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209, 150u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231, 161u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141) != DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141, 72u);
	backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141 = DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141;
      }
      ++num;
      if ((backing.PORT_brAddrCalc) != PORT_brAddrCalc)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc, 161u);
	backing.PORT_brAddrCalc = PORT_brAddrCalc;
      }
      ++num;
      if ((backing.PORT_brAddrCalc_pc) != PORT_brAddrCalc_pc)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc_pc, 161u);
	backing.PORT_brAddrCalc_pc = PORT_brAddrCalc_pc;
      }
      ++num;
      if ((backing.PORT_brAddrCalc_val) != PORT_brAddrCalc_val)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc_val, 161u);
	backing.PORT_brAddrCalc_val = PORT_brAddrCalc_val;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142, 150u);
      backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142;
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166, 161u);
      backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208, 72u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209, 150u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d209;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231, 161u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d231;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141, 72u);
      backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141 = DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc, 161u);
      backing.PORT_brAddrCalc = PORT_brAddrCalc;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc_pc, 161u);
      backing.PORT_brAddrCalc_pc = PORT_brAddrCalc_pc;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc_val, 161u);
      backing.PORT_brAddrCalc_val = PORT_brAddrCalc_val;
    }
}
