/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_capChecksMem.h"


/* Constructor */
MOD_module_capChecksMem::MOD_module_capChecksMem(tSimStateHdl simHdl,
						 char const *name,
						 Module *parent)
  : Module(simHdl, name, parent)
{
  PORT_capChecksMem_auth.setSize(161u);
  PORT_capChecksMem_auth.clear();
  PORT_capChecksMem_data.setSize(161u);
  PORT_capChecksMem_data.clear();
  symbol_count = 2u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_capChecksMem::init_symbols_0()
{
  init_symbol(&symbols[0u], "capChecksMem_auth", SYM_PORT, &PORT_capChecksMem_auth, 161u);
  init_symbol(&symbols[1u], "capChecksMem_data", SYM_PORT, &PORT_capChecksMem_data, 161u);
}


/* Rule actions */


/* Methods */

tUInt32 MOD_module_capChecksMem::METH_capChecksMem(tUWide ARG_capChecksMem_auth,
						   tUWide ARG_capChecksMem_data,
						   tUInt64 ARG_capChecksMem_toCheck,
						   tUInt8 ARG_capChecksMem_mem_func,
						   tUInt32 ARG_capChecksMem_byteOrTagEn)
{
  tUInt8 DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d26;
  tUInt8 DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d64;
  tUInt8 DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d14;
  tUInt8 DEF_NOT_capChecksMem_auth_BIT_160_OR_NOT_capChecks_ETC___d79;
  tUInt8 DEF_capChecksMem_mem_func_EQ_0___d6;
  tUInt8 DEF_capChecksMem_mem_func_EQ_2___d7;
  tUInt8 DEF_capChecksMem_auth_BITS_54_TO_45_EQ_1023___d4;
  tUInt8 DEF_IF_capChecksMem_auth_BIT_160_THEN_IF_capChecks_ETC___d91;
  tUInt8 DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d67;
  tUInt8 DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d29;
  tUInt8 DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d23;
  tUInt8 DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d17;
  tUInt8 DEF_cheri_exc_reg__h1867;
  tUInt8 DEF_capChecksMem_byteOrTagEn_BIT_16___d21;
  tUInt8 DEF_capChecksMem_auth_BIT_160___d1;
  tUInt8 DEF_toCheck_rn1__h1905;
  tUInt32 DEF_x__h174;
  tUInt32 PORT_capChecksMem;
  PORT_capChecksMem_auth = ARG_capChecksMem_auth;
  PORT_capChecksMem_data = ARG_capChecksMem_data;
  DEF_x__h174 = ARG_capChecksMem_auth.get_bits_in_word32(1u, 13u, 10u);
  DEF_toCheck_rn1__h1905 = (tUInt8)((tUInt8)63u & (ARG_capChecksMem_toCheck >> 6u));
  DEF_capChecksMem_auth_BIT_160___d1 = ARG_capChecksMem_auth.get_bits_in_word8(5u, 0u, 1u);
  DEF_capChecksMem_byteOrTagEn_BIT_16___d21 = (tUInt8)(ARG_capChecksMem_byteOrTagEn >> 16u);
  DEF_cheri_exc_reg__h1867 = ((tUInt8)((tUInt8)3u & (ARG_capChecksMem_toCheck >> 19u))) == (tUInt8)0u ? DEF_toCheck_rn1__h1905 : (tUInt8)33u;
  DEF_capChecksMem_auth_BITS_54_TO_45_EQ_1023___d4 = DEF_x__h174 == 1023u;
  DEF_capChecksMem_mem_func_EQ_2___d7 = ARG_capChecksMem_mem_func == (tUInt8)2u;
  DEF_capChecksMem_mem_func_EQ_0___d6 = ARG_capChecksMem_mem_func == (tUInt8)0u;
  DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d14 = (DEF_capChecksMem_mem_func_EQ_0___d6 || DEF_capChecksMem_mem_func_EQ_2___d7) || (!(ARG_capChecksMem_mem_func == (tUInt8)1u) && !(ARG_capChecksMem_mem_func == (tUInt8)3u));
  DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d17 = DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d14 && !ARG_capChecksMem_auth.get_bits_in_word8(2u,
																					  4u,
																					  1u);
  DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d23 = (DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d14 && !ARG_capChecksMem_auth.get_bits_in_word8(2u,
																					   6u,
																					   1u)) && !DEF_capChecksMem_byteOrTagEn_BIT_16___d21;
  DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d26 = !DEF_capChecksMem_mem_func_EQ_0___d6 && !DEF_capChecksMem_mem_func_EQ_2___d7;
  DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d29 = DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d26 && !ARG_capChecksMem_auth.get_bits_in_word8(2u,
																					  5u,
																					  1u);
  DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d64 = (DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d26 && ARG_capChecksMem_data.get_bits_in_word8(5u,
																					  0u,
																					  1u)) && (DEF_capChecksMem_byteOrTagEn_BIT_16___d21 && ((tUInt8)((tUInt8)1u & ARG_capChecksMem_byteOrTagEn) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 1u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 2u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 3u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 4u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 5u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 6u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 7u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 8u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 9u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 10u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 11u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 12u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 13u)) && ((tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 14u)) && (tUInt8)((tUInt8)1u & (ARG_capChecksMem_byteOrTagEn >> 15u))))))))))))))))));
  DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d67 = DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d64 && !ARG_capChecksMem_auth.get_bits_in_word8(2u,
																					  7u,
																					  1u);
  DEF_IF_capChecksMem_auth_BIT_160_THEN_IF_capChecks_ETC___d91 = DEF_capChecksMem_auth_BIT_160___d1 ? (DEF_capChecksMem_auth_BITS_54_TO_45_EQ_1023___d4 ? (DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d17 ? (tUInt8)18u : (DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d23 ? (tUInt8)20u : (DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d29 ? (tUInt8)19u : (DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d67 ? (tUInt8)21u : (tUInt8)22u)))) : (tUInt8)3u) : (tUInt8)2u;
  DEF_NOT_capChecksMem_auth_BIT_160_OR_NOT_capChecks_ETC___d79 = !DEF_capChecksMem_auth_BIT_160___d1 || (!DEF_capChecksMem_auth_BITS_54_TO_45_EQ_1023___d4 || (DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d17 || (DEF_capChecksMem_mem_func_EQ_0_OR_capChecksMem_mem_ETC___d23 || (DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d29 || (DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d67 || ((DEF_NOT_capChecksMem_mem_func_EQ_0_4_AND_NOT_capCh_ETC___d64 && !ARG_capChecksMem_auth.get_bits_in_word8(2u,
																																																																	     8u,
																																																																	     1u)) && !ARG_capChecksMem_data.get_bits_in_word8(2u,
																																																																							      2u,
																																																																							      1u)))))));
  PORT_capChecksMem = 4095u & (((((tUInt32)(DEF_NOT_capChecksMem_auth_BIT_160_OR_NOT_capChecks_ETC___d79)) << 11u) | (((tUInt32)(DEF_cheri_exc_reg__h1867)) << 5u)) | (tUInt32)(DEF_IF_capChecksMem_auth_BIT_160_THEN_IF_capChecks_ETC___d91));
  return PORT_capChecksMem;
}

tUInt8 MOD_module_capChecksMem::METH_RDY_capChecksMem()
{
  tUInt8 PORT_RDY_capChecksMem;
  tUInt8 DEF_CAN_FIRE_capChecksMem;
  DEF_CAN_FIRE_capChecksMem = (tUInt8)1u;
  PORT_RDY_capChecksMem = DEF_CAN_FIRE_capChecksMem;
  return PORT_RDY_capChecksMem;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_capChecksMem::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_capChecksMem::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 2u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "capChecksMem_auth", 161u);
  vcd_write_def(sim_hdl, num++, "capChecksMem_data", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_capChecksMem::dump_VCD(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_module_capChecksMem &backing)
{
}
