/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_amoExec.h"


/* Literal declarations */
static unsigned int const UWide_literal_96_h0_arr[] = { 0u, 0u, 0u };
static tUWide const UWide_literal_96_h0(96u, UWide_literal_96_h0_arr);
static unsigned int const UWide_literal_128_hffffffffffffffffffffffffffffffff_arr[] = { 4294967295u,
											4294967295u,
											4294967295u,
											4294967295u };
static tUWide const UWide_literal_128_hffffffffffffffffffffffffffffffff(128u,
									UWide_literal_128_hffffffffffffffffffffffffffffffff_arr);
static unsigned int const UWide_literal_128_hffffffff_arr[] = { 4294967295u, 0u, 0u, 0u };
static tUWide const UWide_literal_128_hffffffff(128u, UWide_literal_128_hffffffff_arr);
static unsigned int const UWide_literal_128_hffffffffffffffff_arr[] = { 4294967295u,
									4294967295u,
									0u,
									0u };
static tUWide const UWide_literal_128_hffffffffffffffff(128u,
							UWide_literal_128_hffffffffffffffff_arr);


/* Constructor */
MOD_module_amoExec::MOD_module_amoExec(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    DEF_vIn__h1795(128u),
    DEF_vOld__h1794(128u),
    DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98(128u),
    DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97(128u),
    DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95(128u),
    DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94(128u),
    DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82(128u),
    DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86(128u),
    DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89(128u),
    DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92(128u),
    DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99(128u),
    DEF_tmpData__h640(128u),
    DEF_tmpData__h32(128u),
    DEF_x__h611(128u),
    DEF_x__h700(128u),
    DEF_tmpData__h634(128u),
    DEF_y__h328(128u),
    DEF_x__h610(128u),
    DEF_y__h326(128u),
    DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111(128u),
    DEF_x__h325(128u)
{
  PORT_amoExec_current.setSize(129u);
  PORT_amoExec_current.clear();
  PORT_amoExec_inpt.setSize(129u);
  PORT_amoExec_inpt.clear();
  PORT_amoExec.setSize(129u);
  PORT_amoExec.clear();
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_amoExec::init_symbols_0()
{
  init_symbol(&symbols[0u], "amoExec", SYM_PORT, &PORT_amoExec, 129u);
  init_symbol(&symbols[1u], "amoExec_current", SYM_PORT, &PORT_amoExec_current, 129u);
  init_symbol(&symbols[2u], "amoExec_inpt", SYM_PORT, &PORT_amoExec_inpt, 129u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_amoExec::METH_amoExec(tUInt8 ARG_amoExec_amo_inst,
					tUInt8 ARG_amoExec_wordIdx,
					tUWide ARG_amoExec_current,
					tUWide ARG_amoExec_inpt)
{
  tUInt8 DEF_amoExec_amo_inst_BITS_7_TO_4_EQ_0_AND_amoExec__ETC___d7;
  tUInt8 DEF_shftAmnt__h636;
  tUInt8 DEF_shftAmnt__h37;
  tUInt8 DEF_shftAmnt__h642;
  tUInt32 DEF_x__h1128;
  tUInt8 DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d65;
  tUInt8 DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d68;
  tUInt64 DEF_x__h707;
  tUInt8 DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d35;
  tUInt8 DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d40;
  tUInt8 DEF_amoExec_current_BITS_127_TO_0_SLE_amoExec_inpt_ETC___d93;
  tUInt8 DEF_amoExec_current_BITS_127_TO_0_ULE_amoExec_inpt_ETC___d96;
  tUInt32 DEF_vOld__h1130;
  tUInt64 DEF_vOld__h709;
  tUInt8 DEF_x__h999;
  tUInt8 DEF_amoExec_amo_inst_BITS_3_TO_2___d3;
  tUInt8 DEF_amoExec_amo_inst_BITS_7_TO_4___d1;
  tUInt32 DEF_vIn__h1131;
  tUInt64 DEF_amoExec_current_BITS_63_TO_0___d23;
  tUInt64 DEF_amoExec_current_BITS_127_TO_64___d24;
  tUInt64 DEF_amoExec_inpt_BITS_63_TO_0___d21;
  tUInt64 DEF_amoExec_inpt_BITS_127_TO_64___d83;
  PORT_amoExec_current = ARG_amoExec_current;
  PORT_amoExec_inpt = ARG_amoExec_inpt;
  wop_primExtractWide(128u, 129u, ARG_amoExec_inpt, 32u, 127u, 32u, 0u, DEF_vIn__h1795);
  wop_primExtractWide(128u, 129u, ARG_amoExec_current, 32u, 127u, 32u, 0u, DEF_vOld__h1794);
  DEF_amoExec_inpt_BITS_127_TO_64___d83 = primExtract64(64u,
							129u,
							ARG_amoExec_inpt,
							32u,
							127u,
							32u,
							64u);
  DEF_amoExec_current_BITS_127_TO_64___d24 = primExtract64(64u,
							   129u,
							   ARG_amoExec_current,
							   32u,
							   127u,
							   32u,
							   64u);
  DEF_amoExec_inpt_BITS_63_TO_0___d21 = primExtract64(64u, 129u, ARG_amoExec_inpt, 32u, 63u, 32u, 0u);
  DEF_amoExec_current_BITS_63_TO_0___d23 = primExtract64(64u,
							 129u,
							 ARG_amoExec_current,
							 32u,
							 63u,
							 32u,
							 0u);
  DEF_vIn__h1131 = ARG_amoExec_inpt.get_whole_word(0u);
  DEF_amoExec_amo_inst_BITS_3_TO_2___d3 = (tUInt8)((tUInt8)3u & (ARG_amoExec_amo_inst >> 2u));
  DEF_amoExec_amo_inst_BITS_7_TO_4___d1 = (tUInt8)(ARG_amoExec_amo_inst >> 4u);
  DEF_x__h999 = (tUInt8)(ARG_amoExec_wordIdx >> 1u);
  switch (DEF_x__h999) {
  case (tUInt8)0u:
    DEF_vOld__h709 = DEF_amoExec_current_BITS_63_TO_0___d23;
    break;
  case (tUInt8)1u:
    DEF_vOld__h709 = DEF_amoExec_current_BITS_127_TO_64___d24;
    break;
  default:
    DEF_vOld__h709 = 12297829382473034410llu;
  }
  switch (ARG_amoExec_wordIdx) {
  case (tUInt8)0u:
    DEF_vOld__h1130 = ARG_amoExec_current.get_whole_word(0u);
    break;
  case (tUInt8)1u:
    DEF_vOld__h1130 = ARG_amoExec_current.get_whole_word(1u);
    break;
  case (tUInt8)2u:
    DEF_vOld__h1130 = ARG_amoExec_current.get_whole_word(2u);
    break;
  case (tUInt8)3u:
    DEF_vOld__h1130 = ARG_amoExec_current.get_whole_word(3u);
    break;
  default:
    DEF_vOld__h1130 = 2863311530u;
  }
  DEF_amoExec_current_BITS_127_TO_0_ULE_amoExec_inpt_ETC___d96 = DEF_vOld__h1794 <= DEF_vIn__h1795;
  DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98 = DEF_amoExec_current_BITS_127_TO_0_ULE_amoExec_inpt_ETC___d96 ? DEF_vIn__h1795 : DEF_vOld__h1794;
  DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97 = DEF_amoExec_current_BITS_127_TO_0_ULE_amoExec_inpt_ETC___d96 ? DEF_vOld__h1794 : DEF_vIn__h1795;
  DEF_amoExec_current_BITS_127_TO_0_SLE_amoExec_inpt_ETC___d93 = primSLE8(1u,
									  128u,
									  DEF_vOld__h1794,
									  128u,
									  DEF_vIn__h1795);
  DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95 = DEF_amoExec_current_BITS_127_TO_0_SLE_amoExec_inpt_ETC___d93 ? DEF_vIn__h1795 : DEF_vOld__h1794;
  DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94 = DEF_amoExec_current_BITS_127_TO_0_SLE_amoExec_inpt_ETC___d93 ? DEF_vOld__h1794 : DEF_vIn__h1795;
  DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86.set_whole_word((tUInt32)((DEF_amoExec_current_BITS_127_TO_64___d24 ^ DEF_amoExec_inpt_BITS_127_TO_64___d83) >> 32u),
									      3u).build_concat((((tUInt64)((tUInt32)(DEF_amoExec_current_BITS_127_TO_64___d24 ^ DEF_amoExec_inpt_BITS_127_TO_64___d83))) << 32u) | (tUInt64)((tUInt32)((DEF_amoExec_current_BITS_63_TO_0___d23 ^ DEF_amoExec_inpt_BITS_63_TO_0___d21) >> 32u)),
											       32u,
											       64u).set_whole_word((tUInt32)(DEF_amoExec_current_BITS_63_TO_0___d23 ^ DEF_amoExec_inpt_BITS_63_TO_0___d21),
														   0u);
  wop_add(DEF_vOld__h1794,
	  DEF_vIn__h1795,
	  DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82);
  DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89.set_whole_word((tUInt32)((DEF_amoExec_current_BITS_127_TO_64___d24 & DEF_amoExec_inpt_BITS_127_TO_64___d83) >> 32u),
									      3u).build_concat((((tUInt64)((tUInt32)(DEF_amoExec_current_BITS_127_TO_64___d24 & DEF_amoExec_inpt_BITS_127_TO_64___d83))) << 32u) | (tUInt64)((tUInt32)((DEF_amoExec_current_BITS_63_TO_0___d23 & DEF_amoExec_inpt_BITS_63_TO_0___d21) >> 32u)),
											       32u,
											       64u).set_whole_word((tUInt32)(DEF_amoExec_current_BITS_63_TO_0___d23 & DEF_amoExec_inpt_BITS_63_TO_0___d21),
														   0u);
  DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92.set_whole_word((tUInt32)((DEF_amoExec_current_BITS_127_TO_64___d24 | DEF_amoExec_inpt_BITS_127_TO_64___d83) >> 32u),
									      3u).build_concat((((tUInt64)((tUInt32)(DEF_amoExec_current_BITS_127_TO_64___d24 | DEF_amoExec_inpt_BITS_127_TO_64___d83))) << 32u) | (tUInt64)((tUInt32)((DEF_amoExec_current_BITS_63_TO_0___d23 | DEF_amoExec_inpt_BITS_63_TO_0___d21) >> 32u)),
											       32u,
											       64u).set_whole_word((tUInt32)(DEF_amoExec_current_BITS_63_TO_0___d23 | DEF_amoExec_inpt_BITS_63_TO_0___d21),
														   0u);
  DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98;
  switch (DEF_amoExec_amo_inst_BITS_7_TO_4___d1) {
  case (tUInt8)0u:
    DEF_tmpData__h32 = DEF_vIn__h1795;
    break;
  case (tUInt8)1u:
    DEF_tmpData__h32 = DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82;
    break;
  case (tUInt8)2u:
    DEF_tmpData__h32 = DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86;
    break;
  case (tUInt8)3u:
    DEF_tmpData__h32 = DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89;
    break;
  case (tUInt8)4u:
    DEF_tmpData__h32 = DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92;
    break;
  case (tUInt8)5u:
    DEF_tmpData__h32 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94;
    break;
  case (tUInt8)6u:
    DEF_tmpData__h32 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95;
    break;
  case (tUInt8)7u:
    DEF_tmpData__h32 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97;
    break;
  default:
    DEF_tmpData__h32 = DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99;
  }
  switch (DEF_amoExec_amo_inst_BITS_3_TO_2___d3) {
  case (tUInt8)1u:
    DEF_x__h611 = UWide_literal_128_hffffffffffffffff;
    break;
  case (tUInt8)2u:
    DEF_x__h611 = UWide_literal_128_hffffffff;
    break;
  default:
    DEF_x__h611 = UWide_literal_128_hffffffffffffffffffffffffffffffff;
  }
  DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d40 = DEF_vOld__h709 <= DEF_amoExec_inpt_BITS_63_TO_0___d21;
  DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d35 = primSLE8(1u,
									  64u,
									  (tUInt64)(DEF_vOld__h709),
									  64u,
									  (tUInt64)(DEF_amoExec_inpt_BITS_63_TO_0___d21));
  switch (DEF_amoExec_amo_inst_BITS_7_TO_4___d1) {
  case (tUInt8)0u:
    DEF_x__h707 = DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)1u:
    DEF_x__h707 = DEF_vOld__h709 + DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)2u:
    DEF_x__h707 = DEF_vOld__h709 ^ DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)3u:
    DEF_x__h707 = DEF_vOld__h709 & DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)4u:
    DEF_x__h707 = DEF_vOld__h709 | DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)5u:
    DEF_x__h707 = DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d35 ? DEF_vOld__h709 : DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  case (tUInt8)6u:
    DEF_x__h707 = DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d35 ? DEF_amoExec_inpt_BITS_63_TO_0___d21 : DEF_vOld__h709;
    break;
  case (tUInt8)7u:
    DEF_x__h707 = DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d40 ? DEF_vOld__h709 : DEF_amoExec_inpt_BITS_63_TO_0___d21;
    break;
  default:
    DEF_x__h707 = DEF_SEL_ARR_amoExec_current_BITS_63_TO_0_3_amoExec_ETC___d40 ? DEF_amoExec_inpt_BITS_63_TO_0___d21 : DEF_vOld__h709;
  }
  DEF_tmpData__h634.set_whole_word((tUInt32)(0llu),
				   3u).build_concat((((tUInt64)((tUInt32)(0llu))) << 32u) | (tUInt64)((tUInt32)(DEF_x__h707 >> 32u)),
						    32u,
						    64u).set_whole_word((tUInt32)(DEF_x__h707), 0u);
  DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d68 = DEF_vOld__h1130 <= DEF_vIn__h1131;
  DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d65 = primSLE8(1u,
									  32u,
									  (tUInt32)(DEF_vOld__h1130),
									  32u,
									  (tUInt32)(DEF_vIn__h1131));
  switch (DEF_amoExec_amo_inst_BITS_7_TO_4___d1) {
  case (tUInt8)0u:
    DEF_x__h1128 = DEF_vIn__h1131;
    break;
  case (tUInt8)1u:
    DEF_x__h1128 = DEF_vOld__h1130 + DEF_vIn__h1131;
    break;
  case (tUInt8)2u:
    DEF_x__h1128 = DEF_vOld__h1130 ^ DEF_vIn__h1131;
    break;
  case (tUInt8)3u:
    DEF_x__h1128 = DEF_vOld__h1130 & DEF_vIn__h1131;
    break;
  case (tUInt8)4u:
    DEF_x__h1128 = DEF_vOld__h1130 | DEF_vIn__h1131;
    break;
  case (tUInt8)5u:
    DEF_x__h1128 = DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d65 ? DEF_vOld__h1130 : DEF_vIn__h1131;
    break;
  case (tUInt8)6u:
    DEF_x__h1128 = DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d65 ? DEF_vIn__h1131 : DEF_vOld__h1130;
    break;
  case (tUInt8)7u:
    DEF_x__h1128 = DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d68 ? DEF_vOld__h1130 : DEF_vIn__h1131;
    break;
  default:
    DEF_x__h1128 = DEF_SEL_ARR_amoExec_current_BITS_31_TO_0_5_amoExec_ETC___d68 ? DEF_vIn__h1131 : DEF_vOld__h1130;
  }
  DEF_tmpData__h640.set_whole_word(UWide_literal_96_h0.get_whole_word(2u),
				   3u).set_whole_word(UWide_literal_96_h0.get_whole_word(1u),
						      2u).build_concat((((tUInt64)(UWide_literal_96_h0.get_whole_word(0u))) << 32u) | (tUInt64)(DEF_x__h1128),
								       0u,
								       64u);
  switch (DEF_amoExec_amo_inst_BITS_3_TO_2___d3) {
  case (tUInt8)1u:
    DEF_x__h700 = DEF_tmpData__h634;
    break;
  case (tUInt8)2u:
    DEF_x__h700 = DEF_tmpData__h640;
    break;
  default:
    DEF_x__h700 = DEF_tmpData__h32;
  }
  DEF_shftAmnt__h642 = (tUInt8)255u & (ARG_amoExec_wordIdx << 5u);
  DEF_shftAmnt__h636 = (tUInt8)255u & (DEF_x__h999 << 6u);
  switch (DEF_amoExec_amo_inst_BITS_3_TO_2___d3) {
  case (tUInt8)1u:
    DEF_shftAmnt__h37 = DEF_shftAmnt__h636;
    break;
  case (tUInt8)2u:
    DEF_shftAmnt__h37 = DEF_shftAmnt__h642;
    break;
  default:
    DEF_shftAmnt__h37 = (tUInt8)0u;
  }
  DEF_amoExec_amo_inst_BITS_7_TO_4_EQ_0_AND_amoExec__ETC___d7 = (DEF_amoExec_amo_inst_BITS_7_TO_4___d1 == (tUInt8)0u && DEF_amoExec_amo_inst_BITS_3_TO_2___d3 == (tUInt8)0u) && ARG_amoExec_inpt.get_bits_in_word8(4u,
																										   0u,
																										   1u);
  wop_primShiftLWide(128u, 128u, DEF_x__h611, 8u, (tUInt8)(DEF_shftAmnt__h37), DEF_x__h610);
  wop_inv(DEF_x__h610, DEF_y__h328);
  wop_primShiftLWide(128u, 128u, DEF_x__h700, 8u, (tUInt8)(DEF_shftAmnt__h37), DEF_y__h326);
  wop_and(DEF_vOld__h1794, DEF_y__h328, DEF_x__h325);
  wop_or(DEF_x__h325, DEF_y__h326, DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111);
  PORT_amoExec.build_concat(8589934591llu & ((((tUInt64)(DEF_amoExec_amo_inst_BITS_7_TO_4_EQ_0_AND_amoExec__ETC___d7)) << 32u) | (tUInt64)(DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111.get_whole_word(3u))),
			    96u,
			    33u).set_whole_word(DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111.get_whole_word(2u),
						2u).set_whole_word(DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111.get_whole_word(1u),
								   1u).set_whole_word(DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111.get_whole_word(0u),
										      0u);
  return PORT_amoExec;
}

tUInt8 MOD_module_amoExec::METH_RDY_amoExec()
{
  tUInt8 PORT_RDY_amoExec;
  tUInt8 DEF_CAN_FIRE_amoExec;
  DEF_CAN_FIRE_amoExec = (tUInt8)1u;
  PORT_RDY_amoExec = DEF_CAN_FIRE_amoExec;
  return PORT_RDY_amoExec;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_amoExec::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_amoExec::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 24u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99", 128u);
  vcd_write_def(sim_hdl, num++, "IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94", 128u);
  vcd_write_def(sim_hdl, num++, "IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95", 128u);
  vcd_write_def(sim_hdl, num++, "IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97", 128u);
  vcd_write_def(sim_hdl, num++, "IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86", 128u);
  vcd_write_def(sim_hdl, num++, "tmpData__h32", 128u);
  vcd_write_def(sim_hdl, num++, "tmpData__h634", 128u);
  vcd_write_def(sim_hdl, num++, "tmpData__h640", 128u);
  vcd_write_def(sim_hdl, num++, "vIn__h1795", 128u);
  vcd_write_def(sim_hdl, num++, "vOld__h1794", 128u);
  vcd_write_def(sim_hdl, num++, "x__h325", 128u);
  vcd_write_def(sim_hdl, num++, "x__h610", 128u);
  vcd_write_def(sim_hdl, num++, "x__h611", 128u);
  vcd_write_def(sim_hdl, num++, "x__h700", 128u);
  vcd_write_def(sim_hdl, num++, "y__h326", 128u);
  vcd_write_def(sim_hdl, num++, "y__h328", 128u);
  vcd_write_def(sim_hdl, num++, "amoExec", 129u);
  vcd_write_def(sim_hdl, num++, "amoExec_current", 129u);
  vcd_write_def(sim_hdl, num++, "amoExec_inpt", 129u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_amoExec::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_module_amoExec &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_amoExec::vcd_defs(tVCDDumpType dt, MOD_module_amoExec &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 129u);
    vcd_write_x(sim_hdl, num++, 129u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99) != DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99, 128u);
	backing.DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99 = DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99;
      }
      ++num;
      if ((backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94) != DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94, 128u);
	backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94;
      }
      ++num;
      if ((backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95) != DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95, 128u);
	backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95;
      }
      ++num;
      if ((backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97) != DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97, 128u);
	backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97;
      }
      ++num;
      if ((backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98) != DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98, 128u);
	backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98;
      }
      ++num;
      if ((backing.DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111) != DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111)
      {
	vcd_write_val(sim_hdl, num, DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111, 128u);
	backing.DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111 = DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111;
      }
      ++num;
      if ((backing.DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82) != DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82)
      {
	vcd_write_val(sim_hdl, num, DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82, 128u);
	backing.DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82 = DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82;
      }
      ++num;
      if ((backing.DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89) != DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89)
      {
	vcd_write_val(sim_hdl, num, DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89, 128u);
	backing.DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89 = DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89;
      }
      ++num;
      if ((backing.DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92) != DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92)
      {
	vcd_write_val(sim_hdl, num, DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92, 128u);
	backing.DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92 = DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92;
      }
      ++num;
      if ((backing.DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86) != DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86)
      {
	vcd_write_val(sim_hdl, num, DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86, 128u);
	backing.DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86 = DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86;
      }
      ++num;
      if ((backing.DEF_tmpData__h32) != DEF_tmpData__h32)
      {
	vcd_write_val(sim_hdl, num, DEF_tmpData__h32, 128u);
	backing.DEF_tmpData__h32 = DEF_tmpData__h32;
      }
      ++num;
      if ((backing.DEF_tmpData__h634) != DEF_tmpData__h634)
      {
	vcd_write_val(sim_hdl, num, DEF_tmpData__h634, 128u);
	backing.DEF_tmpData__h634 = DEF_tmpData__h634;
      }
      ++num;
      if ((backing.DEF_tmpData__h640) != DEF_tmpData__h640)
      {
	vcd_write_val(sim_hdl, num, DEF_tmpData__h640, 128u);
	backing.DEF_tmpData__h640 = DEF_tmpData__h640;
      }
      ++num;
      if ((backing.DEF_vIn__h1795) != DEF_vIn__h1795)
      {
	vcd_write_val(sim_hdl, num, DEF_vIn__h1795, 128u);
	backing.DEF_vIn__h1795 = DEF_vIn__h1795;
      }
      ++num;
      if ((backing.DEF_vOld__h1794) != DEF_vOld__h1794)
      {
	vcd_write_val(sim_hdl, num, DEF_vOld__h1794, 128u);
	backing.DEF_vOld__h1794 = DEF_vOld__h1794;
      }
      ++num;
      if ((backing.DEF_x__h325) != DEF_x__h325)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h325, 128u);
	backing.DEF_x__h325 = DEF_x__h325;
      }
      ++num;
      if ((backing.DEF_x__h610) != DEF_x__h610)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h610, 128u);
	backing.DEF_x__h610 = DEF_x__h610;
      }
      ++num;
      if ((backing.DEF_x__h611) != DEF_x__h611)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h611, 128u);
	backing.DEF_x__h611 = DEF_x__h611;
      }
      ++num;
      if ((backing.DEF_x__h700) != DEF_x__h700)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h700, 128u);
	backing.DEF_x__h700 = DEF_x__h700;
      }
      ++num;
      if ((backing.DEF_y__h326) != DEF_y__h326)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h326, 128u);
	backing.DEF_y__h326 = DEF_y__h326;
      }
      ++num;
      if ((backing.DEF_y__h328) != DEF_y__h328)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h328, 128u);
	backing.DEF_y__h328 = DEF_y__h328;
      }
      ++num;
      if ((backing.PORT_amoExec) != PORT_amoExec)
      {
	vcd_write_val(sim_hdl, num, PORT_amoExec, 129u);
	backing.PORT_amoExec = PORT_amoExec;
      }
      ++num;
      if ((backing.PORT_amoExec_current) != PORT_amoExec_current)
      {
	vcd_write_val(sim_hdl, num, PORT_amoExec_current, 129u);
	backing.PORT_amoExec_current = PORT_amoExec_current;
      }
      ++num;
      if ((backing.PORT_amoExec_inpt) != PORT_amoExec_inpt)
      {
	vcd_write_val(sim_hdl, num, PORT_amoExec_inpt, 129u);
	backing.PORT_amoExec_inpt = PORT_amoExec_inpt;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99, 128u);
      backing.DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99 = DEF_IF_amoExec_amo_inst_BITS_7_TO_4_EQ_8_2_THEN_IF_ETC___d99;
      vcd_write_val(sim_hdl, num++, DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94, 128u);
      backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d94;
      vcd_write_val(sim_hdl, num++, DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95, 128u);
      backing.DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95 = DEF_IF_amoExec_current_BITS_127_TO_0_SLE_amoExec_i_ETC___d95;
      vcd_write_val(sim_hdl, num++, DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97, 128u);
      backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d97;
      vcd_write_val(sim_hdl, num++, DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98, 128u);
      backing.DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98 = DEF_IF_amoExec_current_BITS_127_TO_0_ULE_amoExec_i_ETC___d98;
      vcd_write_val(sim_hdl, num++, DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111, 128u);
      backing.DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111 = DEF_amoExec_current_BITS_127_TO_0_AND_INV_IF_amoEx_ETC___d111;
      vcd_write_val(sim_hdl, num++, DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82, 128u);
      backing.DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82 = DEF_amoExec_current_BITS_127_TO_0_PLUS_amoExec_inp_ETC___d82;
      vcd_write_val(sim_hdl, num++, DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89, 128u);
      backing.DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89 = DEF_amoExec_current_BITS_127_TO_64_4_AND_amoExec_i_ETC___d89;
      vcd_write_val(sim_hdl, num++, DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92, 128u);
      backing.DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92 = DEF_amoExec_current_BITS_127_TO_64_4_OR_amoExec_in_ETC___d92;
      vcd_write_val(sim_hdl, num++, DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86, 128u);
      backing.DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86 = DEF_amoExec_current_BITS_127_TO_64_4_XOR_amoExec_i_ETC___d86;
      vcd_write_val(sim_hdl, num++, DEF_tmpData__h32, 128u);
      backing.DEF_tmpData__h32 = DEF_tmpData__h32;
      vcd_write_val(sim_hdl, num++, DEF_tmpData__h634, 128u);
      backing.DEF_tmpData__h634 = DEF_tmpData__h634;
      vcd_write_val(sim_hdl, num++, DEF_tmpData__h640, 128u);
      backing.DEF_tmpData__h640 = DEF_tmpData__h640;
      vcd_write_val(sim_hdl, num++, DEF_vIn__h1795, 128u);
      backing.DEF_vIn__h1795 = DEF_vIn__h1795;
      vcd_write_val(sim_hdl, num++, DEF_vOld__h1794, 128u);
      backing.DEF_vOld__h1794 = DEF_vOld__h1794;
      vcd_write_val(sim_hdl, num++, DEF_x__h325, 128u);
      backing.DEF_x__h325 = DEF_x__h325;
      vcd_write_val(sim_hdl, num++, DEF_x__h610, 128u);
      backing.DEF_x__h610 = DEF_x__h610;
      vcd_write_val(sim_hdl, num++, DEF_x__h611, 128u);
      backing.DEF_x__h611 = DEF_x__h611;
      vcd_write_val(sim_hdl, num++, DEF_x__h700, 128u);
      backing.DEF_x__h700 = DEF_x__h700;
      vcd_write_val(sim_hdl, num++, DEF_y__h326, 128u);
      backing.DEF_y__h326 = DEF_y__h326;
      vcd_write_val(sim_hdl, num++, DEF_y__h328, 128u);
      backing.DEF_y__h328 = DEF_y__h328;
      vcd_write_val(sim_hdl, num++, PORT_amoExec, 129u);
      backing.PORT_amoExec = PORT_amoExec;
      vcd_write_val(sim_hdl, num++, PORT_amoExec_current, 129u);
      backing.PORT_amoExec_current = PORT_amoExec_current;
      vcd_write_val(sim_hdl, num++, PORT_amoExec_inpt, 129u);
      backing.PORT_amoExec_inpt = PORT_amoExec_inpt;
    }
}
