/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sat Apr 18 22:34:52 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_prepareBoundsCheck.h"


/* Constructor */
MOD_module_prepareBoundsCheck::MOD_module_prepareBoundsCheck(tSimStateHdl simHdl,
							     char const *name,
							     Module *parent)
  : Module(simHdl, name, parent),
    DEF_ret__h1242(65u),
    DEF_ret__h3075(65u),
    DEF_x__h2870(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125(65u),
    DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152(65u),
    DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159(65u),
    DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163(65u),
    DEF_x__h1228(65u),
    DEF_result__h1833(65u),
    DEF_result__h3609(65u),
    DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67(65u),
    DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132(65u),
    DEF_addTop__h1240(65u),
    DEF_addTop__h3073(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161(65u),
    DEF__0_CONCAT_prepareBoundsCheck_size___d162(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158(65u),
    DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131(65u),
    DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172(201u),
    DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171(130u)
{
  PORT_prepareBoundsCheck_a.setSize(161u);
  PORT_prepareBoundsCheck_a.clear();
  PORT_prepareBoundsCheck_b.setSize(161u);
  PORT_prepareBoundsCheck_b.clear();
  PORT_prepareBoundsCheck_pcc.setSize(161u);
  PORT_prepareBoundsCheck_pcc.clear();
  PORT_prepareBoundsCheck_ddc.setSize(161u);
  PORT_prepareBoundsCheck_ddc.clear();
  PORT_prepareBoundsCheck.setSize(266u);
  PORT_prepareBoundsCheck.clear();
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_prepareBoundsCheck::init_symbols_0()
{
  init_symbol(&symbols[0u], "prepareBoundsCheck", SYM_PORT, &PORT_prepareBoundsCheck, 266u);
  init_symbol(&symbols[1u], "prepareBoundsCheck_a", SYM_PORT, &PORT_prepareBoundsCheck_a, 161u);
  init_symbol(&symbols[2u], "prepareBoundsCheck_b", SYM_PORT, &PORT_prepareBoundsCheck_b, 161u);
  init_symbol(&symbols[3u], "prepareBoundsCheck_ddc", SYM_PORT, &PORT_prepareBoundsCheck_ddc, 161u);
  init_symbol(&symbols[4u], "prepareBoundsCheck_pcc", SYM_PORT, &PORT_prepareBoundsCheck_pcc, 161u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_prepareBoundsCheck::METH_prepareBoundsCheck(tUWide ARG_prepareBoundsCheck_a,
							      tUWide ARG_prepareBoundsCheck_b,
							      tUWide ARG_prepareBoundsCheck_pcc,
							      tUWide ARG_prepareBoundsCheck_ddc,
							      tUInt64 ARG_prepareBoundsCheck_vaddr,
							      tUInt8 ARG_prepareBoundsCheck_size,
							      tUInt64 ARG_prepareBoundsCheck_toCheck)
{
  tUInt64 DEF_x__h127;
  tUInt64 DEF_mask__h2465;
  tUInt64 DEF_mask__h309;
  tUInt64 DEF_mask__h3074;
  tUInt64 DEF_mask__h1241;
  tUInt64 DEF_addBase__h2464;
  tUInt64 DEF_addBase__h308;
  tUInt8 DEF_x__h1792;
  tUInt8 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101;
  tUInt8 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23;
  tUInt32 DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53;
  tUInt32 DEF_x__h1302;
  tUInt32 DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29;
  tUInt32 DEF_x__h1012;
  tUInt64 DEF_x__h2004;
  tUInt8 DEF_prepareBoundsCheck_toCheck_BIT_21___d1;
  tUInt32 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75;
  tUInt8 DEF__1__h3539;
  tUInt8 DEF__1__h1763;
  tUInt8 DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2;
  tUInt8 DEF_x__h3568;
  tUInt8 DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30;
  tUInt8 DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33;
  tUInt8 DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36;
  tUInt8 DEF_topTip__h3076;
  tUInt8 DEF_topTip__h1243;
  tUInt8 DEF__theResult___fst_authority_idx__h1905;
  tUInt8 DEF__theResult___fst_authority_idx__h1899;
  tUInt8 DEF_x__h3597;
  tUInt32 DEF_thin_otype__h3960;
  tUInt32 DEF_a_capFat_bounds_baseBits__h821;
  tUInt32 DEF_a_capFat_bounds_topBits__h820;
  tUInt32 DEF_b_capFat_bounds_baseBits__h827;
  tUInt32 DEF_b_capFat_bounds_topBits__h826;
  tUInt32 DEF_pcc_capFat_bounds_baseBits__h833;
  tUInt32 DEF_pcc_capFat_bounds_topBits__h832;
  tUInt32 DEF_ddc_capFat_bounds_baseBits__h839;
  tUInt32 DEF_ddc_capFat_bounds_topBits__h838;
  tUInt64 DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105;
  tUInt64 DEF__theResult___snd_capFat_address__h735;
  tUInt64 DEF_x_BITS_63_TO_14___h1789;
  tUInt64 DEF_cap_address__h3922;
  tUInt64 DEF_cap_address__h4121;
  tUInt64 DEF_pcc_capFat_address__h671;
  tUInt64 DEF_ddc_capFat_address__h693;
  PORT_prepareBoundsCheck_a = ARG_prepareBoundsCheck_a;
  PORT_prepareBoundsCheck_b = ARG_prepareBoundsCheck_b;
  PORT_prepareBoundsCheck_pcc = ARG_prepareBoundsCheck_pcc;
  PORT_prepareBoundsCheck_ddc = ARG_prepareBoundsCheck_ddc;
  DEF_ddc_capFat_address__h693 = primExtract64(64u,
					       161u,
					       ARG_prepareBoundsCheck_ddc,
					       32u,
					       159u,
					       32u,
					       96u);
  DEF_pcc_capFat_address__h671 = primExtract64(64u,
					       161u,
					       ARG_prepareBoundsCheck_pcc,
					       32u,
					       159u,
					       32u,
					       96u);
  DEF_cap_address__h4121 = primExtract64(64u, 161u, ARG_prepareBoundsCheck_b, 32u, 159u, 32u, 96u);
  DEF_cap_address__h3922 = primExtract64(64u, 161u, ARG_prepareBoundsCheck_a, 32u, 159u, 32u, 96u);
  DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 = primExtract64(50u,
								  161u,
								  ARG_prepareBoundsCheck_a,
								  32u,
								  159u,
								  32u,
								  110u);
  DEF_ddc_capFat_bounds_topBits__h838 = primExtract32(14u,
						      161u,
						      ARG_prepareBoundsCheck_ddc,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_ddc_capFat_bounds_baseBits__h839 = ARG_prepareBoundsCheck_ddc.get_bits_in_word32(0u, 10u, 14u);
  DEF_pcc_capFat_bounds_topBits__h832 = primExtract32(14u,
						      161u,
						      ARG_prepareBoundsCheck_pcc,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_pcc_capFat_bounds_baseBits__h833 = ARG_prepareBoundsCheck_pcc.get_bits_in_word32(0u, 10u, 14u);
  DEF_b_capFat_bounds_topBits__h826 = primExtract32(14u,
						    161u,
						    ARG_prepareBoundsCheck_b,
						    32u,
						    37u,
						    32u,
						    24u);
  DEF_b_capFat_bounds_baseBits__h827 = ARG_prepareBoundsCheck_b.get_bits_in_word32(0u, 10u, 14u);
  DEF_a_capFat_bounds_topBits__h820 = primExtract32(14u,
						    161u,
						    ARG_prepareBoundsCheck_a,
						    32u,
						    37u,
						    32u,
						    24u);
  DEF_a_capFat_bounds_baseBits__h821 = ARG_prepareBoundsCheck_a.get_bits_in_word32(0u, 10u, 14u);
  DEF_thin_otype__h3960 = ARG_prepareBoundsCheck_a.get_bits_in_word32(1u, 13u, 10u);
  DEF_x__h3597 = ARG_prepareBoundsCheck_a.get_bits_in_word8(1u, 6u, 6u);
  DEF__theResult___fst_authority_idx__h1899 = (tUInt8)((tUInt8)63u & (ARG_prepareBoundsCheck_toCheck >> 6u));
  DEF__theResult___fst_authority_idx__h1905 = (tUInt8)((tUInt8)63u & ARG_prepareBoundsCheck_toCheck);
  DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36 = ARG_prepareBoundsCheck_ddc.get_bits_in_word8(0u,
											      0u,
											      2u);
  DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33 = ARG_prepareBoundsCheck_pcc.get_bits_in_word8(0u,
											      0u,
											      2u);
  DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30 = ARG_prepareBoundsCheck_b.get_bits_in_word8(0u, 0u, 2u);
  DEF_prepareBoundsCheck_toCheck_BIT_21___d1 = (tUInt8)((tUInt8)1u & (ARG_prepareBoundsCheck_toCheck >> 21u));
  DEF_x__h3568 = ARG_prepareBoundsCheck_a.get_bits_in_word8(0u, 0u, 2u);
  DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2 = (tUInt8)((tUInt8)3u & (ARG_prepareBoundsCheck_toCheck >> 19u));
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF__theResult___snd_capFat_address__h735 = DEF_cap_address__h3922;
    break;
  case (tUInt8)1u:
    DEF__theResult___snd_capFat_address__h735 = DEF_cap_address__h4121;
    break;
  case (tUInt8)2u:
    DEF__theResult___snd_capFat_address__h735 = DEF_pcc_capFat_address__h671;
    break;
  default:
    DEF__theResult___snd_capFat_address__h735 = DEF_ddc_capFat_address__h693;
  }
  DEF_x_BITS_63_TO_14___h1789 = (tUInt64)(DEF__theResult___snd_capFat_address__h735 >> 14u);
  DEF__1__h3539 = (tUInt8)((1125899906842623llu & (DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 + primShiftL64(50u,
														  50u,
														  (tUInt64)(primSignExt64(50u,
																	  2u,
																	  (tUInt8)(DEF_x__h3568))),
														  6u,
														  (tUInt8)(DEF_x__h3597)))) >> 49u);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_a_capFat_bounds_baseBits__h821;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_b_capFat_bounds_baseBits__h827;
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_pcc_capFat_bounds_baseBits__h833;
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_ddc_capFat_bounds_baseBits__h839;
  }
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)((DEF_cap_address__h3922 + 2llu) >> 32u))),
									      32u,
									      33u).set_whole_word((tUInt32)(DEF_cap_address__h3922 + 2llu),
												  0u);
  DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154.set_bits_in_word((tUInt8)(0llu),
									      2u,
									      0u,
									      1u).set_whole_word((tUInt32)(0llu),
												 1u).set_whole_word((((tUInt32)(4194303u & 0llu)) << 10u) | DEF_thin_otype__h3960,
														    0u);
  DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(DEF_cap_address__h4121 >> 32u))),
									  32u,
									  33u).set_whole_word((tUInt32)(DEF_cap_address__h4121),
											      0u);
  DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29 = 65535u & ((((tUInt32)(DEF_x__h3568)) << 14u) | DEF_a_capFat_bounds_baseBits__h821);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1012 = DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29;
    break;
  case (tUInt8)1u:
    DEF_x__h1012 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30)) << 14u) | DEF_b_capFat_bounds_baseBits__h827);
    break;
  case (tUInt8)2u:
    DEF_x__h1012 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33)) << 14u) | DEF_pcc_capFat_bounds_baseBits__h833);
    break;
  default:
    DEF_x__h1012 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36)) << 14u) | DEF_ddc_capFat_bounds_baseBits__h839);
  }
  DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_a.get_bits_in_word8(0u,
																  2u,
																  2u))) << 14u) | DEF_a_capFat_bounds_topBits__h820);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1302 = DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53;
    break;
  case (tUInt8)1u:
    DEF_x__h1302 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_b.get_bits_in_word8(0u,
										    2u,
										    2u))) << 14u) | DEF_b_capFat_bounds_topBits__h826);
    break;
  case (tUInt8)2u:
    DEF_x__h1302 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_pcc.get_bits_in_word8(0u,
										      2u,
										      2u))) << 14u) | DEF_pcc_capFat_bounds_topBits__h832);
    break;
  default:
    DEF_x__h1302 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_ddc.get_bits_in_word8(0u,
										      2u,
										      2u))) << 14u) | DEF_ddc_capFat_bounds_topBits__h838);
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = DEF_x__h3597;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_b.get_bits_in_word8(1u,
													      6u,
													      6u);
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_pcc.get_bits_in_word8(1u,
														6u,
														6u);
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_ddc.get_bits_in_word8(1u,
														6u,
														6u);
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = DEF__theResult___fst_authority_idx__h1899;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = DEF__theResult___fst_authority_idx__h1905;
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = (tUInt8)32u;
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = (tUInt8)33u;
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1792 = DEF_x__h3568;
    break;
  case (tUInt8)1u:
    DEF_x__h1792 = DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30;
    break;
  case (tUInt8)2u:
    DEF_x__h1792 = DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33;
    break;
  default:
    DEF_x__h1792 = DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36;
  }
  DEF__1__h1763 = (tUInt8)((1125899906842623llu & (DEF_x_BITS_63_TO_14___h1789 + primShiftL64(50u,
											      50u,
											      (tUInt64)(primSignExt64(50u,
														      2u,
														      (tUInt8)(DEF_x__h1792))),
											      6u,
											      (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23)))) >> 49u);
  wop_primSignExtWide(65u,
		      16u,
		      (tUInt32)(DEF_x__h1302),
		      DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67);
  wop_primSignExtWide(65u,
		      16u,
		      (tUInt32)(DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53),
		      DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132);
  wop_primShiftLWide(65u,
		     65u,
		     DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67,
		     6u,
		     (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23),
		     DEF_addTop__h1240);
  wop_primShiftLWide(65u,
		     65u,
		     DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132,
		     6u,
		     (tUInt8)(DEF_x__h3597),
		     DEF_addTop__h3073);
  DEF_addBase__h308 = primShiftL64(64u,
				   64u,
				   (tUInt64)(primSignExt64(64u, 16u, (tUInt32)(DEF_x__h1012))),
				   6u,
				   (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_addBase__h2464 = primShiftL64(64u,
				    64u,
				    (tUInt64)(primSignExt64(64u,
							    16u,
							    (tUInt32)(DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29))),
				    6u,
				    (tUInt8)(DEF_x__h3597));
  DEF_mask__h1241 = primShiftL64(51u,
				 51u,
				 2251799813685247llu,
				 6u,
				 (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_mask__h309 = primShiftL64(50u,
				50u,
				1125899906842623llu,
				6u,
				(tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_mask__h3074 = primShiftL64(51u, 51u, 2251799813685247llu, 6u, (tUInt8)(DEF_x__h3597));
  DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(ARG_prepareBoundsCheck_vaddr >> 32u))),
							       32u,
							       33u).set_whole_word((tUInt32)(ARG_prepareBoundsCheck_vaddr),
										   0u);
  DEF_mask__h2465 = primShiftL64(50u, 50u, 1125899906842623llu, 6u, (tUInt8)(DEF_x__h3597));
  switch ((tUInt8)((tUInt8)7u & (ARG_prepareBoundsCheck_toCheck >> 16u))) {
  case (tUInt8)0u:
    DEF_x__h2004 = DEF_cap_address__h3922;
    break;
  case (tUInt8)1u:
    DEF_x__h2004 = (((DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 & DEF_mask__h2465) << 14u) | (tUInt64)(0u)) + DEF_addBase__h2464;
    break;
  case (tUInt8)2u:
    DEF_x__h2004 = (tUInt64)(DEF_thin_otype__h3960);
    break;
  case (tUInt8)3u:
    DEF_x__h2004 = DEF_cap_address__h4121;
    break;
  default:
    DEF_x__h2004 = ARG_prepareBoundsCheck_vaddr;
  }
  DEF__0_CONCAT_prepareBoundsCheck_size___d162.set_bits_in_word((tUInt8)(0llu),
								2u,
								0u,
								1u).set_whole_word((tUInt32)(0llu),
										   1u).set_whole_word((((tUInt32)(33554431u & 0llu)) << 7u) | (tUInt32)(ARG_prepareBoundsCheck_size),
												      0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161,
	  DEF__0_CONCAT_prepareBoundsCheck_size___d162,
	  DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163);
  DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(DEF_cap_address__h3922 >> 32u))),
									  32u,
									  33u).set_whole_word((tUInt32)(DEF_cap_address__h3922),
											      0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158,
	  DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156,
	  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159);
  DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50.set_bits_in_word((tUInt8)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1789)) & DEF_mask__h1241) >> 50u),
										 2u,
										 0u,
										 1u).set_whole_word((tUInt32)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1789)) & DEF_mask__h1241) >> 18u),
												    1u).set_whole_word(((tUInt32)(262143u & ((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1789)) & DEF_mask__h1241))) << 14u,
														       0u);
  wop_add(DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50,
	  DEF_addTop__h1240,
	  DEF_ret__h1242);
  DEF_topTip__h1243 = primExtract8(2u, 65u, DEF_ret__h1242, 32u, 64u, 32u, 63u);
  DEF_result__h1833.build_concat(8589934591llu & ((((tUInt64)((tUInt8)1u & ~DEF_ret__h1242.get_bits_in_word8(2u,
													     0u,
													     1u))) << 32u) | (tUInt64)(DEF_ret__h1242.get_whole_word(1u))),
				 32u,
				 33u).set_whole_word(DEF_ret__h1242.get_whole_word(0u), 0u);
  DEF_x__h1228 = DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 < (tUInt8)51u && !(((tUInt8)3u & (DEF_topTip__h1243 - ((tUInt8)3u & (DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 == (tUInt8)50u ? (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 >> 13u) : DEF__1__h1763)))) <= (tUInt8)1u) ? DEF_result__h1833 : DEF_ret__h1242;
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131.set_bits_in_word((tUInt8)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3074) >> 50u),
										  2u,
										  0u,
										  1u).set_whole_word((tUInt32)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3074) >> 18u),
												     1u).set_whole_word(((tUInt32)(262143u & ((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3074))) << 14u,
															0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131,
	  DEF_addTop__h3073,
	  DEF_ret__h3075);
  DEF_topTip__h3076 = primExtract8(2u, 65u, DEF_ret__h3075, 32u, 64u, 32u, 63u);
  DEF_result__h3609.build_concat(8589934591llu & ((((tUInt64)((tUInt8)1u & ~DEF_ret__h3075.get_bits_in_word8(2u,
													     0u,
													     1u))) << 32u) | (tUInt64)(DEF_ret__h3075.get_whole_word(1u))),
				 32u,
				 33u).set_whole_word(DEF_ret__h3075.get_whole_word(0u), 0u);
  DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_x__h3597 < (tUInt8)51u && !(((tUInt8)3u & (DEF_topTip__h3076 - ((tUInt8)3u & (DEF_x__h3597 == (tUInt8)50u ? ARG_prepareBoundsCheck_a.get_bits_in_word8(0u,
																											     23u,
																											     1u) : DEF__1__h3539)))) <= (tUInt8)1u) ? DEF_result__h3609 : DEF_ret__h3075;
  switch ((tUInt8)((tUInt8)7u & (ARG_prepareBoundsCheck_toCheck >> 13u))) {
  case (tUInt8)0u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
    break;
  case (tUInt8)1u:
    DEF_x__h2870 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
    break;
  case (tUInt8)2u:
    DEF_x__h2870 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154;
    break;
  case (tUInt8)3u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
    break;
  case (tUInt8)4u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
    break;
  default:
    DEF_x__h2870 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
  }
  DEF_x__h127 = (((DEF_x_BITS_63_TO_14___h1789 & DEF_mask__h309) << 14u) | (tUInt64)(0u)) + DEF_addBase__h308;
  DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.set_bits_in_word((tUInt8)(DEF_x__h2004 >> 62u),
										 4u,
										 0u,
										 2u).set_whole_word((tUInt32)(DEF_x__h2004 >> 30u),
												    3u).set_whole_word((((tUInt32)(1073741823u & DEF_x__h2004)) << 2u) | (tUInt32)(primExtract8(2u,
																								65u,
																								DEF_x__h2870,
																								32u,
																								64u,
																								32u,
																								63u)),
														       2u).set_whole_word(primExtract32(32u,
																			65u,
																			DEF_x__h2870,
																			32u,
																			62u,
																			32u,
																			31u),
																	  1u).set_whole_word((DEF_x__h2870.get_bits_in_word32(0u,
																							      0u,
																							      31u) << 1u) | (tUInt32)((tUInt8)((tUInt8)1u & (ARG_prepareBoundsCheck_toCheck >> 12u))),
																			     0u);
  DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.set_bits_in_word(primExtract32(9u,
											       65u,
											       DEF_x__h1228,
											       32u,
											       64u,
											       32u,
											       56u),
										 6u,
										 0u,
										 9u).set_whole_word(primExtract32(32u,
														  65u,
														  DEF_x__h1228,
														  32u,
														  55u,
														  32u,
														  24u),
												    5u).set_whole_word(((DEF_x__h1228.get_bits_in_word32(0u,
																			 0u,
																			 24u) << 8u) | (((tUInt32)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101)) << 2u)) | (tUInt32)(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_bits_in_word8(4u,
																																										       0u,
																																										       2u)),
														       4u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(3u),
																	  3u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(2u),
																			     2u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(1u),
																						1u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(0u),
																								   0u);
  PORT_prepareBoundsCheck.set_bits_in_word(1023u & ((((tUInt32)(DEF_prepareBoundsCheck_toCheck_BIT_21___d1)) << 9u) | (tUInt32)(DEF_x__h127 >> 55u)),
					   8u,
					   0u,
					   10u).set_whole_word((tUInt32)(DEF_x__h127 >> 23u),
							       7u).set_whole_word((((tUInt32)(8388607u & DEF_x__h127)) << 9u) | DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_bits_in_word32(6u,
																										 0u,
																										 9u),
										  6u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(5u),
												     5u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(4u),
															4u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(3u),
																	   3u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(2u),
																			      2u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(1u),
																						 1u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(0u),
																								    0u);
  return PORT_prepareBoundsCheck;
}

tUInt8 MOD_module_prepareBoundsCheck::METH_RDY_prepareBoundsCheck()
{
  tUInt8 PORT_RDY_prepareBoundsCheck;
  tUInt8 DEF_CAN_FIRE_prepareBoundsCheck;
  DEF_CAN_FIRE_prepareBoundsCheck = (tUInt8)1u;
  PORT_RDY_prepareBoundsCheck = DEF_CAN_FIRE_prepareBoundsCheck;
  return PORT_RDY_prepareBoundsCheck;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_prepareBoundsCheck::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_prepareBoundsCheck::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 29u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172", 201u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152", 65u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164", 65u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171", 130u);
  vcd_write_def(sim_hdl, num++, "SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67", 65u);
  vcd_write_def(sim_hdl, num++, "SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132", 65u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154", 65u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_prepareBoundsCheck_size___d162", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_vaddr___d161", 65u);
  vcd_write_def(sim_hdl, num++, "addTop__h1240", 65u);
  vcd_write_def(sim_hdl, num++, "addTop__h3073", 65u);
  vcd_write_def(sim_hdl, num++, "result__h1833", 65u);
  vcd_write_def(sim_hdl, num++, "result__h3609", 65u);
  vcd_write_def(sim_hdl, num++, "ret__h1242", 65u);
  vcd_write_def(sim_hdl, num++, "ret__h3075", 65u);
  vcd_write_def(sim_hdl, num++, "x__h1228", 65u);
  vcd_write_def(sim_hdl, num++, "x__h2870", 65u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck", 266u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_a", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_b", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_ddc", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_pcc", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_prepareBoundsCheck::dump_VCD(tVCDDumpType dt,
					     unsigned int levels,
					     MOD_module_prepareBoundsCheck &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_prepareBoundsCheck::vcd_defs(tVCDDumpType dt,
					     MOD_module_prepareBoundsCheck &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 201u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 130u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 266u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172) != DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172, 201u);
	backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172 = DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152) != DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152, 65u);
	backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164) != DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164, 65u);
	backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171) != DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171, 130u);
	backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171 = DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171;
      }
      ++num;
      if ((backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67) != DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67, 65u);
	backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67 = DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67;
      }
      ++num;
      if ((backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132) != DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132, 65u);
	backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132 = DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154) != DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154, 65u);
	backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162) != DEF__0_CONCAT_prepareBoundsCheck_size___d162)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_prepareBoundsCheck_size___d162, 65u);
	backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162 = DEF__0_CONCAT_prepareBoundsCheck_size___d162;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50) != DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50, 65u);
	backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50 = DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156) != DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163) != DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161) != DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161;
      }
      ++num;
      if ((backing.DEF_addTop__h1240) != DEF_addTop__h1240)
      {
	vcd_write_val(sim_hdl, num, DEF_addTop__h1240, 65u);
	backing.DEF_addTop__h1240 = DEF_addTop__h1240;
      }
      ++num;
      if ((backing.DEF_addTop__h3073) != DEF_addTop__h3073)
      {
	vcd_write_val(sim_hdl, num, DEF_addTop__h3073, 65u);
	backing.DEF_addTop__h3073 = DEF_addTop__h3073;
      }
      ++num;
      if ((backing.DEF_result__h1833) != DEF_result__h1833)
      {
	vcd_write_val(sim_hdl, num, DEF_result__h1833, 65u);
	backing.DEF_result__h1833 = DEF_result__h1833;
      }
      ++num;
      if ((backing.DEF_result__h3609) != DEF_result__h3609)
      {
	vcd_write_val(sim_hdl, num, DEF_result__h3609, 65u);
	backing.DEF_result__h3609 = DEF_result__h3609;
      }
      ++num;
      if ((backing.DEF_ret__h1242) != DEF_ret__h1242)
      {
	vcd_write_val(sim_hdl, num, DEF_ret__h1242, 65u);
	backing.DEF_ret__h1242 = DEF_ret__h1242;
      }
      ++num;
      if ((backing.DEF_ret__h3075) != DEF_ret__h3075)
      {
	vcd_write_val(sim_hdl, num, DEF_ret__h3075, 65u);
	backing.DEF_ret__h3075 = DEF_ret__h3075;
      }
      ++num;
      if ((backing.DEF_x__h1228) != DEF_x__h1228)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1228, 65u);
	backing.DEF_x__h1228 = DEF_x__h1228;
      }
      ++num;
      if ((backing.DEF_x__h2870) != DEF_x__h2870)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2870, 65u);
	backing.DEF_x__h2870 = DEF_x__h2870;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck) != PORT_prepareBoundsCheck)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck, 266u);
	backing.PORT_prepareBoundsCheck = PORT_prepareBoundsCheck;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_a) != PORT_prepareBoundsCheck_a)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_a, 161u);
	backing.PORT_prepareBoundsCheck_a = PORT_prepareBoundsCheck_a;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_b) != PORT_prepareBoundsCheck_b)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_b, 161u);
	backing.PORT_prepareBoundsCheck_b = PORT_prepareBoundsCheck_b;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_ddc) != PORT_prepareBoundsCheck_ddc)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_ddc, 161u);
	backing.PORT_prepareBoundsCheck_ddc = PORT_prepareBoundsCheck_ddc;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_pcc) != PORT_prepareBoundsCheck_pcc)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_pcc, 161u);
	backing.PORT_prepareBoundsCheck_pcc = PORT_prepareBoundsCheck_pcc;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172, 201u);
      backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172 = DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152, 65u);
      backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164, 65u);
      backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171, 130u);
      backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171 = DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67, 65u);
      backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67 = DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132, 65u);
      backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132 = DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154, 65u);
      backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_54_TO_45_13___d154;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_prepareBoundsCheck_size___d162, 65u);
      backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162 = DEF__0_CONCAT_prepareBoundsCheck_size___d162;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50, 65u);
      backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50 = DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161;
      vcd_write_val(sim_hdl, num++, DEF_addTop__h1240, 65u);
      backing.DEF_addTop__h1240 = DEF_addTop__h1240;
      vcd_write_val(sim_hdl, num++, DEF_addTop__h3073, 65u);
      backing.DEF_addTop__h3073 = DEF_addTop__h3073;
      vcd_write_val(sim_hdl, num++, DEF_result__h1833, 65u);
      backing.DEF_result__h1833 = DEF_result__h1833;
      vcd_write_val(sim_hdl, num++, DEF_result__h3609, 65u);
      backing.DEF_result__h3609 = DEF_result__h3609;
      vcd_write_val(sim_hdl, num++, DEF_ret__h1242, 65u);
      backing.DEF_ret__h1242 = DEF_ret__h1242;
      vcd_write_val(sim_hdl, num++, DEF_ret__h3075, 65u);
      backing.DEF_ret__h3075 = DEF_ret__h3075;
      vcd_write_val(sim_hdl, num++, DEF_x__h1228, 65u);
      backing.DEF_x__h1228 = DEF_x__h1228;
      vcd_write_val(sim_hdl, num++, DEF_x__h2870, 65u);
      backing.DEF_x__h2870 = DEF_x__h2870;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck, 266u);
      backing.PORT_prepareBoundsCheck = PORT_prepareBoundsCheck;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_a, 161u);
      backing.PORT_prepareBoundsCheck_a = PORT_prepareBoundsCheck_a;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_b, 161u);
      backing.PORT_prepareBoundsCheck_b = PORT_prepareBoundsCheck_b;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_ddc, 161u);
      backing.PORT_prepareBoundsCheck_ddc = PORT_prepareBoundsCheck_ddc;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_pcc, 161u);
      backing.PORT_prepareBoundsCheck_pcc = PORT_prepareBoundsCheck_pcc;
    }
}
